// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ConfigSettingContractHistoricalDataV0
 * {
 *     int64 feeHistorical1KB; // Fee for storing 1KB in archives
 * };
 */
data class ConfigSettingContractHistoricalDataV0Xdr(
  /** Fee for storing 1KB in archives */
  val feeHistorical1Kb: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ConfigSettingContractHistoricalDataV0Xdr {
      val feeHistorical1Kb = Int64Xdr.decode(reader)
      return ConfigSettingContractHistoricalDataV0Xdr(feeHistorical1Kb)
    }
  }

  fun encode(writer: XdrWriter) {
    feeHistorical1Kb.encode(writer)
  }
}
