// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ConfigSettingContractParallelComputeV0
 * {
 *     // Maximum number of clusters with dependent transactions allowed in a
 *     // stage of parallel tx set component.
 *     // This effectively sets the lower bound on the number of physical threads
 *     // necessary to effectively apply transaction sets in parallel.
 *     uint32 ledgerMaxDependentTxClusters;
 * };
 */
data class ConfigSettingContractParallelComputeV0Xdr(
  /**
   * Maximum number of clusters with dependent transactions allowed in a
   * stage of parallel tx set component.
   * This effectively sets the lower bound on the number of physical threads
   * necessary to effectively apply transaction sets in parallel.
   */
  val ledgerMaxDependentTxClusters: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ConfigSettingContractParallelComputeV0Xdr {
      val ledgerMaxDependentTxClusters = Uint32Xdr.decode(reader)
      return ConfigSettingContractParallelComputeV0Xdr(ledgerMaxDependentTxClusters)
    }
  }

  fun encode(writer: XdrWriter) {
    ledgerMaxDependentTxClusters.encode(writer)
  }
}
