// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

const val CONTRACT_COST_COUNT_LIMIT: Int = 1024
const val SC_SPEC_DOC_LIMIT: Int = 1024
const val SCSYMBOL_LIMIT: Int = 32
const val MASK_ACCOUNT_FLAGS: Int = 0x7
const val MASK_ACCOUNT_FLAGS_V17: Int = 0xF
const val MAX_SIGNERS: Int = 20
const val MASK_TRUSTLINE_FLAGS: Int = 1
const val MASK_TRUSTLINE_FLAGS_V13: Int = 3
const val MASK_TRUSTLINE_FLAGS_V17: Int = 7
const val MASK_OFFERENTRY_FLAGS: Int = 1
const val MASK_CLAIMABLE_BALANCE_FLAGS: Int = 0x1
const val MASK_LEDGER_HEADER_FLAGS: Int = 0x7
const val AUTH_MSG_FLAG_FLOW_CONTROL_BYTES_REQUESTED: Int = 200
const val TX_ADVERT_VECTOR_MAX_SIZE: Int = 1000
const val TX_DEMAND_VECTOR_MAX_SIZE: Int = 1000
const val MAX_OPS_PER_TX: Int = 100
const val LIQUIDITY_POOL_FEE_V18: Int = 30
