// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * union switch (int v)
 *     {
 *     case 0:
 *         struct
 *         {
 *             SCVal topics<>;
 *             SCVal data;
 *         } v0;
 *     }
 */
sealed class ContractEventBodyXdr {
  abstract val discriminant: Int

  data class V0(
    val value: ContractEventV0Xdr
  ) : ContractEventBodyXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): ContractEventBodyXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> {
          val value = ContractEventV0Xdr.decode(reader)
          V0(value)
        }
        else -> throw IllegalArgumentException("Unknown ContractEventBodyXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is V0 -> {
        value.encode(writer)
      }
    }
  }
}
