// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct CreateContractArgs
 * {
 *     ContractIDPreimage contractIDPreimage;
 *     ContractExecutable executable;
 * };
 */
data class CreateContractArgsXdr(
  val contractIdPreimage: ContractIDPreimageXdr,
  val executable: ContractExecutableXdr
) {
  companion object {

    fun decode(reader: XdrReader): CreateContractArgsXdr {
      val contractIdPreimage = ContractIDPreimageXdr.decode(reader)
      val executable = ContractExecutableXdr.decode(reader)
      return CreateContractArgsXdr(contractIdPreimage, executable)
    }
  }

  fun encode(writer: XdrWriter) {
    contractIdPreimage.encode(writer)
    executable.encode(writer)
  }
}
