// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct DontHave
 * {
 *     MessageType type;
 *     uint256 reqHash;
 * };
 */
data class DontHaveXdr(
  val type: MessageTypeXdr,
  val reqHash: Uint256Xdr
) {
  companion object {

    fun decode(reader: XdrReader): DontHaveXdr {
      val type = MessageTypeXdr.decode(reader)
      val reqHash = Uint256Xdr.decode(reader)
      return DontHaveXdr(type, reqHash)
    }
  }

  fun encode(writer: XdrWriter) {
    type.encode(writer)
    reqHash.encode(writer)
  }
}
