// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct FloodDemand
 * {
 *     TxDemandVector txHashes;
 * };
 */
data class FloodDemandXdr(
  val txHashes: TxDemandVectorXdr
) {
  companion object {

    fun decode(reader: XdrReader): FloodDemandXdr {
      val txHashes = TxDemandVectorXdr.decode(reader)
      return FloodDemandXdr(txHashes)
    }
  }

  fun encode(writer: XdrWriter) {
    txHashes.encode(writer)
  }
}
