// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * union LedgerCloseMetaExt switch (int v)
 * {
 * case 0:
 *     void;
 * case 1:
 *     LedgerCloseMetaExtV1 v1;
 * };
 */
sealed class LedgerCloseMetaExtXdr {
  abstract val discriminant: Int

  data class V1(
    val value: LedgerCloseMetaExtV1Xdr
  ) : LedgerCloseMetaExtXdr() {
    override val discriminant: Int = 1
  }

  data object Void : LedgerCloseMetaExtXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): LedgerCloseMetaExtXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> Void
        1 -> {
          val value = LedgerCloseMetaExtV1Xdr.decode(reader)
          V1(value)
        }
        else -> throw IllegalArgumentException("Unknown LedgerCloseMetaExtXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is Void -> {}
      is V1 -> {
        value.encode(writer)
      }
    }
  }
}
