// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct Liabilities
 * {
 *     int64 buying;
 *     int64 selling;
 * };
 */
data class LiabilitiesXdr(
  val buying: Int64Xdr,
  val selling: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): LiabilitiesXdr {
      val buying = Int64Xdr.decode(reader)
      val selling = Int64Xdr.decode(reader)
      return LiabilitiesXdr(buying, selling)
    }
  }

  fun encode(writer: XdrWriter) {
    buying.encode(writer)
    selling.encode(writer)
  }
}
