// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef PublicKey NodeID;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class NodeIDXdr(val value: PublicKeyXdr) {
  companion object {
    fun decode(reader: XdrReader): NodeIDXdr {
      val value = PublicKeyXdr.decode(reader)
      return NodeIDXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    value.encode(writer)
  }
}
