// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct OperationMetaV2
 * {
 *     ExtensionPoint ext;
 * 
 *     LedgerEntryChanges changes;
 * 
 *     ContractEvent events<>;
 * };
 */
data class OperationMetaV2Xdr(
  val ext: ExtensionPointXdr,
  val changes: LedgerEntryChangesXdr,
  val events: List<ContractEventXdr>
) {
  companion object {

    fun decode(reader: XdrReader): OperationMetaV2Xdr {
      val ext = ExtensionPointXdr.decode(reader)
      val changes = LedgerEntryChangesXdr.decode(reader)
      val events = List(reader.readInt()) { ContractEventXdr.decode(reader) }
      return OperationMetaV2Xdr(ext, changes, events)
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    changes.encode(writer)
    writer.writeInt(events.size)
    events.forEach { item ->
      item.encode(writer)
    }
  }
}
