// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * enum RevokeSponsorshipResultCode
 * {
 *     // codes considered as "success" for the operation
 *     REVOKE_SPONSORSHIP_SUCCESS = 0,
 * 
 *     // codes considered as "failure" for the operation
 *     REVOKE_SPONSORSHIP_DOES_NOT_EXIST = -1,
 *     REVOKE_SPONSORSHIP_NOT_SPONSOR = -2,
 *     REVOKE_SPONSORSHIP_LOW_RESERVE = -3,
 *     REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE = -4,
 *     REVOKE_SPONSORSHIP_MALFORMED = -5
 * };
 */
enum class RevokeSponsorshipResultCodeXdr(val value: Int) {
  /** codes considered as "success" for the operation */
  REVOKE_SPONSORSHIP_SUCCESS(0),
  /** codes considered as "failure" for the operation */
  REVOKE_SPONSORSHIP_DOES_NOT_EXIST(-1),
  REVOKE_SPONSORSHIP_NOT_SPONSOR(-2),
  REVOKE_SPONSORSHIP_LOW_RESERVE(-3),
  REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE(-4),
  REVOKE_SPONSORSHIP_MALFORMED(-5);

  companion object {

    fun decode(reader: XdrReader): RevokeSponsorshipResultCodeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown RevokeSponsorshipResultCodeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
