// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct {
 *         uint32 protocol;
 *         uint32 preRelease;
 *     }
 */
data class SCEnvMetaEntryInterfaceVersionXdr(
  val protocol: Uint32Xdr,
  val preRelease: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCEnvMetaEntryInterfaceVersionXdr {
      val protocol = Uint32Xdr.decode(reader)
      val preRelease = Uint32Xdr.decode(reader)
      return SCEnvMetaEntryInterfaceVersionXdr(protocol, preRelease)
    }
  }

  fun encode(writer: XdrWriter) {
    protocol.encode(writer)
    preRelease.encode(writer)
  }
}
