// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCPBallot
 * {
 *     uint32 counter; // n
 *     Value value;    // x
 * };
 */
data class SCPBallotXdr(
  /** n */
  val counter: Uint32Xdr,
  /** x */
  val value: ValueXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCPBallotXdr {
      val counter = Uint32Xdr.decode(reader)
      val value = ValueXdr.decode(reader)
      return SCPBallotXdr(counter, value)
    }
  }

  fun encode(writer: XdrWriter) {
    counter.encode(writer)
    value.encode(writer)
  }
}
