// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * union SCPHistoryEntry switch (int v)
 * {
 * case 0:
 *     SCPHistoryEntryV0 v0;
 * };
 */
sealed class SCPHistoryEntryXdr {
  abstract val discriminant: Int

  data class V0(
    val value: SCPHistoryEntryV0Xdr
  ) : SCPHistoryEntryXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): SCPHistoryEntryXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> {
          val value = SCPHistoryEntryV0Xdr.decode(reader)
          V0(value)
        }
        else -> throw IllegalArgumentException("Unknown SCPHistoryEntryXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is V0 -> {
        value.encode(writer)
      }
    }
  }
}
