// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * enum SCSpecEntryKind
 * {
 *     SC_SPEC_ENTRY_FUNCTION_V0 = 0,
 *     SC_SPEC_ENTRY_UDT_STRUCT_V0 = 1,
 *     SC_SPEC_ENTRY_UDT_UNION_V0 = 2,
 *     SC_SPEC_ENTRY_UDT_ENUM_V0 = 3,
 *     SC_SPEC_ENTRY_UDT_ERROR_ENUM_V0 = 4,
 *     SC_SPEC_ENTRY_EVENT_V0 = 5
 * };
 */
enum class SCSpecEntryKindXdr(val value: Int) {
  SC_SPEC_ENTRY_FUNCTION_V0(0),
  SC_SPEC_ENTRY_UDT_STRUCT_V0(1),
  SC_SPEC_ENTRY_UDT_UNION_V0(2),
  SC_SPEC_ENTRY_UDT_ENUM_V0(3),
  SC_SPEC_ENTRY_UDT_ERROR_ENUM_V0(4),
  SC_SPEC_ENTRY_EVENT_V0(5);

  companion object {

    fun decode(reader: XdrReader): SCSpecEntryKindXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown SCSpecEntryKindXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
