// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecTypeUDT
 * {
 *     string name<60>;
 * };
 */
data class SCSpecTypeUDTXdr(
  val name: String
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeUDTXdr {
      val name = reader.readString()
      return SCSpecTypeUDTXdr(name)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(name)
  }
}
