// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecTypeBytesN
 * {
 *     uint32 n;
 * };
 */
data class SCSpecTypeBytesNXdr(
  val n: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeBytesNXdr {
      val n = Uint32Xdr.decode(reader)
      return SCSpecTypeBytesNXdr(n)
    }
  }

  fun encode(writer: XdrWriter) {
    n.encode(writer)
  }
}
