// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecTypeTuple
 * {
 *     SCSpecTypeDef valueTypes<12>;
 * };
 */
data class SCSpecTypeTupleXdr(
  val valueTypes: List<SCSpecTypeDefXdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeTupleXdr {
      val valueTypes = List(reader.readInt()) { SCSpecTypeDefXdr.decode(reader) }
      return SCSpecTypeTupleXdr(valueTypes)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(valueTypes.size)
    valueTypes.forEach { item ->
      item.encode(writer)
    }
  }
}
