// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecUDTErrorEnumCaseV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string name<60>;
 *     uint32 value;
 * };
 */
data class SCSpecUDTErrorEnumCaseV0Xdr(
  val doc: String,
  val name: String,
  val value: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecUDTErrorEnumCaseV0Xdr {
      val doc = reader.readString()
      val name = reader.readString()
      val value = Uint32Xdr.decode(reader)
      return SCSpecUDTErrorEnumCaseV0Xdr(doc, name, value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(name)
    value.encode(writer)
  }
}
