// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SignedTimeSlicedSurveyStartCollectingMessage
 * {
 *     Signature signature;
 *     TimeSlicedSurveyStartCollectingMessage startCollecting;
 * };
 */
data class SignedTimeSlicedSurveyStartCollectingMessageXdr(
  val signature: SignatureXdr,
  val startCollecting: TimeSlicedSurveyStartCollectingMessageXdr
) {
  companion object {

    fun decode(reader: XdrReader): SignedTimeSlicedSurveyStartCollectingMessageXdr {
      val signature = SignatureXdr.decode(reader)
      val startCollecting = TimeSlicedSurveyStartCollectingMessageXdr.decode(reader)
      return SignedTimeSlicedSurveyStartCollectingMessageXdr(signature, startCollecting)
    }
  }

  fun encode(writer: XdrWriter) {
    signature.encode(writer)
    startCollecting.encode(writer)
  }
}
