// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef opaque SignatureHint[4];
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class SignatureHintXdr(val value: ByteArray) {
  companion object {
    fun decode(reader: XdrReader): SignatureHintXdr {
      val value = reader.readFixedOpaque(4)
      return SignatureHintXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeFixedOpaque(value, 4)
  }
}
