// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * enum SorobanCredentialsType
 * {
 *     SOROBAN_CREDENTIALS_SOURCE_ACCOUNT = 0,
 *     SOROBAN_CREDENTIALS_ADDRESS = 1
 * };
 */
enum class SorobanCredentialsTypeXdr(val value: Int) {
  SOROBAN_CREDENTIALS_SOURCE_ACCOUNT(0),
  SOROBAN_CREDENTIALS_ADDRESS(1);

  companion object {

    fun decode(reader: XdrReader): SorobanCredentialsTypeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown SorobanCredentialsTypeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
