// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SorobanResourcesExtV0
 * {
 *     // Vector of indices representing what Soroban
 *     // entries in the footprint are archived, based on the
 *     // order of keys provided in the readWrite footprint.
 *     uint32 archivedSorobanEntries<>;
 * };
 */
data class SorobanResourcesExtV0Xdr(
  val archivedSorobanEntries: List<Uint32Xdr>
) {
  companion object {

    fun decode(reader: XdrReader): SorobanResourcesExtV0Xdr {
      val archivedSorobanEntries = List(reader.readInt()) { Uint32Xdr.decode(reader) }
      return SorobanResourcesExtV0Xdr(archivedSorobanEntries)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(archivedSorobanEntries.size)
    archivedSorobanEntries.forEach { item ->
      item.encode(writer)
    }
  }
}
