// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef AccountID* SponsorshipDescriptor;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class SponsorshipDescriptorXdr(val value: AccountIDXdr?) {
  companion object {
    fun decode(reader: XdrReader): SponsorshipDescriptorXdr {
      val value = if (reader.readBoolean()) AccountIDXdr.decode(reader) else null
      return SponsorshipDescriptorXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    if (value != null) {
      writer.writeBoolean(true)
      value.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
  }
}
