// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct StoredDebugTransactionSet
 * {
 * 	StoredTransactionSet txSet;
 * 	uint32 ledgerSeq;
 * 	StellarValue scpValue;
 * };
 */
data class StoredDebugTransactionSetXdr(
  val txSet: StoredTransactionSetXdr,
  val ledgerSeq: Uint32Xdr,
  val scpValue: StellarValueXdr
) {
  companion object {

    fun decode(reader: XdrReader): StoredDebugTransactionSetXdr {
      val txSet = StoredTransactionSetXdr.decode(reader)
      val ledgerSeq = Uint32Xdr.decode(reader)
      val scpValue = StellarValueXdr.decode(reader)
      return StoredDebugTransactionSetXdr(txSet, ledgerSeq, scpValue)
    }
  }

  fun encode(writer: XdrWriter) {
    txSet.encode(writer)
    ledgerSeq.encode(writer)
    scpValue.encode(writer)
  }
}
