// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef string string64<64>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class String64Xdr(val value: String) {
  companion object {
    fun decode(reader: XdrReader): String64Xdr {
      val value = reader.readString()
      return String64Xdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(value)
  }
}
