// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * enum SurveyMessageCommandType
 * {
 *     TIME_SLICED_SURVEY_TOPOLOGY = 1
 * };
 */
enum class SurveyMessageCommandTypeXdr(val value: Int) {
  TIME_SLICED_SURVEY_TOPOLOGY(1);

  companion object {

    fun decode(reader: XdrReader): SurveyMessageCommandTypeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown SurveyMessageCommandTypeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
