// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct TransactionSetV1
 * {
 *     Hash previousLedgerHash;
 *     TransactionPhase phases<>;
 * };
 */
data class TransactionSetV1Xdr(
  val previousLedgerHash: HashXdr,
  val phases: List<TransactionPhaseXdr>
) {
  companion object {

    fun decode(reader: XdrReader): TransactionSetV1Xdr {
      val previousLedgerHash = HashXdr.decode(reader)
      val phases = List(reader.readInt()) { TransactionPhaseXdr.decode(reader) }
      return TransactionSetV1Xdr(previousLedgerHash, phases)
    }
  }

  fun encode(writer: XdrWriter) {
    previousLedgerHash.encode(writer)
    writer.writeInt(phases.size)
    phases.forEach { item ->
      item.encode(writer)
    }
  }
}
