// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.stellar.sdk.xdr

/**
 * XDR Source:
 * struct TrustLineEntryExtensionV2
 * {
 *     int32 liquidityPoolUseCount;
 * 
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 */
data class TrustLineEntryExtensionV2Xdr(
  val liquidityPoolUseCount: Int32Xdr,
  val ext: TrustLineEntryExtensionV2ExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): TrustLineEntryExtensionV2Xdr {
      val liquidityPoolUseCount = Int32Xdr.decode(reader)
      val ext = TrustLineEntryExtensionV2ExtXdr.decode(reader)
      return TrustLineEntryExtensionV2Xdr(liquidityPoolUseCount, ext)
    }
  }

  fun encode(writer: XdrWriter) {
    liquidityPoolUseCount.encode(writer)
    ext.encode(writer)
  }
}
