// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef opaque DataBlob<>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class DataBlobXdr(val value: ByteArray) {
  companion object {
    fun decode(reader: XdrReader): DataBlobXdr {
      val value = reader.readVariableOpaque()
      return DataBlobXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeVariableOpaque(value)
  }
}
