// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "Int32Xdr"

/**
 * XDR Source:
 * typedef int Int32;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class Int32Xdr(val value: Int) {
  companion object {
    fun decode(reader: XdrReader): Int32Xdr {
      val value = reader.readInt()
      return Int32Xdr(value)
    }

    fun fromXdrJson(json: String): Int32Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): Int32Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): Int32Xdr = Int32Xdr(XdrJson.int32(element, XDR_JSON_TYPE, "value"))
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.int32(value)

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
