// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef int IntList<100>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class IntListXdr(val value: List<Int>) {
  companion object {
    fun decode(reader: XdrReader): IntListXdr {
      val value = List(reader.readInt()) { reader.readInt() }
      return IntListXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value.size)
    value.forEach { item ->
      writer.writeInt(item)
    }
  }
}
