// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct KeywordStruct
 * {
 *     int val;
 *     string when<32>;
 * };
 */
data class KeywordStructXdr(
  val `val`: Int,
  val `when`: String
) {
  companion object {

    fun decode(reader: XdrReader): KeywordStructXdr {
      val value = reader.readInt()
      val when = reader.readString()
      return KeywordStructXdr(value, when)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(`val`)
    writer.writeString(`when`)
  }
}
