// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef SignedCount MyCounter;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class MyCounterXdr(val value: SignedCountXdr) {
  companion object {
    fun decode(reader: XdrReader): MyCounterXdr {
      val value = SignedCountXdr.decode(reader)
      return MyCounterXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    value.encode(writer)
  }
}
