// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "SCValTypeXdr"

/**
 * XDR Source:
 * enum SCValType
 * {
 *     SCV_STRING = 14,
 *     SCV_EXECUTABLE_TAG = 22
 * };
 */
enum class SCValTypeXdr(val value: Int, internal val xdrJsonName: String) {
  SCV_STRING(14, "string"),
  SCV_EXECUTABLE_TAG(22, "executable_tag");

  companion object {

    fun decode(reader: XdrReader): SCValTypeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown SCValTypeXdr value: $value")
    }

    fun fromXdrJson(json: String): SCValTypeXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCValTypeXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCValTypeXdr {
      val name = XdrJson.name(element, XDR_JSON_TYPE)
      return findXdrJsonName(name) ?: XdrJson.unknownMember(XDR_JSON_TYPE, name)
    }

    internal fun findXdrJsonName(name: String): SCValTypeXdr? = entries.find { it.xdrJsonName == name }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.name(xdrJsonName)

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
