// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * enum StatusCode
 * {
 *     STATUS_OK = 0,
 *     STATUS_NOT_FOUND = 1,
 *     STATUS_ERROR = 2,
 *     STATUS_UNKNOWN = -1
 * };
 */
enum class StatusCodeXdr(val value: Int) {
  STATUS_OK(0),
  STATUS_NOT_FOUND(1),
  STATUS_ERROR(2),
  STATUS_UNKNOWN(-1);

  companion object {

    fun decode(reader: XdrReader): StatusCodeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown StatusCodeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
