version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: bundler
    directory: /tools/xdrgen-kt
    schedule:
      interval: monthly
    groups:
      bundler:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
