# frozen_string_literal: true

require_relative 'kotlin_json_names'
require_relative 'kotlin_json_overrides'

module Xdrgen
  module Generators
    # Kotlin code generator for XDR definitions
    # Generates idiomatic Kotlin code with proper type mappings:
    # - enum -> enum class
    # - struct -> data class
    # - union -> sealed hierarchy
    # - arrays -> List<T> or ByteArray
    # - strings -> String
    # - opaque -> ByteArray
    class Kotlin < Base
      # Structs that contain a variable-length array of themselves (directly recursive).
      # Their generated decode method wraps each recursive element with depth-guard calls.
      RECURSIVE_TYPES = %w[SorobanDelegateSignatureXdr].freeze
      XDR_RECURSION_CAP = 128

      # XDR string positions that carry arbitrary bytes rather than text: the CAP-85
      # executable tag, which the ledger matches byte for byte. Each entry maps an XDR
      # type name from the .x source to the string fields (struct) or arms (union) at
      # that type that are emitted as ByteArray, bypassing the string wrapper type, so
      # content that is not valid UTF-8 survives a decode/encode round trip exactly.
      # Only the named positions change; every other use of the same string typedef
      # keeps the generic emission.
      BYTES_BACKED_STRING_FIELDS = {
        'ContractExecutableExternalRef' => %w[tag].freeze,
        'SCVal' => %w[executable_tag].freeze
      }.freeze

      JSON_NAMES = KotlinJsonNames
      JSON_OVERRIDES = KotlinJsonOverrides

      JSON_ELEMENT_IMPORT = 'kotlinx.serialization.json.JsonElement'
      JSON_OBJECT_IMPORT = 'kotlinx.serialization.json.JsonObject'
      JSON_BUILDER_IMPORT = 'kotlinx.serialization.json.buildJsonObject'

      # Every generated file names its own type once, in a file-private constant, and the
      # XDR-JSON methods refer to that constant wherever the name would otherwise be repeated
      # at each call site.
      JSON_TYPE_CONSTANT = 'XDR_JSON_TYPE'

      # A struct names the keys it accepts once, beside its type name, so the decoder can reject
      # a key that belongs to no field without rebuilding the list at every call.
      JSON_KEYS_CONSTANT = 'XDR_JSON_KEYS'

      # A field named "type" is spelled "type_" by tooling that escapes it as a keyword of its
      # own language. SEP-0051 requires the key "type", so that is what this SDK emits; the
      # older spelling is accepted on input and never written back out.
      JSON_KEY_ALIASES = { 'type' => 'type_' }.freeze

      def generate
        @output_files = {}
        @package = @namespace.gsub('::', '.')
        @json_overrides_used = []
        @bytes_backed_string_fields_used = []

        # Skip XdrReader/XdrWriter generation - will be provided by KMP SDK
        # render_xdr_utils

        # Generate primitive type extensions
        render_primitive_extensions

        # Generate all type definitions
        render_definitions(@top)

        verify_json_overrides_consumed
        verify_bytes_backed_string_fields_consumed
      end

      private

      def render_definitions(node)
        node.definitions.each { |defn| render_definition(defn) }
        node.namespaces.each { |ns| render_definitions(ns) }
      end

      def render_nested_definitions(defn)
        return unless defn.respond_to?(:nested_definitions)
        defn.nested_definitions.each { |nested| render_definition(nested) }
      end

      def render_definition(defn)
        render_nested_definitions(defn)

        case defn
        when AST::Definitions::Struct
          render_struct(defn)
        when AST::Definitions::Enum
          render_enum(defn)
        when AST::Definitions::Union
          render_union(defn)
        when AST::Definitions::Typedef
          render_typedef(defn)
        when AST::Definitions::Const
          render_const(defn)
        end
      end

      def render_const(const)
        # Render constants as top-level const vals
        file_name = 'Constants.kt'

        # Initialize constants file if not exists
        unless @output_files&.key?(file_name)
          @output_files ||= {}
          out = @output.open(file_name)
          out.puts "// Automatically generated by xdrgen"
          out.puts "// DO NOT EDIT or your changes may be overwritten"
          out.puts
          out.puts "package #{@package}"
          out.puts
          @output_files[file_name] = out
        end

        out = @output_files[file_name]
        out.puts "const val #{const.name}: Int = #{const.value}"
      end

      def render_enum(enum)
        enum_name = name(enum)
        file_name = "#{enum_name}.kt"
        out = @output.open(file_name)

        render_file_header(out, [JSON_ELEMENT_IMPORT], enum_name)
        render_source_comment(out, enum)

        identifiers = enum.members.map(&:name)

        out.puts "enum class #{enum_name}(val value: Int, internal val xdrJsonName: String) {"
        out.indent do
          enum.members.each_with_index do |member, idx|
            # Extract and render comments for this member
            comments = extract_member_comment(enum.text_value, member.name)
            render_member_comment(out, comments)

            suffix = idx < enum.members.length - 1 ? ',' : ';'
            json_name = JSON_NAMES.enum_member_json_name(member.name, identifiers)
            out.puts "#{member.name}(#{member.value}, \"#{json_name}\")#{suffix}"
          end

          out.puts
          out.puts "companion object {"
          out.indent do
            out.puts ""
            out.puts "fun decode(reader: XdrReader): #{enum_name} {"
            out.indent do
              out.puts "val value = reader.readInt()"
              out.puts "return entries.find { it.value == value }"
              out.indent do
                out.puts "?: throw IllegalArgumentException(\"Unknown #{enum_name} value: \$value\")"
              end
            end
            out.puts "}"

            out.puts
            render_json_entry_points(out, enum_name)
            out.puts "internal fun fromXdrJsonTree(element: JsonElement): #{enum_name} {"
            out.indent do
              out.puts "val name = XdrJson.name(element, #{JSON_TYPE_CONSTANT})"
              out.puts "return findXdrJsonName(name) ?: XdrJson.unknownMember(#{JSON_TYPE_CONSTANT}, name)"
            end
            out.puts "}"

            out.puts
            out.puts "internal fun findXdrJsonName(name: String): #{enum_name}? = entries.find { it.xdrJsonName == name }"
          end
          out.puts "}"

          out.puts
          out.puts "fun encode(writer: XdrWriter) {"
          out.indent do
            out.puts "writer.writeInt(value)"
          end
          out.puts "}"

          out.puts
          out.puts "fun toXdrJsonElement(): JsonElement = XdrJson.name(xdrJsonName)"
          out.puts
          out.puts "fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())"
        end
        out.puts "}"

        out.close
      end

      def render_typedef(typedef)
        typedef_name = name(typedef)
        file_name = "#{typedef_name}.kt"
        out = @output.open(file_name)

        override = json_override(typedef_name)
        render_file_header(out, json_imports(override, [JSON_ELEMENT_IMPORT]), typedef_name)
        render_source_comment(out, typedef)

        # All typedefs become inline value classes (like Java wrappers but zero-cost)
        kotlin_type = kotlin_type_for(typedef.declaration)

        out.puts "@Suppress(\"EXPECT_ACTUAL_INCOMPATIBILITY\")"
        out.puts "@kotlin.jvm.JvmInline"
        out.puts "value class #{typedef_name}(val value: #{kotlin_type}) {"
        out.indent do
          out.puts "companion object {"
          out.indent do
            out.puts "fun decode(reader: XdrReader): #{typedef_name} {"
            out.indent do
              out.puts "val value = #{decode_expression(typedef.declaration, 'reader')}"
              out.puts "return #{typedef_name}(value)"
            end
            out.puts "}"

            out.puts
            render_json_entry_points(out, typedef_name)
            if override
              out.puts override[:from]
            else
              from = json_from_expression(typedef.declaration, 'element', 'value')
              out.puts "internal fun fromXdrJsonTree(element: JsonElement): #{typedef_name} = #{typedef_name}(#{from})"
            end
          end
          out.puts "}"

          out.puts
          out.puts "fun encode(writer: XdrWriter) {"
          out.indent do
            encode_statement(typedef.declaration, 'value', 'writer', out)
          end
          out.puts "}"

          out.puts
          if override
            out.puts override[:to]
          else
            out.puts "fun toXdrJsonElement(): JsonElement = #{json_to_expression(typedef.declaration, 'value')}"
          end
          out.puts
          out.puts "fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())"
        end
        out.puts "}"

        out.close
      end

      def render_struct(struct)
        struct_name = name(struct)
        file_name = "#{struct_name}.kt"
        out = @output.open(file_name)

        override = json_override(struct_name)
        default_imports = override ? [JSON_ELEMENT_IMPORT] : [JSON_ELEMENT_IMPORT, JSON_BUILDER_IMPORT]
        render_file_header(out, json_imports(override, default_imports), struct_name)
        render_declared_json_keys(out, struct) unless override
        render_source_comment(out, struct)

        out.puts "data class #{struct_name}("
        out.indent do
          struct.members.each_with_index do |member, idx|
            # Extract and render comments for this field
            comments = extract_member_comment(struct.text_value, member.name)
            render_member_comment(out, comments)

            member_name = escape_kotlin_keyword(member.name.underscore.camelize(:lower))
            member_type = member_kotlin_type(struct, member)
            suffix = idx < struct.members.length - 1 ? ',' : ''
            out.puts "val #{member_name}: #{member_type}#{suffix}"
          end
        end
        out.puts ") {"
        out.indent do
          # Companion object with decode method
          out.puts "companion object {"
          out.indent do
            out.puts ""
            out.puts "fun decode(reader: XdrReader): #{struct_name} {"
            out.indent do
              struct.members.each do |member|
                local_name = escape_kotlin_keyword(member.name.underscore.camelize(:lower))
                out.puts "val #{local_name} = #{member_decode_expression(struct, member, 'reader', struct_name: struct_name)}"
              end

              param_list = struct.members.map { |m|
                escape_kotlin_keyword(m.name.underscore.camelize(:lower))
              }.join(', ')
              out.puts "return #{struct_name}(#{param_list})"
            end
            out.puts "}"

            out.puts
            render_json_entry_points(out, struct_name)
            if override
              out.puts override[:from]
            else
              render_struct_from_json(out, struct, struct_name)
            end
          end
          out.puts "}"

          # Encode method
          out.puts
          out.puts "fun encode(writer: XdrWriter) {"
          out.indent do
            struct.members.each do |member|
              member_name = escape_kotlin_keyword(member.name.underscore.camelize(:lower))
              member_encode_statement(struct, member, member_name, 'writer', out)
            end
          end
          out.puts "}"

          out.puts
          if override
            out.puts override[:to]
          else
            out.puts "fun toXdrJsonElement(): JsonElement = buildJsonObject {"
            out.indent do
              struct.members.each do |member|
                member_name = escape_kotlin_keyword(member.name.underscore.camelize(:lower))
                key = JSON_NAMES.struct_field_json_name(member.name)
                out.puts "put(\"#{key}\", #{member_json_to_expression(struct, member, member_name)})"
              end
            end
            out.puts "}"
          end
          out.puts
          out.puts "fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())"
        end
        out.puts "}"

        out.close
      end

      # Reads the object one key at a time and constructs positionally, so the JSON key order
      # and the constructor order are both the .x declaration order by construction.
      def render_struct_from_json(out, struct, struct_name)
        out.puts "internal fun fromXdrJsonTree(element: JsonElement): #{struct_name} {"
        out.indent do
          out.puts "val json = XdrJson.obj(element, #{JSON_TYPE_CONSTANT}, #{JSON_KEYS_CONSTANT})"
          out.puts "return #{struct_name}("
          out.indent do
            struct.members.each_with_index do |member, idx|
              key = JSON_NAMES.struct_field_json_name(member.name)
              field = json_field_expression(key)
              suffix = idx < struct.members.length - 1 ? ',' : ''
              out.puts "#{member_json_from_expression(struct, member, field, key)}#{suffix}"
            end
          end
          out.puts ")"
        end
        out.puts "}"
      end

      def json_field_expression(key)
        alias_key = JSON_KEY_ALIASES[key]
        if alias_key
          "XdrJson.field(json, \"#{key}\", \"#{alias_key}\", #{JSON_TYPE_CONSTANT})"
        else
          "XdrJson.field(json, \"#{key}\", #{JSON_TYPE_CONSTANT})"
        end
      end

      # Every key a struct answers to: its declared field keys, plus the historical spelling of
      # any field that accepts one. Listing both spellings lets the decoder recognise either as
      # the field it names; a document supplying both at once is rejected where the field is
      # read, which is what knows the two are one field.
      def render_declared_json_keys(out, struct)
        keys = struct.members.flat_map do |member|
          key = JSON_NAMES.struct_field_json_name(member.name)
          [key, JSON_KEY_ALIASES[key]].compact
        end
        literals = keys.map { |key| "\"#{key}\"" }.join(', ')
        out.puts "private val #{JSON_KEYS_CONSTANT}: Array<String> = arrayOf(#{literals})"
        out.puts
      end

      def render_union(union)
        union_name = name(union)
        file_name = "#{union_name}.kt"
        out = @output.open(file_name)

        override = json_override(union_name)
        render_file_header(out, json_imports(override, union_json_imports(union, override)), union_name)
        render_source_comment(out, union)

        # Sealed class hierarchy for unions
        # union.discriminant is the full declaration (has .type), union.discriminant_type is the resolved type
        discriminant_type = kotlin_type_for(union.discriminant)
        out.puts "sealed class #{union_name} {"
        out.indent do
          out.puts "abstract val discriminant: #{discriminant_type}"
          out.puts

          # Generate a subclass for each arm
          union.arms.each do |arm|
            next if arm.void?

            # Extract and render comments for this arm
            comments = extract_union_arm_comment(union.text_value, arm)
            render_member_comment(out, comments)

            arm_class_name = arm.name.camelize
            arm_type = member_kotlin_type(union, arm)
            is_default = arm.is_a?(AST::Definitions::UnionDefaultArm)

            if is_default || arm.cases.length > 1
              # Default arms and multi-case arms both need discriminant as a
              # constructor parameter so the wire-read value survives a
              # decode/encode round trip. Hardcoding here would lose the
              # discriminant for any case beyond the first.
              out.puts "data class #{arm_class_name}("
              out.indent do
                out.puts "override val discriminant: #{discriminant_type},"
                out.puts "val value: #{arm_type}"
              end
              out.puts ") : #{union_name}()"
            else
              out.puts "data class #{arm_class_name}("
              out.indent do
                out.puts "val value: #{arm_type}"
              end
              out.puts ") : #{union_name}() {"
              out.indent do
                # Discriminant value
                discriminant_value = arm_discriminant_value(arm, union.discriminant)
                out.puts "override val discriminant: #{discriminant_type} = #{discriminant_value}"
              end
              out.puts "}"
            end
            out.puts
          end

          # Void arms - handle arms with multiple discriminant values
          void_arms_by_class = union.arms.select(&:void?).group_by { |arm| arm.name.camelize }
          void_arms_by_class.each do |arm_class_name, arms|
            # For void arms, if an arm has multiple cases, we need a data class that accepts discriminant
            # Otherwise, we can use a data object with a fixed discriminant

            # Count total discriminant values across all arms with this class name
            total_discriminants = arms.sum { |arm| arm.cases.length }

            # Extract and render comments for the first arm (they're grouped by name)
            comments = extract_union_arm_comment(union.text_value, arms.first)
            render_member_comment(out, comments)

            is_default = arms.first.is_a?(AST::Definitions::UnionDefaultArm)

            if is_default || total_discriminants > 1
              # Default arms and multi-case void arms both need discriminant
              # as a constructor parameter — the wire-read value must survive
              # decode/encode.
              out.puts "data class #{arm_class_name}("
              out.indent do
                out.puts "override val discriminant: #{discriminant_type}"
              end
              out.puts ") : #{union_name}()"
            else
              # Single discriminant value - use data object with fixed discriminant
              discriminant_value = format_discriminant_value(arms.first.cases.first, union)
              out.puts "data object #{arm_class_name} : #{union_name}() {"
              out.indent do
                out.puts "override val discriminant: #{discriminant_type} = #{discriminant_value}"
              end
              out.puts "}"
            end
            out.puts
          end

          # Companion object with decode
          out.puts "companion object {"
          out.indent do
            out.puts ""
            out.puts "fun decode(reader: XdrReader): #{union_name} {"
            out.indent do
              out.puts "val discriminant = #{decode_expression(union.discriminant, 'reader')}"
              out.puts "return when (discriminant) {"
              out.indent do
                # Build a map to detect void arms with multiple discriminants.
                # `union.normal_arms` excludes the default arm — that case is
                # rendered separately below in the `union.default_arm.present?`
                # block. The class-definition predicate at the top of this method
                # uses `is_default || ...`; the predicate here intentionally does
                # not need the `is_default` check because the default arm never
                # reaches this loop.
                void_arms_by_class = {}
                union.normal_arms.select(&:void?).each do |arm|
                  class_name = arm.name.camelize
                  void_arms_by_class[class_name] ||= []
                  void_arms_by_class[class_name] << arm
                end

                union.normal_arms.each do |arm|
                  arm_class_name = arm.name.camelize

                  # For void arms, check if this class has multiple discriminants
                  has_multiple_discriminants = if arm.void?
                    arm_list = void_arms_by_class[arm_class_name]
                    # Count total cases across all arms with this name
                    total_cases = arm_list.sum { |a| a.cases.length }
                    total_cases > 1
                  else
                    false
                  end

                  arm.cases.each do |c|
                    discriminant_value = format_discriminant_value(c, union)

                    if arm.void?
                      if has_multiple_discriminants
                        # Multiple discriminants for same class - need to pass discriminant
                        out.puts "#{discriminant_value} -> #{arm_class_name}(discriminant)"
                      else
                        # Single discriminant - use data object
                        out.puts "#{discriminant_value} -> #{arm_class_name}"
                      end
                    else
                      out.puts "#{discriminant_value} -> {"
                      out.indent do
                        out.puts "val value = #{member_decode_expression(union, arm, 'reader')}"
                        if arm.cases.length > 1
                          out.puts "#{arm_class_name}(discriminant, value)"
                        else
                          out.puts "#{arm_class_name}(value)"
                        end
                      end
                      out.puts "}"
                    end
                  end
                end

                # Handle default arm if present
                if union.default_arm.present?
                  arm = union.default_arm
                  arm_class_name = arm.name.camelize
                  out.puts "else -> {"
                  out.indent do
                    if arm.void?
                      out.puts "#{arm_class_name}(discriminant)"
                    else
                      out.puts "val value = #{member_decode_expression(union, arm, 'reader')}"
                      out.puts "#{arm_class_name}(discriminant, value)"
                    end
                  end
                  out.puts "}"
                else
                  out.puts "else -> throw IllegalArgumentException(\"Unknown #{union_name} discriminant: \$discriminant\")"
                end
              end
              out.puts "}"
            end
            out.puts "}"

            out.puts
            render_json_entry_points(out, union_name)
            if override
              out.puts override[:from]
            else
              render_union_from_json(out, union, union_name)
            end
          end
          out.puts "}"

          # Encode method
          out.puts
          out.puts "fun encode(writer: XdrWriter) {"
          out.indent do
            encode_statement(union.discriminant, 'discriminant', 'writer', out)
            out.puts "when (this) {"
            out.indent do
              # Group arms by class name to avoid duplicate 'is' checks
              arms_by_class = union.arms.group_by { |arm| arm.name.camelize }
              arms_by_class.each do |class_name, _|
                arm = union.arms.find { |a| a.name.camelize == class_name }
                if arm.void?
                  out.puts "is #{class_name} -> {}"
                else
                  out.puts "is #{class_name} -> {"
                  out.indent do
                    member_encode_statement(union, arm, 'value', 'writer', out)
                  end
                  out.puts "}"
                end
              end
            end
            out.puts "}"
          end
          out.puts "}"

          out.puts
          if override
            out.puts override[:to]
          else
            render_union_to_json(out, union)
          end
          out.puts
          out.puts "fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())"
        end
        out.puts "}"

        out.close
      end

      # A void arm is a bare string naming the arm; an arm carrying a value is an object with
      # that one key. An arm class covering more than one case, or the default arm, reads its
      # key from the discriminant it carries rather than from a name fixed here.
      def render_union_to_json(out, union)
        out.puts "fun toXdrJsonElement(): JsonElement = when (this) {"
        out.indent do
          union_json_classes(union).each do |entry|
            key = entry[:dynamic] ? union_json_dynamic_key(union) : "\"#{entry[:key]}\""
            if entry[:void]
              out.puts "is #{entry[:name]} -> XdrJson.name(#{key})"
            else
              arm = union.arms.find { |a| a.name.camelize == entry[:name] }
              value = member_json_to_expression(union, arm, 'value')
              out.puts "is #{entry[:name]} -> buildJsonObject { put(#{key}, #{value}) }"
            end
          end
        end
        out.puts "}"
      end

      def render_union_from_json(out, union, union_name)
        default = union_default_arm(union)
        value_arms = union.normal_arms.reject(&:void?)
        void_arms = union.normal_arms.select(&:void?)
        value_branch = value_arms.any? || (default && !default.void?)
        void_branch = void_arms.any? || (default && default.void?)
        both = value_branch && void_branch

        out.puts "internal fun fromXdrJsonTree(element: JsonElement): #{union_name} {"
        out.indent do
          if value_branch
            out.puts "if (element is JsonObject) {" if both
            out.indent(both ? 1 : 0) do
              out.puts "val (arm, value) = XdrJson.singleKeyObject(element, #{JSON_TYPE_CONSTANT})"
              out.puts "return when (arm) {"
              out.indent do
                value_arms.each do |arm|
                  arm.cases.each { |kase| out.puts union_json_case(union, arm, kase) }
                end
                out.puts union_json_default(union, default, union_name, value: true)
              end
              out.puts "}"
            end
            out.puts "}" if both
          end

          if void_branch
            out.puts "return when (val arm = XdrJson.name(element, #{JSON_TYPE_CONSTANT})) {"
            out.indent do
              void_arms.each do |arm|
                arm.cases.each { |kase| out.puts union_json_case(union, arm, kase) }
              end
              out.puts union_json_default(union, default, union_name, value: false)
            end
            out.puts "}"
          end
        end
        out.puts "}"
      end

      def union_default_arm(union)
        union.default_arm.present? ? union.default_arm : nil
      end

      def union_json_case(union, arm, kase)
        key = JSON_NAMES.union_arm_json_key(kase, union)
        class_name = arm.name.camelize
        discriminant = format_discriminant_value(kase, union)
        arguments = []
        arguments << discriminant if union_json_dynamic_arm?(union, arm)
        arguments << member_json_from_expression(union, arm, 'value', key) unless arm.void?

        if arguments.empty?
          "\"#{key}\" -> #{class_name}"
        else
          "\"#{key}\" -> #{class_name}(#{arguments.join(', ')})"
        end
      end

      # Without a default arm an unrecognised key is an error. With one, the key still has to
      # name a discriminant the union can carry: an enum member outside the explicit cases, or
      # the "v<n>" spelling of an integer discriminant.
      def union_json_default(union, default, union_name, value:)
        return "else -> XdrJson.unknownArm(#{JSON_TYPE_CONSTANT}, arm)" if default.nil?
        return "else -> XdrJson.unknownArm(#{JSON_TYPE_CONSTANT}, arm)" if default.void? != !value

        class_name = default.name.camelize
        arguments = [union_json_discriminant_from_key(union, union_name)]
        arguments << member_json_from_expression(union, default, 'value', 'default') unless default.void?
        "else -> #{class_name}(#{arguments.join(', ')})"
      end

      def union_json_discriminant_from_key(union, union_name)
        if union.discriminant_type.is_a?(AST::Definitions::Enum)
          enum_name = name(union.discriminant_type)
          "#{enum_name}.findXdrJsonName(arm) ?: XdrJson.unknownArm(#{JSON_TYPE_CONSTANT}, arm)"
        else
          require_int_discriminant(union, union_name)
          "XdrJson.intArm(#{JSON_TYPE_CONSTANT}, arm)"
        end
      end

      # The key an arm class derives from the discriminant it carries at run time.
      def union_json_dynamic_key(union)
        return 'discriminant.xdrJsonName' if union.discriminant_type.is_a?(AST::Definitions::Enum)

        require_int_discriminant(union, name(union))
        '"v$discriminant"'
      end

      def require_int_discriminant(union, union_name)
        return if kotlin_type_for(union.discriminant) == 'Int'

        raise "#{union_name} switches on #{kotlin_type_for(union.discriminant)}; SEP-0051 keys the " \
              'arms of an integer-discriminated union from the case value, which this generator ' \
              'only derives for a plain Int discriminant'
      end

      # Mirrors the arm-class shapes render_union emits: a class covering more than one case,
      # and the default arm, carry the discriminant so the wire-read value survives a round trip.
      def union_json_dynamic_arm?(union, arm)
        return true if arm.is_a?(AST::Definitions::UnionDefaultArm)
        return arm.cases.length > 1 unless arm.void?

        class_name = arm.name.camelize
        union.arms.select { |a| a.void? && a.name.camelize == class_name }
             .sum { |a| a.is_a?(AST::Definitions::UnionDefaultArm) ? 1 : a.cases.length } > 1
      end

      def union_json_classes(union)
        classes = {}
        union.arms.each do |arm|
          class_name = arm.name.camelize
          entry = (classes[class_name] ||= { name: class_name, void: arm.void?, dynamic: false, key: nil })
          entry[:dynamic] = true if union_json_dynamic_arm?(union, arm)
          next if arm.is_a?(AST::Definitions::UnionDefaultArm)

          entry[:key] ||= JSON_NAMES.union_arm_json_key(arm.cases.first, union)
        end
        classes.values
      end

      def union_json_imports(union, override)
        return [JSON_ELEMENT_IMPORT] if override

        imports = [JSON_ELEMENT_IMPORT]
        default = union_default_arm(union)
        if union.normal_arms.any? { |arm| !arm.void? } || (default && !default.void?)
          imports << JSON_BUILDER_IMPORT
          imports << JSON_OBJECT_IMPORT if union.normal_arms.any?(&:void?) || (default && default.void?)
        end
        imports
      end

      # Helper method to format a discriminant value for use in when expressions
      def format_discriminant_value(case_stmt, union)
        if case_stmt.value.is_a?(AST::Identifier)
          # For enum discriminants, get the enum type name
          discriminant_type_name = name(union.discriminant_type)
          "#{discriminant_type_name}.#{case_stmt.value.name}"
        else
          # Numeric literal - need to wrap in value class if discriminant is a typedef
          literal_value = case_stmt.value.value
          discriminant_type_name = kotlin_type_for(union.discriminant)

          if discriminant_type_name.end_with?('Xdr')
            # Wrap in value class constructor
            # Resolve to underlying type to determine literal suffix
            resolved_type = resolve_typedef_declaration(union.discriminant)
            wrapped_value = case resolved_type.type
            when AST::Typespecs::UnsignedInt
              "#{literal_value}u"
            when AST::Typespecs::UnsignedHyper
              "#{literal_value}uL"
            else
              literal_value.to_s
            end
            "#{discriminant_type_name}(#{wrapped_value})"
          else
            literal_value.to_s
          end
        end
      end

      def render_primitive_extensions
        file_name = 'XdrPrimitiveExtensions.kt'
        out = @output.open(file_name)

        out.puts <<~KOTLIN
          // Automatically generated by xdrgen
          // Extension functions for primitive types used in XDR

          package #{@package}

          // Extension functions for encoding primitive types
          fun Int.encode(writer: XdrWriter) = writer.writeInt(this)
          fun UInt.encode(writer: XdrWriter) = writer.writeUnsignedInt(this)
          fun Long.encode(writer: XdrWriter) = writer.writeLong(this)
          fun ULong.encode(writer: XdrWriter) = writer.writeUnsignedLong(this)
          fun Float.encode(writer: XdrWriter) = writer.writeFloat(this)
          fun Double.encode(writer: XdrWriter) = writer.writeDouble(this)
          fun Boolean.encode(writer: XdrWriter) = writer.writeBoolean(this)
          fun String.encode(writer: XdrWriter) = writer.writeString(this)
        KOTLIN

        out.close
      end

      def render_xdr_utils
        file_name = 'XdrReader.kt'
        out = @output.open(file_name)

        out.puts <<~KOTLIN
          // Automatically generated by xdrgen
          // DO NOT EDIT or your changes may be overwritten

          package #{@package}

          import java.io.DataInputStream
          import java.io.InputStream
          import java.nio.charset.StandardCharsets

          /**
           * XDR reader for decoding XDR-encoded data.
           */
          class XdrReader(input: InputStream) {
              private val dataInput = DataInputStream(input)

              fun readInt(): Int = dataInput.readInt()

              fun readUnsignedInt(): UInt = dataInput.readInt().toUInt()

              fun readLong(): Long = dataInput.readLong()

              fun readUnsignedLong(): ULong = dataInput.readLong().toULong()

              fun readFloat(): Float = dataInput.readFloat()

              fun readDouble(): Double = dataInput.readDouble()

              fun readBoolean(): Boolean = dataInput.readInt() != 0

              fun readString(): String {
                  val length = dataInput.readInt()
                  if (length < 0) throw IllegalArgumentException("Negative string length: \$length")
                  val bytes = ByteArray(length)
                  dataInput.readFully(bytes)
                  readPadding(length)
                  return String(bytes, StandardCharsets.UTF_8)
              }

              fun readFixedOpaque(length: Int): ByteArray {
                  val bytes = ByteArray(length)
                  dataInput.readFully(bytes)
                  readPadding(length)
                  return bytes
              }

              fun readVariableOpaque(): ByteArray {
                  val length = dataInput.readInt()
                  if (length < 0) throw IllegalArgumentException("Negative opaque length: \$length")
                  return readFixedOpaque(length)
              }

              private fun readPadding(length: Int) {
                  val remainder = length % 4
                  if (remainder != 0) {
                      val padding = 4 - remainder
                      dataInput.skipBytes(padding)
                  }
              }
          }
        KOTLIN

        out.close

        # Generate XdrWriter
        file_name = 'XdrWriter.kt'
        out = @output.open(file_name)

        out.puts <<~KOTLIN
          // Automatically generated by xdrgen
          // DO NOT EDIT or your changes may be overwritten

          package #{@package}

          import java.io.DataOutputStream
          import java.io.OutputStream
          import java.nio.charset.StandardCharsets

          /**
           * XDR writer for encoding data to XDR format.
           */
          class XdrWriter(output: OutputStream) {
              private val dataOutput = DataOutputStream(output)

              fun writeInt(value: Int) {
                  dataOutput.writeInt(value)
              }

              fun writeUnsignedInt(value: UInt) {
                  dataOutput.writeInt(value.toInt())
              }

              fun writeLong(value: Long) {
                  dataOutput.writeLong(value)
              }

              fun writeUnsignedLong(value: ULong) {
                  dataOutput.writeLong(value.toLong())
              }

              fun writeFloat(value: Float) {
                  dataOutput.writeFloat(value)
              }

              fun writeDouble(value: Double) {
                  dataOutput.writeDouble(value)
              }

              fun writeBoolean(value: Boolean) {
                  dataOutput.writeInt(if (value) 1 else 0)
              }

              fun writeString(value: String) {
                  val bytes = value.toByteArray(StandardCharsets.UTF_8)
                  dataOutput.writeInt(bytes.size)
                  dataOutput.write(bytes)
                  writePadding(bytes.size)
              }

              fun writeFixedOpaque(value: ByteArray, expectedLength: Int? = null) {
                  expectedLength?.let {
                      require(value.size == it) {
                          "Expected fixed opaque length \$it, got \${value.size}"
                      }
                  }
                  dataOutput.write(value)
                  writePadding(value.size)
              }

              fun writeVariableOpaque(value: ByteArray) {
                  dataOutput.writeInt(value.size)
                  dataOutput.write(value)
                  writePadding(value.size)
              }

              private fun writePadding(length: Int) {
                  val remainder = length % 4
                  if (remainder != 0) {
                      val padding = 4 - remainder
                      repeat(padding) { dataOutput.writeByte(0) }
                  }
              }

              fun flush() {
                  dataOutput.flush()
              }
          }
        KOTLIN

        out.close
      end

      def render_file_header(out, imports = [], type_name = nil)
        out.puts "// Automatically generated by xdrgen"
        out.puts "// DO NOT EDIT or your changes may be overwritten"
        out.puts
        out.puts "package #{@package}"
        out.puts
        unless imports.empty?
          imports.uniq.sort.each { |import| out.puts "import #{import}" }
          out.puts
        end
        return if type_name.nil?

        out.puts "private const val #{JSON_TYPE_CONSTANT} = \"#{type_name}\""
        out.puts
      end

      # The two public decode entry points. Both funnel into fromXdrJsonTree, which every
      # nested type calls directly: the depth limit is applied once, at the outermost type,
      # because applying it per nested value would rewalk the tree at every level.
      def render_json_entry_points(out, type_name)
        out.puts "fun fromXdrJson(json: String): #{type_name} = fromXdrJsonTree(XdrJson.parse(json, #{JSON_TYPE_CONSTANT}))"
        out.puts
        out.puts "fun fromXdrJsonElement(element: JsonElement): #{type_name} = " \
                 "fromXdrJsonTree(XdrJson.checkDepth(element, #{JSON_TYPE_CONSTANT}))"
        out.puts
      end

      def json_override(type_name)
        override = JSON_OVERRIDES.for_type(type_name)
        @json_overrides_used << type_name if override
        override
      end

      def json_imports(override, default_imports)
        return default_imports unless override

        default_imports + override[:imports]
      end

      # A registered override that never matched a generated type is a stale entry: the type
      # was renamed or removed, and the Stellar-specific rendering it carries has silently
      # stopped being applied. Only a run over the full Stellar .x set can conclude that, so
      # the caller opts in; a run over a subset says nothing about the registry.
      def verify_json_overrides_consumed
        return unless @options[:verify_json_overrides]

        missing = JSON_OVERRIDES.type_names - @json_overrides_used
        return if missing.empty?

        raise "SEP-0051 overrides registered for types this run did not generate: #{missing.join(', ')}"
      end

      # The same stale-entry rule for BYTES_BACKED_STRING_FIELDS: an entry that matched no
      # generated position names a renamed or removed field, and the ByteArray emission it
      # carries has silently stopped being applied. Opt-in for the same reason as
      # verify_json_overrides_consumed: only a run over the full Stellar .x set can conclude
      # an entry is stale.
      def verify_bytes_backed_string_fields_consumed
        return unless @options[:verify_bytes_backed_fields]

        registered = BYTES_BACKED_STRING_FIELDS.flat_map do |type, fields|
          fields.map { |field| "#{type}.#{field}" }
        end
        missing = registered - @bytes_backed_string_fields_used
        return if missing.empty?

        raise "Bytes-backed string fields registered for positions this run did not generate: #{missing.join(', ')}"
      end

      # Whether BYTES_BACKED_STRING_FIELDS names this struct field or union arm. A listed
      # position that is not an XDR string is a table mistake and raises rather than
      # emitting ByteArray code for a type the reader and writer calls do not fit.
      def bytes_backed_string_field?(defn, member)
        fields = BYTES_BACKED_STRING_FIELDS[defn.name]
        return false unless fields&.include?(member.name)

        resolved = resolve_typedef_declaration(member.declaration)
        unless resolved.type.is_a?(AST::Typespecs::String)
          raise "BYTES_BACKED_STRING_FIELDS names #{defn.name}.#{member.name}, which is not an XDR string"
        end

        (@bytes_backed_string_fields_used ||= []) << "#{defn.name}.#{member.name}"
        true
      end

      # The five positions a struct field or union arm is rendered at, each answering with
      # the ByteArray emission when BYTES_BACKED_STRING_FIELDS names the member and with
      # the generic one otherwise. The binary form of a string and of variable opaque is
      # identical (length prefix, bytes, padding), and the JSON form goes through the same
      # SEP-0051 escape ladder either way, so only the Kotlin representation differs.

      def member_kotlin_type(defn, member)
        return 'ByteArray' if bytes_backed_string_field?(defn, member)

        kotlin_type_for(member.declaration)
      end

      def member_decode_expression(defn, member, reader_var, struct_name: nil)
        return "#{reader_var}.readVariableOpaque()" if bytes_backed_string_field?(defn, member)
        return decode_expression(member.declaration, reader_var) if struct_name.nil?

        decode_expression_guarded(struct_name, member.declaration, reader_var)
      end

      def member_encode_statement(defn, member, value_expr, writer_var, out)
        if bytes_backed_string_field?(defn, member)
          out.puts "#{writer_var}.writeVariableOpaque(#{value_expr})"
        else
          encode_statement(member.declaration, value_expr, writer_var, out)
        end
      end

      def member_json_to_expression(defn, member, value_expr)
        return "XdrJson.escapedString(#{value_expr})" if bytes_backed_string_field?(defn, member)

        json_to_expression(member.declaration, value_expr)
      end

      def member_json_from_expression(defn, member, element_expr, key)
        unless bytes_backed_string_field?(defn, member)
          return json_from_expression(member.declaration, element_expr, key)
        end

        size = resolve_typedef_declaration(member.declaration).type.size
        "XdrJson.unescapeStringBytes(#{element_expr}, #{JSON_TYPE_CONSTANT}, \"#{key}\"#{json_max_length(size)})"
      end

      # The JSON form of a value, as an expression yielding a JsonElement.
      def json_to_expression(decl, value_expr)
        case decl
        when AST::Declarations::Optional
          "XdrJson.optional(#{value_expr}) { #{json_to_typespec(decl.type, 'it')} }"
        when AST::Declarations::Array
          values = decl.fixed? ? "#{value_expr}.asList()" : value_expr
          "XdrJson.array(#{values}) { #{json_to_typespec(decl.type, 'it')} }"
        else
          json_to_typespec(decl.type, value_expr)
        end
      end

      def json_to_typespec(typespec, value_expr)
        case typespec
        when AST::Typespecs::Int
          "XdrJson.int32(#{value_expr})"
        when AST::Typespecs::UnsignedInt
          "XdrJson.uint32(#{value_expr})"
        when AST::Typespecs::Hyper
          "XdrJson.int64(#{value_expr})"
        when AST::Typespecs::UnsignedHyper
          "XdrJson.uint64(#{value_expr})"
        when AST::Typespecs::Float, AST::Typespecs::Double, AST::Typespecs::Quadruple
          raise_unsupported_json_typespec(typespec)
        when AST::Typespecs::Bool
          "XdrJson.bool(#{value_expr})"
        when AST::Typespecs::String
          "XdrJson.escapedString(#{value_expr})"
        when AST::Typespecs::Opaque
          "XdrJson.hex(#{value_expr})"
        else
          "#{value_expr}.toXdrJsonElement()"
        end
      end

      # The Kotlin value read out of a JSON element, as an expression. Declared lengths and
      # maxima are checked here so a decoded instance is one the binary encoder also accepts.
      def json_from_expression(decl, element_expr, key)
        case decl
        when AST::Declarations::Optional
          inner = json_from_typespec(decl.type, 'it', key)
          "XdrJson.optional(#{element_expr})?.let { #{inner} }"
        when AST::Declarations::Array
          inner = json_from_typespec(decl.type, 'it', key)
          if decl.fixed?
            "XdrJson.array(#{element_expr}, #{JSON_TYPE_CONSTANT}, \"#{key}\", expectedLength = #{decl.size})" \
              ".map { #{inner} }.toTypedArray()"
          else
            "XdrJson.array(#{element_expr}, #{JSON_TYPE_CONSTANT}, \"#{key}\"#{json_max_length(decl.size)})" \
              ".map { #{inner} }"
          end
        else
          json_from_typespec(decl.type, element_expr, key)
        end
      end

      def json_from_typespec(typespec, element_expr, key)
        arguments = "#{element_expr}, #{JSON_TYPE_CONSTANT}, \"#{key}\""
        case typespec
        when AST::Typespecs::Int
          "XdrJson.int32(#{arguments})"
        when AST::Typespecs::UnsignedInt
          "XdrJson.uint32(#{arguments})"
        when AST::Typespecs::Hyper
          "XdrJson.int64(#{arguments})"
        when AST::Typespecs::UnsignedHyper
          "XdrJson.uint64(#{arguments})"
        when AST::Typespecs::Float, AST::Typespecs::Double, AST::Typespecs::Quadruple
          raise_unsupported_json_typespec(typespec)
        when AST::Typespecs::Bool
          "XdrJson.bool(#{arguments})"
        when AST::Typespecs::String
          "XdrJson.unescapeString(#{arguments}#{json_max_length(typespec.size)})"
        when AST::Typespecs::Opaque
          if typespec.fixed?
            "XdrJson.hex(#{arguments}, expectedLength = #{typespec.size})"
          else
            "XdrJson.hex(#{arguments}#{json_max_length(typespec.size)})"
          end
        when AST::Typespecs::Simple
          "#{name(typespec.resolved_type)}.fromXdrJsonTree(#{element_expr})"
        else
          "#{name(typespec)}.fromXdrJsonTree(#{element_expr})"
        end
      end

      def json_max_length(size)
        size.blank? ? '' : ", maxLength = #{size}"
      end

      def raise_unsupported_json_typespec(typespec)
        kind = typespec.class.name.split('::').last.downcase
        raise "SEP-0051 defines no JSON form for XDR #{kind}, which the Stellar .x files do not use"
      end

      def render_source_comment(out, defn)
        return if defn.is_a?(AST::Definitions::Namespace)

        out.puts "/**"
        out.puts " * XDR Source:"
        defn.text_value.each_line do |line|
          out.puts " * #{line.rstrip}"
        end
        out.puts " */"
      end

      # Extract comments for a specific member from the source text
      # Returns array of comment lines (without // prefix) that precede the member
      def extract_member_comment(source_text, member_name)
        lines = source_text.split("\n")
        comments = []

        lines.each_with_index do |line, idx|
          # Check if this line contains the member declaration
          if line =~ /^\s*\S+\s+#{Regexp.escape(member_name)}\s*[=,;]/ || line =~ /^\s*#{Regexp.escape(member_name)}\s*[=,;]/
            # Check for inline comment on the same line
            if line =~ /\/\/(.*)$/
              comments << $1.strip
            end

            # Look backwards for preceding comments
            i = idx - 1
            while i >= 0
              prev_line = lines[i].strip
              # Stop if we hit a non-comment, non-blank line
              break if !prev_line.empty? && !prev_line.start_with?('//')
              # Collect comment lines
              if prev_line.start_with?('//')
                comment_text = prev_line.sub(/^\/\/\s*/, '')
                comments.unshift(comment_text)
              end
              i -= 1
            end
            break
          end
        end

        comments
      end

      # Extract comments for a union arm from the source text
      # Union arms have format: case DISCRIMINANT_VALUE: // comment
      # Returns array of comment lines
      def extract_union_arm_comment(source_text, arm)
        comments = []

        # Try to get case values from the arm
        return [] unless arm.respond_to?(:cases)

        arm.cases.each do |case_stmt|
          # Get the case text which includes inline comments
          case_text = case_stmt.text_value rescue nil
          next unless case_text

          # Extract inline comment from case line
          if case_text =~ /\/\/(.*)$/
            comment_text = $1.strip
            comments << comment_text unless comment_text.empty?
          end
        end

        # If no inline comments, check for preceding comments
        if comments.empty? && arm.cases.first
          first_case = arm.cases.first
          lines = source_text.split("\n")

          # Find the case line
          lines.each_with_index do |line, idx|
            # Simple heuristic: match the start of the case text
            case_start = first_case.text_value.split("\n").first.strip rescue nil
            if case_start && line.include?(case_start)
              # Look backwards for comments
              i = idx - 1
              while i >= 0
                prev_line = lines[i].strip
                break if !prev_line.empty? && !prev_line.start_with?('//')
                if prev_line.start_with?('//')
                  comment_text = prev_line.sub(/^\/\/\s*/, '')
                  comments.unshift(comment_text)
                end
                i -= 1
              end
              break
            end
          end
        end

        comments
      end

      # Render KDoc comment for a member (enum value, struct field, etc.)
      def render_member_comment(out, comments)
        return if comments.empty?

        if comments.length == 1
          out.puts "/** #{comments.first} */"
        else
          out.puts "/**"
          comments.each { |line| out.puts " * #{line}" }
          out.puts " */"
        end
      end

      def kotlin_type_for(decl)
        case decl
        when AST::Declarations::Void
          'Unit'
        when AST::Declarations::Optional
          "#{kotlin_type_for_typespec(decl.type)}?"
        when AST::Declarations::Array
          if decl.fixed?
            # Fixed arrays could be Array<T> or ByteArray for bytes
            inner_type = kotlin_type_for_typespec(decl.type)
            inner_type == 'Byte' ? 'ByteArray' : "Array<#{inner_type}>"
          else
            # Variable arrays become List
            inner_type = kotlin_type_for_typespec(decl.type)
            inner_type == 'Byte' ? 'ByteArray' : "List<#{inner_type}>"
          end
        else
          kotlin_type_for_typespec(decl.type)
        end
      end

      def kotlin_type_for_typespec(typespec)
        case typespec
        when AST::Typespecs::Int
          'Int'
        when AST::Typespecs::UnsignedInt
          'UInt'
        when AST::Typespecs::Hyper
          'Long'
        when AST::Typespecs::UnsignedHyper
          'ULong'
        when AST::Typespecs::Float
          'Float'
        when AST::Typespecs::Double
          'Double'
        when AST::Typespecs::Quadruple
          raise "Quadruple not supported in Kotlin"
        when AST::Typespecs::Bool
          'Boolean'
        when AST::Typespecs::String
          'String'
        when AST::Typespecs::Opaque
          'ByteArray'
        when AST::Typespecs::Simple
          name(typespec.resolved_type)
        else
          name(typespec)
        end
      end

      # Like decode_expression but wraps variable-array element decodes with depth-guard
      # calls when the containing struct is in RECURSIVE_TYPES and the element type
      # resolves to the same struct (self-referential recursion).
      def decode_expression_guarded(struct_name, decl, reader_var)
        if RECURSIVE_TYPES.include?(struct_name) &&
           decl.is_a?(AST::Declarations::Array) &&
           !decl.fixed? &&
           kotlin_type_for_typespec(decl.type) == struct_name
          inner_decode = decode_expression_for_typespec(decl.type, reader_var)
          "List(#{reader_var}.readInt()) { " \
            "#{reader_var}.enterRecursion(#{XDR_RECURSION_CAP}); " \
            "try { #{inner_decode} } finally { #{reader_var}.exitRecursion() } }"
        else
          decode_expression(decl, reader_var)
        end
      end

      def decode_expression(decl, reader_var)
        case decl
        when AST::Declarations::Void
          # void
          ''
        when AST::Declarations::Optional
          inner_decode = decode_expression_for_typespec(decl.type, reader_var)
          "if (#{reader_var}.readBoolean()) #{inner_decode} else null"
        when AST::Declarations::Array
          if decl.fixed?
            _, size = decl.type.array_size
            inner_decode = decode_expression_for_typespec(decl.type, reader_var)

            if kotlin_type_for_typespec(decl.type) == 'Byte'
              "#{reader_var}.readFixedOpaque(#{size})"
            else
              "Array(#{size}) { #{inner_decode} }"
            end
          else
            inner_decode = decode_expression_for_typespec(decl.type, reader_var)

            if kotlin_type_for_typespec(decl.type) == 'Byte'
              "#{reader_var}.readVariableOpaque()"
            else
              "List(#{reader_var}.readInt()) { #{inner_decode} }"
            end
          end
        else
          decode_expression_for_typespec(decl.type, reader_var)
        end
      end

      def decode_expression_for_typespec(typespec, reader_var)
        case typespec
        when AST::Typespecs::Int
          "#{reader_var}.readInt()"
        when AST::Typespecs::UnsignedInt
          "#{reader_var}.readUnsignedInt()"
        when AST::Typespecs::Hyper
          "#{reader_var}.readLong()"
        when AST::Typespecs::UnsignedHyper
          "#{reader_var}.readUnsignedLong()"
        when AST::Typespecs::Float
          "#{reader_var}.readFloat()"
        when AST::Typespecs::Double
          "#{reader_var}.readDouble()"
        when AST::Typespecs::Bool
          "#{reader_var}.readBoolean()"
        when AST::Typespecs::String
          "#{reader_var}.readString()"
        when AST::Typespecs::Opaque
          if typespec.fixed?
            "#{reader_var}.readFixedOpaque(#{typespec.size})"
          else
            "#{reader_var}.readVariableOpaque()"
          end
        when AST::Typespecs::Simple
          type_name = name(typespec.resolved_type)
          "#{type_name}.decode(#{reader_var})"
        else
          type_name = name(typespec)
          "#{type_name}.decode(#{reader_var})"
        end
      end

      def encode_statement(decl, value_expr, writer_var, out)
        case decl
        when AST::Declarations::Void
          # Nothing to encode
        when AST::Declarations::Optional
          out.puts "if (#{value_expr} != null) {"
          out.indent do
            out.puts "#{writer_var}.writeBoolean(true)"
            encode_statement_for_typespec(decl.type, value_expr, writer_var, out)
          end
          out.puts "} else {"
          out.indent do
            out.puts "#{writer_var}.writeBoolean(false)"
          end
          out.puts "}"
        when AST::Declarations::Array
          if decl.fixed?
            if kotlin_type_for_typespec(decl.type) == 'Byte'
              _, size = decl.type.array_size
              out.puts "#{writer_var}.writeFixedOpaque(#{value_expr}, #{size})"
            else
              out.puts "#{value_expr}.forEach { item ->"
              out.indent do
                encode_statement_for_typespec(decl.type, 'item', writer_var, out)
              end
              out.puts "}"
            end
          else
            if kotlin_type_for_typespec(decl.type) == 'Byte'
              out.puts "#{writer_var}.writeVariableOpaque(#{value_expr})"
            else
              out.puts "#{writer_var}.writeInt(#{value_expr}.size)"
              out.puts "#{value_expr}.forEach { item ->"
              out.indent do
                encode_statement_for_typespec(decl.type, 'item', writer_var, out)
              end
              out.puts "}"
            end
          end
        else
          encode_statement_for_typespec(decl.type, value_expr, writer_var, out)
        end
      end

      def encode_statement_for_typespec(typespec, value_expr, writer_var, out)
        case typespec
        when AST::Typespecs::Int
          out.puts "#{writer_var}.writeInt(#{value_expr})"
        when AST::Typespecs::UnsignedInt
          out.puts "#{writer_var}.writeUnsignedInt(#{value_expr})"
        when AST::Typespecs::Hyper
          out.puts "#{writer_var}.writeLong(#{value_expr})"
        when AST::Typespecs::UnsignedHyper
          out.puts "#{writer_var}.writeUnsignedLong(#{value_expr})"
        when AST::Typespecs::Float
          out.puts "#{writer_var}.writeFloat(#{value_expr})"
        when AST::Typespecs::Double
          out.puts "#{writer_var}.writeDouble(#{value_expr})"
        when AST::Typespecs::Bool
          out.puts "#{writer_var}.writeBoolean(#{value_expr})"
        when AST::Typespecs::String
          out.puts "#{writer_var}.writeString(#{value_expr})"
        when AST::Typespecs::Opaque
          if typespec.fixed?
            out.puts "#{writer_var}.writeFixedOpaque(#{value_expr}, #{typespec.size})"
          else
            out.puts "#{writer_var}.writeVariableOpaque(#{value_expr})"
          end
        when AST::Typespecs::Simple
          out.puts "#{value_expr}.encode(#{writer_var})"
        else
          out.puts "#{value_expr}.encode(#{writer_var})"
        end
      end

      def arm_discriminant_value(arm, discriminant)
        # Handle default arm separately
        return 'else' if arm.is_a?(AST::Definitions::UnionDefaultArm)

        # Get the first case value for this arm
        first_case = arm.cases.first
        return 'else' unless first_case

        # Create a simple struct for union context
        # discriminant is already a declaration, .type gives us the typespec
        disc_type = discriminant.type.respond_to?(:resolved_type) ? discriminant.type.resolved_type : discriminant.type
        union_context = Struct.new(:discriminant, :discriminant_type).new(discriminant, disc_type)
        format_discriminant_value(first_case, union_context)
      end

      def simple_typedef?(decl)
        # Simple typedefs can use typealias
        case decl
        when AST::Declarations::Array, AST::Declarations::Optional
          false
        when AST::Declarations::Simple
          true
        else
          case decl.type
          when AST::Typespecs::Simple
            false # Reference types need wrappers
          else
            true # Primitive types can use typealias
          end
        end
      end

      def name(named)
        # Build the complete name path without Xdr suffixes, then add Xdr once at the end
        base_name = build_base_name(named)
        "#{base_name}Xdr"
      end

      def build_base_name(named)
        parent = build_base_name(named.parent_defn) if named.is_a?(AST::Concerns::NestedDefinition)
        result = named.name.camelize
        "#{parent}#{result}"
      end

      def escape_kotlin_keyword(name)
        # Kotlin keywords that need to be escaped with backticks
        kotlin_keywords = %w[val var fun class object interface when is in as break continue return this super if else while do for try catch finally throw typeof true false null]

        if kotlin_keywords.include?(name)
          "`#{name}`"
        else
          name
        end
      end

      def resolve_typedef_declaration(decl)
        # Resolve a declaration to its underlying type (following typedef chains)
        return decl unless decl.is_a?(AST::Declarations::Simple)

        # If it's a reference to another type, resolve it
        if decl.type.is_a?(AST::Typespecs::Simple)
          resolved_def = @top.find_definition(decl.type.text_value)
          if resolved_def.is_a?(AST::Definitions::Typedef)
            # Recursively resolve the typedef's declaration
            resolve_typedef_declaration(resolved_def.declaration)
          else
            decl
          end
        else
          decl
        end
      end

      def get_or_create_file(file_name)
        @output_files[file_name] ||= begin
          out = @output.open(file_name)
          out.puts "// Automatically generated by xdrgen"
          out.puts "// DO NOT EDIT or your changes may be overwritten"
          out.puts
          out.puts "package #{@package}"
          out.puts
          out
        end
      end
    end
  end
end
