name: StellarDemo
options:
  bundleIdPrefix: com.soneso.demo
  deploymentTarget:
    iOS: 14.0
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  StellarDemo:
    type: application
    platform: iOS
    sources:
      - StellarDemo
    info:
      path: StellarDemo/Info.plist
      properties:
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(SRCROOT)/../../shared/build/bin/iosSimulatorArm64/debugFramework
        - $(SRCROOT)/../../shared/build/bin/iosArm64/debugFramework
      OTHER_LDFLAGS:
        - $(inherited)
        - -framework shared
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
        embed: true
    preBuildScripts:
      - script: |
          cd "$SRCROOT/../../.."
          ./gradlew :demo:shared:linkDebugFrameworkIosSimulatorArm64
        name: Build Kotlin Framework
        basedOnDependencyAnalysis: false
