// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         AccountEntryExtensionV1 v1;
 *     }
 */
sealed class AccountEntryExtXdr {
  abstract val discriminant: Int

  data class V1(
    val value: AccountEntryExtensionV1Xdr
  ) : AccountEntryExtXdr() {
    override val discriminant: Int = 1
  }

  data object Void : AccountEntryExtXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): AccountEntryExtXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> Void
        1 -> {
          val value = AccountEntryExtensionV1Xdr.decode(reader)
          V1(value)
        }
        else -> throw IllegalArgumentException("Unknown AccountEntryExtXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is Void -> {}
      is V1 -> {
        value.encode(writer)
      }
    }
  }
}
