// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct AccountEntryExtensionV1
 * {
 *     Liabilities liabilities;
 * 
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 2:
 *         AccountEntryExtensionV2 v2;
 *     }
 *     ext;
 * };
 */
data class AccountEntryExtensionV1Xdr(
  val liabilities: LiabilitiesXdr,
  val ext: AccountEntryExtensionV1ExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): AccountEntryExtensionV1Xdr {
      val liabilities = LiabilitiesXdr.decode(reader)
      val ext = AccountEntryExtensionV1ExtXdr.decode(reader)
      return AccountEntryExtensionV1Xdr(liabilities, ext)
    }
  }

  fun encode(writer: XdrWriter) {
    liabilities.encode(writer)
    ext.encode(writer)
  }
}
