// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "AccountEntryXdr"

/**
 * XDR Source:
 * struct AccountEntry
 * {
 *     AccountID accountID;      // master public key for this account
 *     int64 balance;            // in stroops
 *     SequenceNumber seqNum;    // last sequence number used for this account
 *     uint32 numSubEntries;     // number of sub-entries this account has
 *                               // drives the reserve
 *     AccountID* inflationDest; // Account to vote for during inflation
 *     uint32 flags;             // see AccountFlags
 * 
 *     string32 homeDomain; // can be used for reverse federation and memo lookup
 * 
 *     // fields used for signatures
 *     // thresholds stores unsigned bytes: [weight of master|low|medium|high]
 *     Thresholds thresholds;
 * 
 *     Signer signers<MAX_SIGNERS>; // possible signers for this account
 * 
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         AccountEntryExtensionV1 v1;
 *     }
 *     ext;
 * };
 */
data class AccountEntryXdr(
  /** master public key for this account */
  val accountId: AccountIDXdr,
  /** in stroops */
  val balance: Int64Xdr,
  /** last sequence number used for this account */
  val seqNum: SequenceNumberXdr,
  /** number of sub-entries this account has */
  val numSubEntries: Uint32Xdr,
  /**
   * drives the reserve
   * Account to vote for during inflation
   */
  val inflationDest: AccountIDXdr?,
  /** see AccountFlags */
  val flags: Uint32Xdr,
  /** can be used for reverse federation and memo lookup */
  val homeDomain: String32Xdr,
  /**
   * fields used for signatures
   * thresholds stores unsigned bytes: [weight of master|low|medium|high]
   */
  val thresholds: ThresholdsXdr,
  val signers: List<SignerXdr>,
  val ext: AccountEntryExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): AccountEntryXdr {
      val accountId = AccountIDXdr.decode(reader)
      val balance = Int64Xdr.decode(reader)
      val seqNum = SequenceNumberXdr.decode(reader)
      val numSubEntries = Uint32Xdr.decode(reader)
      val inflationDest = if (reader.readBoolean()) AccountIDXdr.decode(reader) else null
      val flags = Uint32Xdr.decode(reader)
      val homeDomain = String32Xdr.decode(reader)
      val thresholds = ThresholdsXdr.decode(reader)
      val signers = List(reader.readInt()) { SignerXdr.decode(reader) }
      val ext = AccountEntryExtXdr.decode(reader)
      return AccountEntryXdr(accountId, balance, seqNum, numSubEntries, inflationDest, flags, homeDomain, thresholds, signers, ext)
    }

    fun fromXdrJson(json: String): AccountEntryXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): AccountEntryXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): AccountEntryXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return AccountEntryXdr(
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "account_id", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "balance", XDR_JSON_TYPE)),
        SequenceNumberXdr.fromXdrJsonTree(XdrJson.field(json, "seq_num", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "num_sub_entries", XDR_JSON_TYPE)),
        XdrJson.optional(XdrJson.field(json, "inflation_dest", XDR_JSON_TYPE))?.let { AccountIDXdr.fromXdrJsonTree(it) },
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "flags", XDR_JSON_TYPE)),
        String32Xdr.fromXdrJsonTree(XdrJson.field(json, "home_domain", XDR_JSON_TYPE)),
        ThresholdsXdr.fromXdrJsonTree(XdrJson.field(json, "thresholds", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "signers", XDR_JSON_TYPE), XDR_JSON_TYPE, "signers", maxLength = MAX_SIGNERS).map { SignerXdr.fromXdrJsonTree(it) },
        AccountEntryExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    accountId.encode(writer)
    balance.encode(writer)
    seqNum.encode(writer)
    numSubEntries.encode(writer)
    if (inflationDest != null) {
      writer.writeBoolean(true)
      inflationDest.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
    flags.encode(writer)
    homeDomain.encode(writer)
    thresholds.encode(writer)
    writer.writeInt(signers.size)
    signers.forEach { item ->
      item.encode(writer)
    }
    ext.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("account_id", accountId.toXdrJsonElement())
    put("balance", balance.toXdrJsonElement())
    put("seq_num", seqNum.toXdrJsonElement())
    put("num_sub_entries", numSubEntries.toXdrJsonElement())
    put("inflation_dest", XdrJson.optional(inflationDest) { it.toXdrJsonElement() })
    put("flags", flags.toXdrJsonElement())
    put("home_domain", homeDomain.toXdrJsonElement())
    put("thresholds", thresholds.toXdrJsonElement())
    put("signers", XdrJson.array(signers) { it.toXdrJsonElement() })
    put("ext", ext.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
