// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "AccountEntryExtensionV2Xdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("num_sponsored", "num_sponsoring", "signer_sponsoring_i_ds", "ext")

/**
 * XDR Source:
 * struct AccountEntryExtensionV2
 * {
 *     uint32 numSponsored;
 *     uint32 numSponsoring;
 *     SponsorshipDescriptor signerSponsoringIDs<MAX_SIGNERS>;
 * 
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 3:
 *         AccountEntryExtensionV3 v3;
 *     }
 *     ext;
 * };
 */
data class AccountEntryExtensionV2Xdr(
  val numSponsored: Uint32Xdr,
  val numSponsoring: Uint32Xdr,
  val signerSponsoringIDs: List<SponsorshipDescriptorXdr>,
  val ext: AccountEntryExtensionV2ExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): AccountEntryExtensionV2Xdr {
      val numSponsored = Uint32Xdr.decode(reader)
      val numSponsoring = Uint32Xdr.decode(reader)
      val signerSponsoringIDs = List(reader.readInt()) { SponsorshipDescriptorXdr.decode(reader) }
      val ext = AccountEntryExtensionV2ExtXdr.decode(reader)
      return AccountEntryExtensionV2Xdr(numSponsored, numSponsoring, signerSponsoringIDs, ext)
    }

    fun fromXdrJson(json: String): AccountEntryExtensionV2Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): AccountEntryExtensionV2Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): AccountEntryExtensionV2Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return AccountEntryExtensionV2Xdr(
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "num_sponsored", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "num_sponsoring", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "signer_sponsoring_i_ds", XDR_JSON_TYPE), XDR_JSON_TYPE, "signer_sponsoring_i_ds", maxLength = MAX_SIGNERS).map { SponsorshipDescriptorXdr.fromXdrJsonTree(it) },
        AccountEntryExtensionV2ExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    numSponsored.encode(writer)
    numSponsoring.encode(writer)
    writer.writeInt(signerSponsoringIDs.size)
    signerSponsoringIDs.forEach { item ->
      item.encode(writer)
    }
    ext.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("num_sponsored", numSponsored.toXdrJsonElement())
    put("num_sponsoring", numSponsoring.toXdrJsonElement())
    put("signer_sponsoring_i_ds", XdrJson.array(signerSponsoringIDs) { it.toXdrJsonElement() })
    put("ext", ext.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
