// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "AccountEntryExtensionV3Xdr"

/**
 * XDR Source:
 * struct AccountEntryExtensionV3
 * {
 *     // We can use this to add more fields, or because it is first, to
 *     // change AccountEntryExtensionV3 into a union.
 *     ExtensionPoint ext;
 * 
 *     // Ledger number at which `seqNum` took on its present value.
 *     uint32 seqLedger;
 * 
 *     // Time at which `seqNum` took on its present value.
 *     TimePoint seqTime;
 * };
 */
data class AccountEntryExtensionV3Xdr(
  /**
   * We can use this to add more fields, or because it is first, to
   * change AccountEntryExtensionV3 into a union.
   */
  val ext: ExtensionPointXdr,
  /** Ledger number at which `seqNum` took on its present value. */
  val seqLedger: Uint32Xdr,
  /** Time at which `seqNum` took on its present value. */
  val seqTime: TimePointXdr
) {
  companion object {

    fun decode(reader: XdrReader): AccountEntryExtensionV3Xdr {
      val ext = ExtensionPointXdr.decode(reader)
      val seqLedger = Uint32Xdr.decode(reader)
      val seqTime = TimePointXdr.decode(reader)
      return AccountEntryExtensionV3Xdr(ext, seqLedger, seqTime)
    }

    fun fromXdrJson(json: String): AccountEntryExtensionV3Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): AccountEntryExtensionV3Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): AccountEntryExtensionV3Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return AccountEntryExtensionV3Xdr(
        ExtensionPointXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "seq_ledger", XDR_JSON_TYPE)),
        TimePointXdr.fromXdrJsonTree(XdrJson.field(json, "seq_time", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    seqLedger.encode(writer)
    seqTime.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("ext", ext.toXdrJsonElement())
    put("seq_ledger", seqLedger.toXdrJsonElement())
    put("seq_time", seqTime.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
