// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "AllowTrustOpXdr"

/**
 * XDR Source:
 * struct AllowTrustOp
 * {
 *     AccountID trustor;
 *     AssetCode asset;
 * 
 *     // One of 0, AUTHORIZED_FLAG, or AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG
 *     uint32 authorize;
 * };
 */
data class AllowTrustOpXdr(
  val trustor: AccountIDXdr,
  val asset: AssetCodeXdr,
  /** One of 0, AUTHORIZED_FLAG, or AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG */
  val authorize: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): AllowTrustOpXdr {
      val trustor = AccountIDXdr.decode(reader)
      val asset = AssetCodeXdr.decode(reader)
      val authorize = Uint32Xdr.decode(reader)
      return AllowTrustOpXdr(trustor, asset, authorize)
    }

    fun fromXdrJson(json: String): AllowTrustOpXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): AllowTrustOpXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): AllowTrustOpXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return AllowTrustOpXdr(
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "trustor", XDR_JSON_TYPE)),
        AssetCodeXdr.fromXdrJsonTree(XdrJson.field(json, "asset", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "authorize", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    trustor.encode(writer)
    asset.encode(writer)
    authorize.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("trustor", trustor.toXdrJsonElement())
    put("asset", asset.toXdrJsonElement())
    put("authorize", authorize.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
