// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "AlphaNum4Xdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("asset_code", "issuer")

/**
 * XDR Source:
 * struct AlphaNum4
 * {
 *     AssetCode4 assetCode;
 *     AccountID issuer;
 * };
 */
data class AlphaNum4Xdr(
  val assetCode: AssetCode4Xdr,
  val issuer: AccountIDXdr
) {
  companion object {

    fun decode(reader: XdrReader): AlphaNum4Xdr {
      val assetCode = AssetCode4Xdr.decode(reader)
      val issuer = AccountIDXdr.decode(reader)
      return AlphaNum4Xdr(assetCode, issuer)
    }

    fun fromXdrJson(json: String): AlphaNum4Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): AlphaNum4Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): AlphaNum4Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return AlphaNum4Xdr(
        AssetCode4Xdr.fromXdrJsonTree(XdrJson.field(json, "asset_code", XDR_JSON_TYPE)),
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "issuer", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    assetCode.encode(writer)
    issuer.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("asset_code", assetCode.toXdrJsonElement())
    put("issuer", issuer.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
