// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef opaque AssetCode4[4];
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class AssetCode4Xdr(val value: ByteArray) {
  companion object {
    fun decode(reader: XdrReader): AssetCode4Xdr {
      val value = reader.readFixedOpaque(4)
      return AssetCode4Xdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeFixedOpaque(value, 4)
  }
}
