// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "BeginSponsoringFutureReservesResultXdr"

/**
 * XDR Source:
 * union BeginSponsoringFutureReservesResult switch (
 *     BeginSponsoringFutureReservesResultCode code)
 * {
 * case BEGIN_SPONSORING_FUTURE_RESERVES_SUCCESS:
 *     void;
 * case BEGIN_SPONSORING_FUTURE_RESERVES_MALFORMED:
 * case BEGIN_SPONSORING_FUTURE_RESERVES_ALREADY_SPONSORED:
 * case BEGIN_SPONSORING_FUTURE_RESERVES_RECURSIVE:
 *     void;
 * };
 */
sealed class BeginSponsoringFutureReservesResultXdr {
  abstract val discriminant: BeginSponsoringFutureReservesResultCodeXdr

  data class Void(
    override val discriminant: BeginSponsoringFutureReservesResultCodeXdr
  ) : BeginSponsoringFutureReservesResultXdr()

  companion object {

    fun decode(reader: XdrReader): BeginSponsoringFutureReservesResultXdr {
      val discriminant = BeginSponsoringFutureReservesResultCodeXdr.decode(reader)
      return when (discriminant) {
        BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_SUCCESS -> Void(discriminant)
        BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_MALFORMED -> Void(discriminant)
        BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_ALREADY_SPONSORED -> Void(discriminant)
        BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_RECURSIVE -> Void(discriminant)
        else -> throw IllegalArgumentException("Unknown BeginSponsoringFutureReservesResultXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): BeginSponsoringFutureReservesResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): BeginSponsoringFutureReservesResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): BeginSponsoringFutureReservesResultXdr {
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "success" -> Void(BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_SUCCESS)
        "malformed" -> Void(BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_MALFORMED)
        "already_sponsored" -> Void(BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_ALREADY_SPONSORED)
        "recursive" -> Void(BeginSponsoringFutureReservesResultCodeXdr.BEGIN_SPONSORING_FUTURE_RESERVES_RECURSIVE)
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Void -> {}
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Void -> XdrJson.name(discriminant.xdrJsonName)
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
