// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct BucketMetadata
 * {
 *     // Indicates the protocol version used to create / merge this bucket.
 *     uint32 ledgerVersion;
 * 
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         BucketListType bucketListType;
 *     }
 *     ext;
 * };
 */
data class BucketMetadataXdr(
  /** Indicates the protocol version used to create / merge this bucket. */
  val ledgerVersion: Uint32Xdr,
  val ext: BucketMetadataExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): BucketMetadataXdr {
      val ledgerVersion = Uint32Xdr.decode(reader)
      val ext = BucketMetadataExtXdr.decode(reader)
      return BucketMetadataXdr(ledgerVersion, ext)
    }
  }

  fun encode(writer: XdrWriter) {
    ledgerVersion.encode(writer)
    ext.encode(writer)
  }
}
