// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ClaimOfferAtomXdr"

/**
 * XDR Source:
 * struct ClaimOfferAtom
 * {
 *     // emitted to identify the offer
 *     AccountID sellerID; // Account that owns the offer
 *     int64 offerID;
 * 
 *     // amount and asset taken from the owner
 *     Asset assetSold;
 *     int64 amountSold;
 * 
 *     // amount and asset sent to the owner
 *     Asset assetBought;
 *     int64 amountBought;
 * };
 */
data class ClaimOfferAtomXdr(
  /**
   * emitted to identify the offer
   * Account that owns the offer
   */
  val sellerId: AccountIDXdr,
  val offerId: Int64Xdr,
  /** amount and asset taken from the owner */
  val assetSold: AssetXdr,
  val amountSold: Int64Xdr,
  /** amount and asset sent to the owner */
  val assetBought: AssetXdr,
  val amountBought: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ClaimOfferAtomXdr {
      val sellerId = AccountIDXdr.decode(reader)
      val offerId = Int64Xdr.decode(reader)
      val assetSold = AssetXdr.decode(reader)
      val amountSold = Int64Xdr.decode(reader)
      val assetBought = AssetXdr.decode(reader)
      val amountBought = Int64Xdr.decode(reader)
      return ClaimOfferAtomXdr(sellerId, offerId, assetSold, amountSold, assetBought, amountBought)
    }

    fun fromXdrJson(json: String): ClaimOfferAtomXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ClaimOfferAtomXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ClaimOfferAtomXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return ClaimOfferAtomXdr(
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "seller_id", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "offer_id", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset_sold", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "amount_sold", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset_bought", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "amount_bought", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    sellerId.encode(writer)
    offerId.encode(writer)
    assetSold.encode(writer)
    amountSold.encode(writer)
    assetBought.encode(writer)
    amountBought.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("seller_id", sellerId.toXdrJsonElement())
    put("offer_id", offerId.toXdrJsonElement())
    put("asset_sold", assetSold.toXdrJsonElement())
    put("amount_sold", amountSold.toXdrJsonElement())
    put("asset_bought", assetBought.toXdrJsonElement())
    put("amount_bought", amountBought.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
