// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ClaimableBalanceEntryExtensionV1
 * {
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * 
 *     uint32 flags; // see ClaimableBalanceFlags
 * };
 */
data class ClaimableBalanceEntryExtensionV1Xdr(
  val ext: ClaimableBalanceEntryExtensionV1ExtXdr,
  /** see ClaimableBalanceFlags */
  val flags: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ClaimableBalanceEntryExtensionV1Xdr {
      val ext = ClaimableBalanceEntryExtensionV1ExtXdr.decode(reader)
      val flags = Uint32Xdr.decode(reader)
      return ClaimableBalanceEntryExtensionV1Xdr(ext, flags)
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    flags.encode(writer)
  }
}
