// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ClaimLiquidityAtom
 * {
 *     PoolID liquidityPoolID;
 * 
 *     // amount and asset taken from the pool
 *     Asset assetSold;
 *     int64 amountSold;
 * 
 *     // amount and asset sent to the pool
 *     Asset assetBought;
 *     int64 amountBought;
 * };
 */
data class ClaimLiquidityAtomXdr(
  val liquidityPoolId: PoolIDXdr,
  /** amount and asset taken from the pool */
  val assetSold: AssetXdr,
  val amountSold: Int64Xdr,
  /** amount and asset sent to the pool */
  val assetBought: AssetXdr,
  val amountBought: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ClaimLiquidityAtomXdr {
      val liquidityPoolId = PoolIDXdr.decode(reader)
      val assetSold = AssetXdr.decode(reader)
      val amountSold = Int64Xdr.decode(reader)
      val assetBought = AssetXdr.decode(reader)
      val amountBought = Int64Xdr.decode(reader)
      return ClaimLiquidityAtomXdr(liquidityPoolId, assetSold, amountSold, assetBought, amountBought)
    }
  }

  fun encode(writer: XdrWriter) {
    liquidityPoolId.encode(writer)
    assetSold.encode(writer)
    amountSold.encode(writer)
    assetBought.encode(writer)
    amountBought.encode(writer)
  }
}
