// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ConfigUpgradeSetKeyXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("contract_id", "content_hash")

/**
 * XDR Source:
 * struct ConfigUpgradeSetKey {
 *     ContractID contractID;
 *     Hash contentHash;
 * };
 */
data class ConfigUpgradeSetKeyXdr(
  val contractId: ContractIDXdr,
  val contentHash: HashXdr
) {
  companion object {

    fun decode(reader: XdrReader): ConfigUpgradeSetKeyXdr {
      val contractId = ContractIDXdr.decode(reader)
      val contentHash = HashXdr.decode(reader)
      return ConfigUpgradeSetKeyXdr(contractId, contentHash)
    }

    fun fromXdrJson(json: String): ConfigUpgradeSetKeyXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ConfigUpgradeSetKeyXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ConfigUpgradeSetKeyXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return ConfigUpgradeSetKeyXdr(
        ContractIDXdr.fromXdrJsonTree(XdrJson.field(json, "contract_id", XDR_JSON_TYPE)),
        HashXdr.fromXdrJsonTree(XdrJson.field(json, "content_hash", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    contractId.encode(writer)
    contentHash.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("contract_id", contractId.toXdrJsonElement())
    put("content_hash", contentHash.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
