// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ConfigSettingSCPTimingXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("ledger_target_close_time_milliseconds", "nomination_timeout_initial_milliseconds", "nomination_timeout_increment_milliseconds", "ballot_timeout_initial_milliseconds", "ballot_timeout_increment_milliseconds")

/**
 * XDR Source:
 * struct ConfigSettingSCPTiming {
 *     uint32 ledgerTargetCloseTimeMilliseconds;
 *     uint32 nominationTimeoutInitialMilliseconds;
 *     uint32 nominationTimeoutIncrementMilliseconds;
 *     uint32 ballotTimeoutInitialMilliseconds;
 *     uint32 ballotTimeoutIncrementMilliseconds;
 * };
 */
data class ConfigSettingSCPTimingXdr(
  val ledgerTargetCloseTimeMilliseconds: Uint32Xdr,
  val nominationTimeoutInitialMilliseconds: Uint32Xdr,
  val nominationTimeoutIncrementMilliseconds: Uint32Xdr,
  val ballotTimeoutInitialMilliseconds: Uint32Xdr,
  val ballotTimeoutIncrementMilliseconds: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ConfigSettingSCPTimingXdr {
      val ledgerTargetCloseTimeMilliseconds = Uint32Xdr.decode(reader)
      val nominationTimeoutInitialMilliseconds = Uint32Xdr.decode(reader)
      val nominationTimeoutIncrementMilliseconds = Uint32Xdr.decode(reader)
      val ballotTimeoutInitialMilliseconds = Uint32Xdr.decode(reader)
      val ballotTimeoutIncrementMilliseconds = Uint32Xdr.decode(reader)
      return ConfigSettingSCPTimingXdr(ledgerTargetCloseTimeMilliseconds, nominationTimeoutInitialMilliseconds, nominationTimeoutIncrementMilliseconds, ballotTimeoutInitialMilliseconds, ballotTimeoutIncrementMilliseconds)
    }

    fun fromXdrJson(json: String): ConfigSettingSCPTimingXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ConfigSettingSCPTimingXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ConfigSettingSCPTimingXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return ConfigSettingSCPTimingXdr(
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "ledger_target_close_time_milliseconds", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "nomination_timeout_initial_milliseconds", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "nomination_timeout_increment_milliseconds", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "ballot_timeout_initial_milliseconds", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "ballot_timeout_increment_milliseconds", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    ledgerTargetCloseTimeMilliseconds.encode(writer)
    nominationTimeoutInitialMilliseconds.encode(writer)
    nominationTimeoutIncrementMilliseconds.encode(writer)
    ballotTimeoutInitialMilliseconds.encode(writer)
    ballotTimeoutIncrementMilliseconds.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("ledger_target_close_time_milliseconds", ledgerTargetCloseTimeMilliseconds.toXdrJsonElement())
    put("nomination_timeout_initial_milliseconds", nominationTimeoutInitialMilliseconds.toXdrJsonElement())
    put("nomination_timeout_increment_milliseconds", nominationTimeoutIncrementMilliseconds.toXdrJsonElement())
    put("ballot_timeout_initial_milliseconds", ballotTimeoutInitialMilliseconds.toXdrJsonElement())
    put("ballot_timeout_increment_milliseconds", ballotTimeoutIncrementMilliseconds.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
