// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ConfigSettingContractHistoricalDataV0Xdr"

/**
 * XDR Source:
 * struct ConfigSettingContractHistoricalDataV0
 * {
 *     int64 feeHistorical1KB; // Fee for storing 1KB in archives
 * };
 */
data class ConfigSettingContractHistoricalDataV0Xdr(
  /** Fee for storing 1KB in archives */
  val feeHistorical1Kb: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ConfigSettingContractHistoricalDataV0Xdr {
      val feeHistorical1Kb = Int64Xdr.decode(reader)
      return ConfigSettingContractHistoricalDataV0Xdr(feeHistorical1Kb)
    }

    fun fromXdrJson(json: String): ConfigSettingContractHistoricalDataV0Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ConfigSettingContractHistoricalDataV0Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ConfigSettingContractHistoricalDataV0Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return ConfigSettingContractHistoricalDataV0Xdr(
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "fee_historical1_kb", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    feeHistorical1Kb.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("fee_historical1_kb", feeHistorical1Kb.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
