// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ContractExecutableXdr"

/**
 * XDR Source:
 * union ContractExecutable switch (ContractExecutableType type)
 * {
 * case CONTRACT_EXECUTABLE_WASM:
 *     Hash wasm_hash;
 * case CONTRACT_EXECUTABLE_STELLAR_ASSET:
 *     void;
 * case CONTRACT_EXECUTABLE_EXTERNAL_REF:
 *     ContractExecutableExternalRef external_ref;
 * };
 */
sealed class ContractExecutableXdr {
  abstract val discriminant: ContractExecutableTypeXdr

  data class WasmHash(
    val value: HashXdr
  ) : ContractExecutableXdr() {
    override val discriminant: ContractExecutableTypeXdr = ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_WASM
  }

  data class ExternalRef(
    val value: ContractExecutableExternalRefXdr
  ) : ContractExecutableXdr() {
    override val discriminant: ContractExecutableTypeXdr = ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_EXTERNAL_REF
  }

  data object Void : ContractExecutableXdr() {
    override val discriminant: ContractExecutableTypeXdr = ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_STELLAR_ASSET
  }

  companion object {

    fun decode(reader: XdrReader): ContractExecutableXdr {
      val discriminant = ContractExecutableTypeXdr.decode(reader)
      return when (discriminant) {
        ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_WASM -> {
          val value = HashXdr.decode(reader)
          WasmHash(value)
        }
        ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_STELLAR_ASSET -> Void
        ContractExecutableTypeXdr.CONTRACT_EXECUTABLE_EXTERNAL_REF -> {
          val value = ContractExecutableExternalRefXdr.decode(reader)
          ExternalRef(value)
        }
        else -> throw IllegalArgumentException("Unknown ContractExecutableXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): ContractExecutableXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ContractExecutableXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ContractExecutableXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "wasm" -> WasmHash(HashXdr.fromXdrJsonTree(value))
          "external_ref" -> ExternalRef(ContractExecutableExternalRefXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "stellar_asset" -> Void
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is WasmHash -> {
        value.encode(writer)
      }
      is Void -> {}
      is ExternalRef -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is WasmHash -> buildJsonObject { put("wasm", value.toXdrJsonElement()) }
    is Void -> XdrJson.name("stellar_asset")
    is ExternalRef -> buildJsonObject { put("external_ref", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
