// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ContractExecutableExternalRef {
 *     SCAddress executable_owner;
 *     SCString tag;
 * };
 */
data class ContractExecutableExternalRefXdr(
  val executableOwner: SCAddressXdr,
  val tag: SCStringXdr
) {
  companion object {

    fun decode(reader: XdrReader): ContractExecutableExternalRefXdr {
      val executableOwner = SCAddressXdr.decode(reader)
      val tag = SCStringXdr.decode(reader)
      return ContractExecutableExternalRefXdr(executableOwner, tag)
    }
  }

  fun encode(writer: XdrWriter) {
    executableOwner.encode(writer)
    tag.encode(writer)
  }
}
