// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct
 *             {
 *                 ExtensionPoint ext;
 *                 ContractCodeCostInputs costInputs;
 *             }
 */
data class ContractCodeEntryV1Xdr(
  val ext: ExtensionPointXdr,
  val costInputs: ContractCodeCostInputsXdr
) {
  companion object {

    fun decode(reader: XdrReader): ContractCodeEntryV1Xdr {
      val ext = ExtensionPointXdr.decode(reader)
      val costInputs = ContractCodeCostInputsXdr.decode(reader)
      return ContractCodeEntryV1Xdr(ext, costInputs)
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    costInputs.encode(writer)
  }
}
