// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "ContractCostParamsXdr"

/**
 * XDR Source:
 * typedef ContractCostParamEntry ContractCostParams<CONTRACT_COST_COUNT_LIMIT>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class ContractCostParamsXdr(val value: List<ContractCostParamEntryXdr>) {
  companion object {
    fun decode(reader: XdrReader): ContractCostParamsXdr {
      val value = List(reader.readInt()) { ContractCostParamEntryXdr.decode(reader) }
      return ContractCostParamsXdr(value)
    }

    fun fromXdrJson(json: String): ContractCostParamsXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ContractCostParamsXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ContractCostParamsXdr = ContractCostParamsXdr(XdrJson.array(element, XDR_JSON_TYPE, "value", maxLength = CONTRACT_COST_COUNT_LIMIT).map { ContractCostParamEntryXdr.fromXdrJsonTree(it) })
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value.size)
    value.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.array(value) { it.toXdrJsonElement() }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
