// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * enum CreateClaimableBalanceResultCode
 * {
 *     CREATE_CLAIMABLE_BALANCE_SUCCESS = 0,
 *     CREATE_CLAIMABLE_BALANCE_MALFORMED = -1,
 *     CREATE_CLAIMABLE_BALANCE_LOW_RESERVE = -2,
 *     CREATE_CLAIMABLE_BALANCE_NO_TRUST = -3,
 *     CREATE_CLAIMABLE_BALANCE_NOT_AUTHORIZED = -4,
 *     CREATE_CLAIMABLE_BALANCE_UNDERFUNDED = -5
 * };
 */
enum class CreateClaimableBalanceResultCodeXdr(val value: Int) {
  CREATE_CLAIMABLE_BALANCE_SUCCESS(0),
  CREATE_CLAIMABLE_BALANCE_MALFORMED(-1),
  CREATE_CLAIMABLE_BALANCE_LOW_RESERVE(-2),
  CREATE_CLAIMABLE_BALANCE_NO_TRUST(-3),
  CREATE_CLAIMABLE_BALANCE_NOT_AUTHORIZED(-4),
  CREATE_CLAIMABLE_BALANCE_UNDERFUNDED(-5);

  companion object {

    fun decode(reader: XdrReader): CreateClaimableBalanceResultCodeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown CreateClaimableBalanceResultCodeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
