// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct DecoratedSignature
 * {
 *     SignatureHint hint;  // last 4 bytes of the public key, used as a hint
 *     Signature signature; // actual signature
 * };
 */
data class DecoratedSignatureXdr(
  /** last 4 bytes of the public key, used as a hint */
  val hint: SignatureHintXdr,
  /** actual signature */
  val signature: SignatureXdr
) {
  companion object {

    fun decode(reader: XdrReader): DecoratedSignatureXdr {
      val hint = SignatureHintXdr.decode(reader)
      val signature = SignatureXdr.decode(reader)
      return DecoratedSignatureXdr(hint, signature)
    }
  }

  fun encode(writer: XdrWriter) {
    hint.encode(writer)
    signature.encode(writer)
  }
}
