// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "DurationXdr"

/**
 * XDR Source:
 * typedef uint64 Duration;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class DurationXdr(val value: Uint64Xdr) {
  companion object {
    fun decode(reader: XdrReader): DurationXdr {
      val value = Uint64Xdr.decode(reader)
      return DurationXdr(value)
    }

    fun fromXdrJson(json: String): DurationXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): DurationXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): DurationXdr = DurationXdr(Uint64Xdr.fromXdrJsonTree(element))
  }

  fun encode(writer: XdrWriter) {
    value.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = value.toXdrJsonElement()

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
