// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "EncodedLedgerKeyXdr"

/**
 * XDR Source:
 * typedef opaque EncodedLedgerKey<>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class EncodedLedgerKeyXdr(val value: ByteArray) {
  companion object {
    fun decode(reader: XdrReader): EncodedLedgerKeyXdr {
      val value = reader.readVariableOpaque()
      return EncodedLedgerKeyXdr(value)
    }

    fun fromXdrJson(json: String): EncodedLedgerKeyXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): EncodedLedgerKeyXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): EncodedLedgerKeyXdr = EncodedLedgerKeyXdr(XdrJson.hex(element, XDR_JSON_TYPE, "value"))
  }

  fun encode(writer: XdrWriter) {
    writer.writeVariableOpaque(value)
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.hex(value)

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
