// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * union ExtensionPoint switch (int v)
 * {
 * case 0:
 *     void;
 * };
 */
sealed class ExtensionPointXdr {
  abstract val discriminant: Int

  data object Void : ExtensionPointXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): ExtensionPointXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> Void
        else -> throw IllegalArgumentException("Unknown ExtensionPointXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is Void -> {}
    }
  }
}
