// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "FeeBumpTransactionEnvelopeXdr"

/**
 * XDR Source:
 * struct FeeBumpTransactionEnvelope
 * {
 *     FeeBumpTransaction tx;
 *     /* Each decorated signature is a signature over the SHA256 hash of
 *      * a TransactionSignaturePayload */
 *     DecoratedSignature signatures<20>;
 * };
 */
data class FeeBumpTransactionEnvelopeXdr(
  val tx: FeeBumpTransactionXdr,
  val signatures: List<DecoratedSignatureXdr>
) {
  companion object {

    fun decode(reader: XdrReader): FeeBumpTransactionEnvelopeXdr {
      val tx = FeeBumpTransactionXdr.decode(reader)
      val signatures = List(reader.readInt()) { DecoratedSignatureXdr.decode(reader) }
      return FeeBumpTransactionEnvelopeXdr(tx, signatures)
    }

    fun fromXdrJson(json: String): FeeBumpTransactionEnvelopeXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): FeeBumpTransactionEnvelopeXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): FeeBumpTransactionEnvelopeXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return FeeBumpTransactionEnvelopeXdr(
        FeeBumpTransactionXdr.fromXdrJsonTree(XdrJson.field(json, "tx", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "signatures", XDR_JSON_TYPE), XDR_JSON_TYPE, "signatures", maxLength = 20).map { DecoratedSignatureXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    tx.encode(writer)
    writer.writeInt(signatures.size)
    signatures.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("tx", tx.toXdrJsonElement())
    put("signatures", XdrJson.array(signatures) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
