// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "FeeBumpTransactionXdr"

/**
 * XDR Source:
 * struct FeeBumpTransaction
 * {
 *     MuxedAccount feeSource;
 *     int64 fee;
 *     union switch (EnvelopeType type)
 *     {
 *     case ENVELOPE_TYPE_TX:
 *         TransactionV1Envelope v1;
 *     }
 *     innerTx;
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 */
data class FeeBumpTransactionXdr(
  val feeSource: MuxedAccountXdr,
  val fee: Int64Xdr,
  val innerTx: FeeBumpTransactionInnerTxXdr,
  val ext: FeeBumpTransactionExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): FeeBumpTransactionXdr {
      val feeSource = MuxedAccountXdr.decode(reader)
      val fee = Int64Xdr.decode(reader)
      val innerTx = FeeBumpTransactionInnerTxXdr.decode(reader)
      val ext = FeeBumpTransactionExtXdr.decode(reader)
      return FeeBumpTransactionXdr(feeSource, fee, innerTx, ext)
    }

    fun fromXdrJson(json: String): FeeBumpTransactionXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): FeeBumpTransactionXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): FeeBumpTransactionXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return FeeBumpTransactionXdr(
        MuxedAccountXdr.fromXdrJsonTree(XdrJson.field(json, "fee_source", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "fee", XDR_JSON_TYPE)),
        FeeBumpTransactionInnerTxXdr.fromXdrJsonTree(XdrJson.field(json, "inner_tx", XDR_JSON_TYPE)),
        FeeBumpTransactionExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    feeSource.encode(writer)
    fee.encode(writer)
    innerTx.encode(writer)
    ext.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("fee_source", feeSource.toXdrJsonElement())
    put("fee", fee.toXdrJsonElement())
    put("inner_tx", innerTx.toXdrJsonElement())
    put("ext", ext.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
