// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct FreezeBypassTxs {
 *     Hash txHashes<>;
 * };
 */
data class FreezeBypassTxsXdr(
  val txHashes: List<HashXdr>
) {
  companion object {

    fun decode(reader: XdrReader): FreezeBypassTxsXdr {
      val txHashes = List(reader.readInt()) { HashXdr.decode(reader) }
      return FreezeBypassTxsXdr(txHashes)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(txHashes.size)
    txHashes.forEach { item ->
      item.encode(writer)
    }
  }
}
