// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "FreezeBypassTxsDeltaXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("add_txs", "remove_txs")

/**
 * XDR Source:
 * struct FreezeBypassTxsDelta {
 *     Hash addTxs<>;
 *     Hash removeTxs<>;
 * };
 */
data class FreezeBypassTxsDeltaXdr(
  val addTxs: List<HashXdr>,
  val removeTxs: List<HashXdr>
) {
  companion object {

    fun decode(reader: XdrReader): FreezeBypassTxsDeltaXdr {
      val addTxs = List(reader.readInt()) { HashXdr.decode(reader) }
      val removeTxs = List(reader.readInt()) { HashXdr.decode(reader) }
      return FreezeBypassTxsDeltaXdr(addTxs, removeTxs)
    }

    fun fromXdrJson(json: String): FreezeBypassTxsDeltaXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): FreezeBypassTxsDeltaXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): FreezeBypassTxsDeltaXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return FreezeBypassTxsDeltaXdr(
        XdrJson.array(XdrJson.field(json, "add_txs", XDR_JSON_TYPE), XDR_JSON_TYPE, "add_txs").map { HashXdr.fromXdrJsonTree(it) },
        XdrJson.array(XdrJson.field(json, "remove_txs", XDR_JSON_TYPE), XDR_JSON_TYPE, "remove_txs").map { HashXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(addTxs.size)
    addTxs.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(removeTxs.size)
    removeTxs.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("add_txs", XdrJson.array(addTxs) { it.toXdrJsonElement() })
    put("remove_txs", XdrJson.array(removeTxs) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
