// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "FrozenLedgerKeysDeltaXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("keys_to_freeze", "keys_to_unfreeze")

/**
 * XDR Source:
 * struct FrozenLedgerKeysDelta {
 *     EncodedLedgerKey keysToFreeze<>;
 *     EncodedLedgerKey keysToUnfreeze<>;
 * };
 */
data class FrozenLedgerKeysDeltaXdr(
  val keysToFreeze: List<EncodedLedgerKeyXdr>,
  val keysToUnfreeze: List<EncodedLedgerKeyXdr>
) {
  companion object {

    fun decode(reader: XdrReader): FrozenLedgerKeysDeltaXdr {
      val keysToFreeze = List(reader.readInt()) { EncodedLedgerKeyXdr.decode(reader) }
      val keysToUnfreeze = List(reader.readInt()) { EncodedLedgerKeyXdr.decode(reader) }
      return FrozenLedgerKeysDeltaXdr(keysToFreeze, keysToUnfreeze)
    }

    fun fromXdrJson(json: String): FrozenLedgerKeysDeltaXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): FrozenLedgerKeysDeltaXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): FrozenLedgerKeysDeltaXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return FrozenLedgerKeysDeltaXdr(
        XdrJson.array(XdrJson.field(json, "keys_to_freeze", XDR_JSON_TYPE), XDR_JSON_TYPE, "keys_to_freeze").map { EncodedLedgerKeyXdr.fromXdrJsonTree(it) },
        XdrJson.array(XdrJson.field(json, "keys_to_unfreeze", XDR_JSON_TYPE), XDR_JSON_TYPE, "keys_to_unfreeze").map { EncodedLedgerKeyXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(keysToFreeze.size)
    keysToFreeze.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(keysToUnfreeze.size)
    keysToUnfreeze.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("keys_to_freeze", XdrJson.array(keysToFreeze) { it.toXdrJsonElement() })
    put("keys_to_unfreeze", XdrJson.array(keysToUnfreeze) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
