// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "HashIDPreimageRevokeIDXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("source_account", "seq_num", "op_num", "liquidity_pool_id", "asset")

/**
 * XDR Source:
 * struct
 *     {
 *         AccountID sourceAccount;
 *         SequenceNumber seqNum;
 *         uint32 opNum;
 *         PoolID liquidityPoolID;
 *         Asset asset;
 *     }
 */
data class HashIDPreimageRevokeIDXdr(
  val sourceAccount: AccountIDXdr,
  val seqNum: SequenceNumberXdr,
  val opNum: Uint32Xdr,
  val liquidityPoolId: PoolIDXdr,
  val asset: AssetXdr
) {
  companion object {

    fun decode(reader: XdrReader): HashIDPreimageRevokeIDXdr {
      val sourceAccount = AccountIDXdr.decode(reader)
      val seqNum = SequenceNumberXdr.decode(reader)
      val opNum = Uint32Xdr.decode(reader)
      val liquidityPoolId = PoolIDXdr.decode(reader)
      val asset = AssetXdr.decode(reader)
      return HashIDPreimageRevokeIDXdr(sourceAccount, seqNum, opNum, liquidityPoolId, asset)
    }

    fun fromXdrJson(json: String): HashIDPreimageRevokeIDXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): HashIDPreimageRevokeIDXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): HashIDPreimageRevokeIDXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return HashIDPreimageRevokeIDXdr(
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "source_account", XDR_JSON_TYPE)),
        SequenceNumberXdr.fromXdrJsonTree(XdrJson.field(json, "seq_num", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "op_num", XDR_JSON_TYPE)),
        PoolIDXdr.fromXdrJsonTree(XdrJson.field(json, "liquidity_pool_id", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    sourceAccount.encode(writer)
    seqNum.encode(writer)
    opNum.encode(writer)
    liquidityPoolId.encode(writer)
    asset.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("source_account", sourceAccount.toXdrJsonElement())
    put("seq_num", seqNum.toXdrJsonElement())
    put("op_num", opNum.toXdrJsonElement())
    put("liquidity_pool_id", liquidityPoolId.toXdrJsonElement())
    put("asset", asset.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
