// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * union switch (TransactionResultCode code)
 *     {
 *     // txFEE_BUMP_INNER_SUCCESS is not included
 *     case txSUCCESS:
 *     case txFAILED:
 *         OperationResult results<>;
 *     case txTOO_EARLY:
 *     case txTOO_LATE:
 *     case txMISSING_OPERATION:
 *     case txBAD_SEQ:
 *     case txBAD_AUTH:
 *     case txINSUFFICIENT_BALANCE:
 *     case txNO_ACCOUNT:
 *     case txINSUFFICIENT_FEE:
 *     case txBAD_AUTH_EXTRA:
 *     case txINTERNAL_ERROR:
 *     case txNOT_SUPPORTED:
 *     // txFEE_BUMP_INNER_FAILED is not included
 *     case txBAD_SPONSORSHIP:
 *     case txBAD_MIN_SEQ_AGE_OR_GAP:
 *     case txMALFORMED:
 *     case txSOROBAN_INVALID:
 *         void;
 *     }
 */
sealed class InnerTransactionResultResultXdr {
  abstract val discriminant: TransactionResultCodeXdr

  /** txFEE_BUMP_INNER_SUCCESS is not included */
  data class Results(
    val value: List<OperationResultXdr>
  ) : InnerTransactionResultResultXdr() {
    override val discriminant: TransactionResultCodeXdr = TransactionResultCodeXdr.txSUCCESS
  }

  /** txFEE_BUMP_INNER_FAILED is not included */
  data class Void(
    override val discriminant: TransactionResultCodeXdr
  ) : InnerTransactionResultResultXdr()

  companion object {

    fun decode(reader: XdrReader): InnerTransactionResultResultXdr {
      val discriminant = TransactionResultCodeXdr.decode(reader)
      return when (discriminant) {
        TransactionResultCodeXdr.txSUCCESS -> {
          val value = List(reader.readInt()) { OperationResultXdr.decode(reader) }
          Results(value)
        }
        TransactionResultCodeXdr.txFAILED -> {
          val value = List(reader.readInt()) { OperationResultXdr.decode(reader) }
          Results(value)
        }
        TransactionResultCodeXdr.txTOO_EARLY -> Void(discriminant)
        TransactionResultCodeXdr.txTOO_LATE -> Void(discriminant)
        TransactionResultCodeXdr.txMISSING_OPERATION -> Void(discriminant)
        TransactionResultCodeXdr.txBAD_SEQ -> Void(discriminant)
        TransactionResultCodeXdr.txBAD_AUTH -> Void(discriminant)
        TransactionResultCodeXdr.txINSUFFICIENT_BALANCE -> Void(discriminant)
        TransactionResultCodeXdr.txNO_ACCOUNT -> Void(discriminant)
        TransactionResultCodeXdr.txINSUFFICIENT_FEE -> Void(discriminant)
        TransactionResultCodeXdr.txBAD_AUTH_EXTRA -> Void(discriminant)
        TransactionResultCodeXdr.txINTERNAL_ERROR -> Void(discriminant)
        TransactionResultCodeXdr.txNOT_SUPPORTED -> Void(discriminant)
        TransactionResultCodeXdr.txBAD_SPONSORSHIP -> Void(discriminant)
        TransactionResultCodeXdr.txBAD_MIN_SEQ_AGE_OR_GAP -> Void(discriminant)
        TransactionResultCodeXdr.txMALFORMED -> Void(discriminant)
        TransactionResultCodeXdr.txSOROBAN_INVALID -> Void(discriminant)
        else -> throw IllegalArgumentException("Unknown InnerTransactionResultResultXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Results -> {
        writer.writeInt(value.size)
        value.forEach { item ->
          item.encode(writer)
        }
      }
      is Void -> {}
    }
  }
}
