// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct InnerTransactionResult
 * {
 *     // Always 0. Here for binary compatibility.
 *     int64 feeCharged;
 * 
 *     union switch (TransactionResultCode code)
 *     {
 *     // txFEE_BUMP_INNER_SUCCESS is not included
 *     case txSUCCESS:
 *     case txFAILED:
 *         OperationResult results<>;
 *     case txTOO_EARLY:
 *     case txTOO_LATE:
 *     case txMISSING_OPERATION:
 *     case txBAD_SEQ:
 *     case txBAD_AUTH:
 *     case txINSUFFICIENT_BALANCE:
 *     case txNO_ACCOUNT:
 *     case txINSUFFICIENT_FEE:
 *     case txBAD_AUTH_EXTRA:
 *     case txINTERNAL_ERROR:
 *     case txNOT_SUPPORTED:
 *     // txFEE_BUMP_INNER_FAILED is not included
 *     case txBAD_SPONSORSHIP:
 *     case txBAD_MIN_SEQ_AGE_OR_GAP:
 *     case txMALFORMED:
 *     case txSOROBAN_INVALID:
 *         void;
 *     }
 *     result;
 * 
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 */
data class InnerTransactionResultXdr(
  /** Always 0. Here for binary compatibility. */
  val feeCharged: Int64Xdr,
  val result: InnerTransactionResultResultXdr,
  val ext: InnerTransactionResultExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): InnerTransactionResultXdr {
      val feeCharged = Int64Xdr.decode(reader)
      val result = InnerTransactionResultResultXdr.decode(reader)
      val ext = InnerTransactionResultExtXdr.decode(reader)
      return InnerTransactionResultXdr(feeCharged, result, ext)
    }
  }

  fun encode(writer: XdrWriter) {
    feeCharged.encode(writer)
    result.encode(writer)
    ext.encode(writer)
  }
}
