// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef hyper int64;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class Int64Xdr(val value: Long) {
  companion object {
    fun decode(reader: XdrReader): Int64Xdr {
      val value = reader.readLong()
      return Int64Xdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeLong(value)
  }
}
