// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "InvokeHostFunctionResultXdr"

/**
 * XDR Source:
 * union InvokeHostFunctionResult switch (InvokeHostFunctionResultCode code)
 * {
 * case INVOKE_HOST_FUNCTION_SUCCESS:
 *     Hash success; // sha256(InvokeHostFunctionSuccessPreImage)
 * case INVOKE_HOST_FUNCTION_MALFORMED:
 * case INVOKE_HOST_FUNCTION_TRAPPED:
 * case INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED:
 * case INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED:
 * case INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE:
 *     void;
 * };
 */
sealed class InvokeHostFunctionResultXdr {
  abstract val discriminant: InvokeHostFunctionResultCodeXdr

  data class Success(
    val value: HashXdr
  ) : InvokeHostFunctionResultXdr() {
    override val discriminant: InvokeHostFunctionResultCodeXdr = InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_SUCCESS
  }

  data class Void(
    override val discriminant: InvokeHostFunctionResultCodeXdr
  ) : InvokeHostFunctionResultXdr()

  companion object {

    fun decode(reader: XdrReader): InvokeHostFunctionResultXdr {
      val discriminant = InvokeHostFunctionResultCodeXdr.decode(reader)
      return when (discriminant) {
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_SUCCESS -> {
          val value = HashXdr.decode(reader)
          Success(value)
        }
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_MALFORMED -> Void(discriminant)
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_TRAPPED -> Void(discriminant)
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED -> Void(discriminant)
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED -> Void(discriminant)
        InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE -> Void(discriminant)
        else -> throw IllegalArgumentException("Unknown InvokeHostFunctionResultXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): InvokeHostFunctionResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): InvokeHostFunctionResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): InvokeHostFunctionResultXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "success" -> Success(HashXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "malformed" -> Void(InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_MALFORMED)
        "trapped" -> Void(InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_TRAPPED)
        "resource_limit_exceeded" -> Void(InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_RESOURCE_LIMIT_EXCEEDED)
        "entry_archived" -> Void(InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_ENTRY_ARCHIVED)
        "insufficient_refundable_fee" -> Void(InvokeHostFunctionResultCodeXdr.INVOKE_HOST_FUNCTION_INSUFFICIENT_REFUNDABLE_FEE)
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Success -> {
        value.encode(writer)
      }
      is Void -> {}
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Success -> buildJsonObject { put("success", value.toXdrJsonElement()) }
    is Void -> XdrJson.name(discriminant.xdrJsonName)
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
