// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerEntryDataXdr"

/**
 * XDR Source:
 * union switch (LedgerEntryType type)
 *     {
 *     case ACCOUNT:
 *         AccountEntry account;
 *     case TRUSTLINE:
 *         TrustLineEntry trustLine;
 *     case OFFER:
 *         OfferEntry offer;
 *     case DATA:
 *         DataEntry data;
 *     case CLAIMABLE_BALANCE:
 *         ClaimableBalanceEntry claimableBalance;
 *     case LIQUIDITY_POOL:
 *         LiquidityPoolEntry liquidityPool;
 *     case CONTRACT_DATA:
 *         ContractDataEntry contractData;
 *     case CONTRACT_CODE:
 *         ContractCodeEntry contractCode;
 *     case CONFIG_SETTING:
 *         ConfigSettingEntry configSetting;
 *     case TTL:
 *         TTLEntry ttl;
 *     }
 */
sealed class LedgerEntryDataXdr {
  abstract val discriminant: LedgerEntryTypeXdr

  data class Account(
    val value: AccountEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.ACCOUNT
  }

  data class TrustLine(
    val value: TrustLineEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.TRUSTLINE
  }

  data class Offer(
    val value: OfferEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.OFFER
  }

  data class Data(
    val value: DataEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.DATA
  }

  data class ClaimableBalance(
    val value: ClaimableBalanceEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.CLAIMABLE_BALANCE
  }

  data class LiquidityPool(
    val value: LiquidityPoolEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.LIQUIDITY_POOL
  }

  data class ContractData(
    val value: ContractDataEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.CONTRACT_DATA
  }

  data class ContractCode(
    val value: ContractCodeEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.CONTRACT_CODE
  }

  data class ConfigSetting(
    val value: ConfigSettingEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.CONFIG_SETTING
  }

  data class Ttl(
    val value: TTLEntryXdr
  ) : LedgerEntryDataXdr() {
    override val discriminant: LedgerEntryTypeXdr = LedgerEntryTypeXdr.TTL
  }

  companion object {

    fun decode(reader: XdrReader): LedgerEntryDataXdr {
      val discriminant = LedgerEntryTypeXdr.decode(reader)
      return when (discriminant) {
        LedgerEntryTypeXdr.ACCOUNT -> {
          val value = AccountEntryXdr.decode(reader)
          Account(value)
        }
        LedgerEntryTypeXdr.TRUSTLINE -> {
          val value = TrustLineEntryXdr.decode(reader)
          TrustLine(value)
        }
        LedgerEntryTypeXdr.OFFER -> {
          val value = OfferEntryXdr.decode(reader)
          Offer(value)
        }
        LedgerEntryTypeXdr.DATA -> {
          val value = DataEntryXdr.decode(reader)
          Data(value)
        }
        LedgerEntryTypeXdr.CLAIMABLE_BALANCE -> {
          val value = ClaimableBalanceEntryXdr.decode(reader)
          ClaimableBalance(value)
        }
        LedgerEntryTypeXdr.LIQUIDITY_POOL -> {
          val value = LiquidityPoolEntryXdr.decode(reader)
          LiquidityPool(value)
        }
        LedgerEntryTypeXdr.CONTRACT_DATA -> {
          val value = ContractDataEntryXdr.decode(reader)
          ContractData(value)
        }
        LedgerEntryTypeXdr.CONTRACT_CODE -> {
          val value = ContractCodeEntryXdr.decode(reader)
          ContractCode(value)
        }
        LedgerEntryTypeXdr.CONFIG_SETTING -> {
          val value = ConfigSettingEntryXdr.decode(reader)
          ConfigSetting(value)
        }
        LedgerEntryTypeXdr.TTL -> {
          val value = TTLEntryXdr.decode(reader)
          Ttl(value)
        }
        else -> throw IllegalArgumentException("Unknown LedgerEntryDataXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): LedgerEntryDataXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerEntryDataXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerEntryDataXdr {
      val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
      return when (arm) {
        "account" -> Account(AccountEntryXdr.fromXdrJsonTree(value))
        "trustline" -> TrustLine(TrustLineEntryXdr.fromXdrJsonTree(value))
        "offer" -> Offer(OfferEntryXdr.fromXdrJsonTree(value))
        "data" -> Data(DataEntryXdr.fromXdrJsonTree(value))
        "claimable_balance" -> ClaimableBalance(ClaimableBalanceEntryXdr.fromXdrJsonTree(value))
        "liquidity_pool" -> LiquidityPool(LiquidityPoolEntryXdr.fromXdrJsonTree(value))
        "contract_data" -> ContractData(ContractDataEntryXdr.fromXdrJsonTree(value))
        "contract_code" -> ContractCode(ContractCodeEntryXdr.fromXdrJsonTree(value))
        "config_setting" -> ConfigSetting(ConfigSettingEntryXdr.fromXdrJsonTree(value))
        "ttl" -> Ttl(TTLEntryXdr.fromXdrJsonTree(value))
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Account -> {
        value.encode(writer)
      }
      is TrustLine -> {
        value.encode(writer)
      }
      is Offer -> {
        value.encode(writer)
      }
      is Data -> {
        value.encode(writer)
      }
      is ClaimableBalance -> {
        value.encode(writer)
      }
      is LiquidityPool -> {
        value.encode(writer)
      }
      is ContractData -> {
        value.encode(writer)
      }
      is ContractCode -> {
        value.encode(writer)
      }
      is ConfigSetting -> {
        value.encode(writer)
      }
      is Ttl -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Account -> buildJsonObject { put("account", value.toXdrJsonElement()) }
    is TrustLine -> buildJsonObject { put("trustline", value.toXdrJsonElement()) }
    is Offer -> buildJsonObject { put("offer", value.toXdrJsonElement()) }
    is Data -> buildJsonObject { put("data", value.toXdrJsonElement()) }
    is ClaimableBalance -> buildJsonObject { put("claimable_balance", value.toXdrJsonElement()) }
    is LiquidityPool -> buildJsonObject { put("liquidity_pool", value.toXdrJsonElement()) }
    is ContractData -> buildJsonObject { put("contract_data", value.toXdrJsonElement()) }
    is ContractCode -> buildJsonObject { put("contract_code", value.toXdrJsonElement()) }
    is ConfigSetting -> buildJsonObject { put("config_setting", value.toXdrJsonElement()) }
    is Ttl -> buildJsonObject { put("ttl", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
