// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerEntryXdr"

/**
 * XDR Source:
 * struct LedgerEntry
 * {
 *     uint32 lastModifiedLedgerSeq; // ledger the LedgerEntry was last changed
 * 
 *     union switch (LedgerEntryType type)
 *     {
 *     case ACCOUNT:
 *         AccountEntry account;
 *     case TRUSTLINE:
 *         TrustLineEntry trustLine;
 *     case OFFER:
 *         OfferEntry offer;
 *     case DATA:
 *         DataEntry data;
 *     case CLAIMABLE_BALANCE:
 *         ClaimableBalanceEntry claimableBalance;
 *     case LIQUIDITY_POOL:
 *         LiquidityPoolEntry liquidityPool;
 *     case CONTRACT_DATA:
 *         ContractDataEntry contractData;
 *     case CONTRACT_CODE:
 *         ContractCodeEntry contractCode;
 *     case CONFIG_SETTING:
 *         ConfigSettingEntry configSetting;
 *     case TTL:
 *         TTLEntry ttl;
 *     }
 *     data;
 * 
 *     // reserved for future use
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         LedgerEntryExtensionV1 v1;
 *     }
 *     ext;
 * };
 */
data class LedgerEntryXdr(
  /** ledger the LedgerEntry was last changed */
  val lastModifiedLedgerSeq: Uint32Xdr,
  val data: LedgerEntryDataXdr,
  val ext: LedgerEntryExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): LedgerEntryXdr {
      val lastModifiedLedgerSeq = Uint32Xdr.decode(reader)
      val data = LedgerEntryDataXdr.decode(reader)
      val ext = LedgerEntryExtXdr.decode(reader)
      return LedgerEntryXdr(lastModifiedLedgerSeq, data, ext)
    }

    fun fromXdrJson(json: String): LedgerEntryXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerEntryXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerEntryXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return LedgerEntryXdr(
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "last_modified_ledger_seq", XDR_JSON_TYPE)),
        LedgerEntryDataXdr.fromXdrJsonTree(XdrJson.field(json, "data", XDR_JSON_TYPE)),
        LedgerEntryExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    lastModifiedLedgerSeq.encode(writer)
    data.encode(writer)
    ext.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("last_modified_ledger_seq", lastModifiedLedgerSeq.toXdrJsonElement())
    put("data", data.toXdrJsonElement())
    put("ext", ext.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
