// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerEntryExtensionV1Xdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("sponsoring_id", "ext")

/**
 * XDR Source:
 * struct LedgerEntryExtensionV1
 * {
 *     SponsorshipDescriptor sponsoringID;
 * 
 *     union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     }
 *     ext;
 * };
 */
data class LedgerEntryExtensionV1Xdr(
  val sponsoringId: SponsorshipDescriptorXdr,
  val ext: LedgerEntryExtensionV1ExtXdr
) {
  companion object {

    fun decode(reader: XdrReader): LedgerEntryExtensionV1Xdr {
      val sponsoringId = SponsorshipDescriptorXdr.decode(reader)
      val ext = LedgerEntryExtensionV1ExtXdr.decode(reader)
      return LedgerEntryExtensionV1Xdr(sponsoringId, ext)
    }

    fun fromXdrJson(json: String): LedgerEntryExtensionV1Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerEntryExtensionV1Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerEntryExtensionV1Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return LedgerEntryExtensionV1Xdr(
        SponsorshipDescriptorXdr.fromXdrJsonTree(XdrJson.field(json, "sponsoring_id", XDR_JSON_TYPE)),
        LedgerEntryExtensionV1ExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    sponsoringId.encode(writer)
    ext.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("sponsoring_id", sponsoringId.toXdrJsonElement())
    put("ext", ext.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
