// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * typedef LedgerEntryChange LedgerEntryChanges<>;
 */
@Suppress("EXPECT_ACTUAL_INCOMPATIBILITY")
@kotlin.jvm.JvmInline
value class LedgerEntryChangesXdr(val value: List<LedgerEntryChangeXdr>) {
  companion object {
    fun decode(reader: XdrReader): LedgerEntryChangesXdr {
      val value = List(reader.readInt()) { LedgerEntryChangeXdr.decode(reader) }
      return LedgerEntryChangesXdr(value)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value.size)
    value.forEach { item ->
      item.encode(writer)
    }
  }
}
