// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerCloseMetaV2Xdr"

/**
 * XDR Source:
 * struct LedgerCloseMetaV2
 * {
 *     LedgerCloseMetaExt ext;
 * 
 *     LedgerHeaderHistoryEntry ledgerHeader;
 * 
 *     GeneralizedTransactionSet txSet;
 * 
 *     // NB: transactions are sorted in apply order here
 *     // fees for all transactions are processed first
 *     // followed by applying transactions
 *     TransactionResultMetaV1 txProcessing<>;
 * 
 *     // upgrades are applied last
 *     UpgradeEntryMeta upgradesProcessing<>;
 * 
 *     // other misc information attached to the ledger close
 *     SCPHistoryEntry scpInfo<>;
 * 
 *     // Size in bytes of live Soroban state, to support downstream
 *     // systems calculating storage fees correctly.
 *     uint64 totalByteSizeOfLiveSorobanState;
 * 
 *     // TTL and data/code keys that have been evicted at this ledger.
 *     LedgerKey evictedKeys<>;
 * };
 */
data class LedgerCloseMetaV2Xdr(
  val ext: LedgerCloseMetaExtXdr,
  val ledgerHeader: LedgerHeaderHistoryEntryXdr,
  val txSet: GeneralizedTransactionSetXdr,
  val txProcessing: List<TransactionResultMetaV1Xdr>,
  val upgradesProcessing: List<UpgradeEntryMetaXdr>,
  val scpInfo: List<SCPHistoryEntryXdr>,
  /**
   * Size in bytes of live Soroban state, to support downstream
   * systems calculating storage fees correctly.
   */
  val totalByteSizeOfLiveSorobanState: Uint64Xdr,
  val evictedKeys: List<LedgerKeyXdr>
) {
  companion object {

    fun decode(reader: XdrReader): LedgerCloseMetaV2Xdr {
      val ext = LedgerCloseMetaExtXdr.decode(reader)
      val ledgerHeader = LedgerHeaderHistoryEntryXdr.decode(reader)
      val txSet = GeneralizedTransactionSetXdr.decode(reader)
      val txProcessing = List(reader.readInt()) { TransactionResultMetaV1Xdr.decode(reader) }
      val upgradesProcessing = List(reader.readInt()) { UpgradeEntryMetaXdr.decode(reader) }
      val scpInfo = List(reader.readInt()) { SCPHistoryEntryXdr.decode(reader) }
      val totalByteSizeOfLiveSorobanState = Uint64Xdr.decode(reader)
      val evictedKeys = List(reader.readInt()) { LedgerKeyXdr.decode(reader) }
      return LedgerCloseMetaV2Xdr(ext, ledgerHeader, txSet, txProcessing, upgradesProcessing, scpInfo, totalByteSizeOfLiveSorobanState, evictedKeys)
    }

    fun fromXdrJson(json: String): LedgerCloseMetaV2Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerCloseMetaV2Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerCloseMetaV2Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return LedgerCloseMetaV2Xdr(
        LedgerCloseMetaExtXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE)),
        LedgerHeaderHistoryEntryXdr.fromXdrJsonTree(XdrJson.field(json, "ledger_header", XDR_JSON_TYPE)),
        GeneralizedTransactionSetXdr.fromXdrJsonTree(XdrJson.field(json, "tx_set", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "tx_processing", XDR_JSON_TYPE), XDR_JSON_TYPE, "tx_processing").map { TransactionResultMetaV1Xdr.fromXdrJsonTree(it) },
        XdrJson.array(XdrJson.field(json, "upgrades_processing", XDR_JSON_TYPE), XDR_JSON_TYPE, "upgrades_processing").map { UpgradeEntryMetaXdr.fromXdrJsonTree(it) },
        XdrJson.array(XdrJson.field(json, "scp_info", XDR_JSON_TYPE), XDR_JSON_TYPE, "scp_info").map { SCPHistoryEntryXdr.fromXdrJsonTree(it) },
        Uint64Xdr.fromXdrJsonTree(XdrJson.field(json, "total_byte_size_of_live_soroban_state", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "evicted_keys", XDR_JSON_TYPE), XDR_JSON_TYPE, "evicted_keys").map { LedgerKeyXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    ledgerHeader.encode(writer)
    txSet.encode(writer)
    writer.writeInt(txProcessing.size)
    txProcessing.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(upgradesProcessing.size)
    upgradesProcessing.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(scpInfo.size)
    scpInfo.forEach { item ->
      item.encode(writer)
    }
    totalByteSizeOfLiveSorobanState.encode(writer)
    writer.writeInt(evictedKeys.size)
    evictedKeys.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("ext", ext.toXdrJsonElement())
    put("ledger_header", ledgerHeader.toXdrJsonElement())
    put("tx_set", txSet.toXdrJsonElement())
    put("tx_processing", XdrJson.array(txProcessing) { it.toXdrJsonElement() })
    put("upgrades_processing", XdrJson.array(upgradesProcessing) { it.toXdrJsonElement() })
    put("scp_info", XdrJson.array(scpInfo) { it.toXdrJsonElement() })
    put("total_byte_size_of_live_soroban_state", totalByteSizeOfLiveSorobanState.toXdrJsonElement())
    put("evicted_keys", XdrJson.array(evictedKeys) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
