// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerKeyTtlXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("key_hash")

/**
 * XDR Source:
 * struct
 *     {
 *         // Hash of the LedgerKey that is associated with this TTLEntry
 *         Hash keyHash;
 *     }
 */
data class LedgerKeyTtlXdr(
  /** Hash of the LedgerKey that is associated with this TTLEntry */
  val keyHash: HashXdr
) {
  companion object {

    fun decode(reader: XdrReader): LedgerKeyTtlXdr {
      val keyHash = HashXdr.decode(reader)
      return LedgerKeyTtlXdr(keyHash)
    }

    fun fromXdrJson(json: String): LedgerKeyTtlXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerKeyTtlXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerKeyTtlXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return LedgerKeyTtlXdr(
        HashXdr.fromXdrJsonTree(XdrJson.field(json, "key_hash", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    keyHash.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("key_hash", keyHash.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
