// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LedgerCloseValueSignatureXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("node_id", "signature")

/**
 * XDR Source:
 * struct LedgerCloseValueSignature
 * {
 *     NodeID nodeID;       // which node introduced the value
 *     Signature signature; // nodeID's signature
 * };
 */
data class LedgerCloseValueSignatureXdr(
  /** which node introduced the value */
  val nodeId: NodeIDXdr,
  /** nodeID's signature */
  val signature: SignatureXdr
) {
  companion object {

    fun decode(reader: XdrReader): LedgerCloseValueSignatureXdr {
      val nodeId = NodeIDXdr.decode(reader)
      val signature = SignatureXdr.decode(reader)
      return LedgerCloseValueSignatureXdr(nodeId, signature)
    }

    fun fromXdrJson(json: String): LedgerCloseValueSignatureXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LedgerCloseValueSignatureXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LedgerCloseValueSignatureXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return LedgerCloseValueSignatureXdr(
        NodeIDXdr.fromXdrJsonTree(XdrJson.field(json, "node_id", XDR_JSON_TYPE)),
        SignatureXdr.fromXdrJsonTree(XdrJson.field(json, "signature", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    nodeId.encode(writer)
    signature.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("node_id", nodeId.toXdrJsonElement())
    put("signature", signature.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
