// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LiquidityPoolEntryBodyXdr"

/**
 * XDR Source:
 * union switch (LiquidityPoolType type)
 *     {
 *     case LIQUIDITY_POOL_CONSTANT_PRODUCT:
 *         struct
 *         {
 *             LiquidityPoolConstantProductParameters params;
 * 
 *             int64 reserveA;        // amount of A in the pool
 *             int64 reserveB;        // amount of B in the pool
 *             int64 totalPoolShares; // total number of pool shares issued
 *             int64 poolSharesTrustLineCount; // number of trust lines for the
 *                                             // associated pool shares
 *         } constantProduct;
 *     }
 */
sealed class LiquidityPoolEntryBodyXdr {
  abstract val discriminant: LiquidityPoolTypeXdr

  data class ConstantProduct(
    val value: LiquidityPoolEntryConstantProductXdr
  ) : LiquidityPoolEntryBodyXdr() {
    override val discriminant: LiquidityPoolTypeXdr = LiquidityPoolTypeXdr.LIQUIDITY_POOL_CONSTANT_PRODUCT
  }

  companion object {

    fun decode(reader: XdrReader): LiquidityPoolEntryBodyXdr {
      val discriminant = LiquidityPoolTypeXdr.decode(reader)
      return when (discriminant) {
        LiquidityPoolTypeXdr.LIQUIDITY_POOL_CONSTANT_PRODUCT -> {
          val value = LiquidityPoolEntryConstantProductXdr.decode(reader)
          ConstantProduct(value)
        }
        else -> throw IllegalArgumentException("Unknown LiquidityPoolEntryBodyXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): LiquidityPoolEntryBodyXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LiquidityPoolEntryBodyXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LiquidityPoolEntryBodyXdr {
      val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
      return when (arm) {
        "liquidity_pool_constant_product" -> ConstantProduct(LiquidityPoolEntryConstantProductXdr.fromXdrJsonTree(value))
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is ConstantProduct -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is ConstantProduct -> buildJsonObject { put("liquidity_pool_constant_product", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
