// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LiquidityPoolParametersXdr"

/**
 * XDR Source:
 * union LiquidityPoolParameters switch (LiquidityPoolType type)
 * {
 * case LIQUIDITY_POOL_CONSTANT_PRODUCT:
 *     LiquidityPoolConstantProductParameters constantProduct;
 * };
 */
sealed class LiquidityPoolParametersXdr {
  abstract val discriminant: LiquidityPoolTypeXdr

  data class ConstantProduct(
    val value: LiquidityPoolConstantProductParametersXdr
  ) : LiquidityPoolParametersXdr() {
    override val discriminant: LiquidityPoolTypeXdr = LiquidityPoolTypeXdr.LIQUIDITY_POOL_CONSTANT_PRODUCT
  }

  companion object {

    fun decode(reader: XdrReader): LiquidityPoolParametersXdr {
      val discriminant = LiquidityPoolTypeXdr.decode(reader)
      return when (discriminant) {
        LiquidityPoolTypeXdr.LIQUIDITY_POOL_CONSTANT_PRODUCT -> {
          val value = LiquidityPoolConstantProductParametersXdr.decode(reader)
          ConstantProduct(value)
        }
        else -> throw IllegalArgumentException("Unknown LiquidityPoolParametersXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): LiquidityPoolParametersXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LiquidityPoolParametersXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LiquidityPoolParametersXdr {
      val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
      return when (arm) {
        "liquidity_pool_constant_product" -> ConstantProduct(LiquidityPoolConstantProductParametersXdr.fromXdrJsonTree(value))
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is ConstantProduct -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is ConstantProduct -> buildJsonObject { put("liquidity_pool_constant_product", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
