// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "LiquidityPoolConstantProductParametersXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("asset_a", "asset_b", "fee")

/**
 * XDR Source:
 * struct LiquidityPoolConstantProductParameters
 * {
 *     Asset assetA; // assetA < assetB
 *     Asset assetB;
 *     int32 fee; // Fee is in basis points, so the actual rate is (fee/100)%
 * };
 */
data class LiquidityPoolConstantProductParametersXdr(
  /** assetA < assetB */
  val assetA: AssetXdr,
  val assetB: AssetXdr,
  /** Fee is in basis points, so the actual rate is (fee/100)% */
  val fee: Int32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): LiquidityPoolConstantProductParametersXdr {
      val assetA = AssetXdr.decode(reader)
      val assetB = AssetXdr.decode(reader)
      val fee = Int32Xdr.decode(reader)
      return LiquidityPoolConstantProductParametersXdr(assetA, assetB, fee)
    }

    fun fromXdrJson(json: String): LiquidityPoolConstantProductParametersXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): LiquidityPoolConstantProductParametersXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): LiquidityPoolConstantProductParametersXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return LiquidityPoolConstantProductParametersXdr(
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset_a", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset_b", XDR_JSON_TYPE)),
        Int32Xdr.fromXdrJsonTree(XdrJson.field(json, "fee", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    assetA.encode(writer)
    assetB.encode(writer)
    fee.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("asset_a", assetA.toXdrJsonElement())
    put("asset_b", assetB.toXdrJsonElement())
    put("fee", fee.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
