// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct ManageSellOfferOp
 * {
 *     Asset selling;
 *     Asset buying;
 *     int64 amount; // amount being sold. if set to 0, delete the offer
 *     Price price;  // price of thing being sold in terms of what you are buying
 * 
 *     // 0=create a new offer, otherwise edit an existing offer
 *     int64 offerID;
 * };
 */
data class ManageSellOfferOpXdr(
  val selling: AssetXdr,
  val buying: AssetXdr,
  /** amount being sold. if set to 0, delete the offer */
  val amount: Int64Xdr,
  /** price of thing being sold in terms of what you are buying */
  val price: PriceXdr,
  /** 0=create a new offer, otherwise edit an existing offer */
  val offerId: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ManageSellOfferOpXdr {
      val selling = AssetXdr.decode(reader)
      val buying = AssetXdr.decode(reader)
      val amount = Int64Xdr.decode(reader)
      val price = PriceXdr.decode(reader)
      val offerId = Int64Xdr.decode(reader)
      return ManageSellOfferOpXdr(selling, buying, amount, price, offerId)
    }
  }

  fun encode(writer: XdrWriter) {
    selling.encode(writer)
    buying.encode(writer)
    amount.encode(writer)
    price.encode(writer)
    offerId.encode(writer)
  }
}
