// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ManageOfferSuccessResultOfferXdr"

/**
 * XDR Source:
 * union switch (ManageOfferEffect effect)
 *     {
 *     case MANAGE_OFFER_CREATED:
 *     case MANAGE_OFFER_UPDATED:
 *         OfferEntry offer;
 *     case MANAGE_OFFER_DELETED:
 *         void;
 *     }
 */
sealed class ManageOfferSuccessResultOfferXdr {
  abstract val discriminant: ManageOfferEffectXdr

  data class Offer(
    override val discriminant: ManageOfferEffectXdr,
    val value: OfferEntryXdr
  ) : ManageOfferSuccessResultOfferXdr()

  data object Void : ManageOfferSuccessResultOfferXdr() {
    override val discriminant: ManageOfferEffectXdr = ManageOfferEffectXdr.MANAGE_OFFER_DELETED
  }

  companion object {

    fun decode(reader: XdrReader): ManageOfferSuccessResultOfferXdr {
      val discriminant = ManageOfferEffectXdr.decode(reader)
      return when (discriminant) {
        ManageOfferEffectXdr.MANAGE_OFFER_CREATED -> {
          val value = OfferEntryXdr.decode(reader)
          Offer(discriminant, value)
        }
        ManageOfferEffectXdr.MANAGE_OFFER_UPDATED -> {
          val value = OfferEntryXdr.decode(reader)
          Offer(discriminant, value)
        }
        ManageOfferEffectXdr.MANAGE_OFFER_DELETED -> Void
        else -> throw IllegalArgumentException("Unknown ManageOfferSuccessResultOfferXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): ManageOfferSuccessResultOfferXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ManageOfferSuccessResultOfferXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ManageOfferSuccessResultOfferXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "created" -> Offer(ManageOfferEffectXdr.MANAGE_OFFER_CREATED, OfferEntryXdr.fromXdrJsonTree(value))
          "updated" -> Offer(ManageOfferEffectXdr.MANAGE_OFFER_UPDATED, OfferEntryXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "deleted" -> Void
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Offer -> {
        value.encode(writer)
      }
      is Void -> {}
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Offer -> buildJsonObject { put(discriminant.xdrJsonName, value.toXdrJsonElement()) }
    is Void -> XdrJson.name("deleted")
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
