// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ManageOfferSuccessResultXdr"

/**
 * XDR Source:
 * struct ManageOfferSuccessResult
 * {
 *     // offers that got claimed while creating this offer
 *     ClaimAtom offersClaimed<>;
 * 
 *     union switch (ManageOfferEffect effect)
 *     {
 *     case MANAGE_OFFER_CREATED:
 *     case MANAGE_OFFER_UPDATED:
 *         OfferEntry offer;
 *     case MANAGE_OFFER_DELETED:
 *         void;
 *     }
 *     offer;
 * };
 */
data class ManageOfferSuccessResultXdr(
  val offersClaimed: List<ClaimAtomXdr>,
  val offer: ManageOfferSuccessResultOfferXdr
) {
  companion object {

    fun decode(reader: XdrReader): ManageOfferSuccessResultXdr {
      val offersClaimed = List(reader.readInt()) { ClaimAtomXdr.decode(reader) }
      val offer = ManageOfferSuccessResultOfferXdr.decode(reader)
      return ManageOfferSuccessResultXdr(offersClaimed, offer)
    }

    fun fromXdrJson(json: String): ManageOfferSuccessResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ManageOfferSuccessResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ManageOfferSuccessResultXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return ManageOfferSuccessResultXdr(
        XdrJson.array(XdrJson.field(json, "offers_claimed", XDR_JSON_TYPE), XDR_JSON_TYPE, "offers_claimed").map { ClaimAtomXdr.fromXdrJsonTree(it) },
        ManageOfferSuccessResultOfferXdr.fromXdrJsonTree(XdrJson.field(json, "offer", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(offersClaimed.size)
    offersClaimed.forEach { item ->
      item.encode(writer)
    }
    offer.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("offers_claimed", XdrJson.array(offersClaimed) { it.toXdrJsonElement() })
    put("offer", offer.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
