// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "ManageBuyOfferOpXdr"

/**
 * XDR Source:
 * struct ManageBuyOfferOp
 * {
 *     Asset selling;
 *     Asset buying;
 *     int64 buyAmount; // amount being bought. if set to 0, delete the offer
 *     Price price;     // price of thing being bought in terms of what you are
 *                      // selling
 * 
 *     // 0=create a new offer, otherwise edit an existing offer
 *     int64 offerID;
 * };
 */
data class ManageBuyOfferOpXdr(
  val selling: AssetXdr,
  val buying: AssetXdr,
  /** amount being bought. if set to 0, delete the offer */
  val buyAmount: Int64Xdr,
  /** price of thing being bought in terms of what you are */
  val price: PriceXdr,
  /**
   * selling
   * 0=create a new offer, otherwise edit an existing offer
   */
  val offerId: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): ManageBuyOfferOpXdr {
      val selling = AssetXdr.decode(reader)
      val buying = AssetXdr.decode(reader)
      val buyAmount = Int64Xdr.decode(reader)
      val price = PriceXdr.decode(reader)
      val offerId = Int64Xdr.decode(reader)
      return ManageBuyOfferOpXdr(selling, buying, buyAmount, price, offerId)
    }

    fun fromXdrJson(json: String): ManageBuyOfferOpXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): ManageBuyOfferOpXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): ManageBuyOfferOpXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return ManageBuyOfferOpXdr(
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "selling", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "buying", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "buy_amount", XDR_JSON_TYPE)),
        PriceXdr.fromXdrJsonTree(XdrJson.field(json, "price", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "offer_id", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    selling.encode(writer)
    buying.encode(writer)
    buyAmount.encode(writer)
    price.encode(writer)
    offerId.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("selling", selling.toXdrJsonElement())
    put("buying", buying.toXdrJsonElement())
    put("buy_amount", buyAmount.toXdrJsonElement())
    put("price", price.toXdrJsonElement())
    put("offer_id", offerId.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
