// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * enum ManageDataResultCode
 * {
 *     // codes considered as "success" for the operation
 *     MANAGE_DATA_SUCCESS = 0,
 *     // codes considered as "failure" for the operation
 *     MANAGE_DATA_NOT_SUPPORTED_YET =
 *         -1, // The network hasn't moved to this protocol change yet
 *     MANAGE_DATA_NAME_NOT_FOUND =
 *         -2, // Trying to remove a Data Entry that isn't there
 *     MANAGE_DATA_LOW_RESERVE = -3, // not enough funds to create a new Data Entry
 *     MANAGE_DATA_INVALID_NAME = -4 // Name not a valid string
 * };
 */
enum class ManageDataResultCodeXdr(val value: Int) {
  /** codes considered as "success" for the operation */
  MANAGE_DATA_SUCCESS(0),
  /** codes considered as "failure" for the operation */
  MANAGE_DATA_NOT_SUPPORTED_YET(-1),
  MANAGE_DATA_NAME_NOT_FOUND(-2),
  /** not enough funds to create a new Data Entry */
  MANAGE_DATA_LOW_RESERVE(-3),
  /** Name not a valid string */
  MANAGE_DATA_INVALID_NAME(-4);

  companion object {

    fun decode(reader: XdrReader): ManageDataResultCodeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown ManageDataResultCodeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
