// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct OperationMeta
 * {
 *     LedgerEntryChanges changes;
 * };
 */
data class OperationMetaXdr(
  val changes: LedgerEntryChangesXdr
) {
  companion object {

    fun decode(reader: XdrReader): OperationMetaXdr {
      val changes = LedgerEntryChangesXdr.decode(reader)
      return OperationMetaXdr(changes)
    }
  }

  fun encode(writer: XdrWriter) {
    changes.encode(writer)
  }
}
