// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "PathPaymentStrictReceiveResultSuccessXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("offers", "last")

/**
 * XDR Source:
 * struct
 *     {
 *         ClaimAtom offers<>;
 *         SimplePaymentResult last;
 *     }
 */
data class PathPaymentStrictReceiveResultSuccessXdr(
  val offers: List<ClaimAtomXdr>,
  val last: SimplePaymentResultXdr
) {
  companion object {

    fun decode(reader: XdrReader): PathPaymentStrictReceiveResultSuccessXdr {
      val offers = List(reader.readInt()) { ClaimAtomXdr.decode(reader) }
      val last = SimplePaymentResultXdr.decode(reader)
      return PathPaymentStrictReceiveResultSuccessXdr(offers, last)
    }

    fun fromXdrJson(json: String): PathPaymentStrictReceiveResultSuccessXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): PathPaymentStrictReceiveResultSuccessXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): PathPaymentStrictReceiveResultSuccessXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return PathPaymentStrictReceiveResultSuccessXdr(
        XdrJson.array(XdrJson.field(json, "offers", XDR_JSON_TYPE), XDR_JSON_TYPE, "offers").map { ClaimAtomXdr.fromXdrJsonTree(it) },
        SimplePaymentResultXdr.fromXdrJsonTree(XdrJson.field(json, "last", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(offers.size)
    offers.forEach { item ->
      item.encode(writer)
    }
    last.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("offers", XdrJson.array(offers) { it.toXdrJsonElement() })
    put("last", last.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
