// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "PathPaymentStrictReceiveResultXdr"

/**
 * XDR Source:
 * union PathPaymentStrictReceiveResult switch (
 *     PathPaymentStrictReceiveResultCode code)
 * {
 * case PATH_PAYMENT_STRICT_RECEIVE_SUCCESS:
 *     struct
 *     {
 *         ClaimAtom offers<>;
 *         SimplePaymentResult last;
 *     } success;
 * case PATH_PAYMENT_STRICT_RECEIVE_MALFORMED:
 * case PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED:
 * case PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST:
 * case PATH_PAYMENT_STRICT_RECEIVE_SRC_NOT_AUTHORIZED:
 * case PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION:
 * case PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST:
 * case PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED:
 * case PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL:
 *     void;
 * case PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER:
 *     Asset noIssuer; // the asset that caused the error
 * case PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS:
 * case PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF:
 * case PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX:
 *     void;
 * };
 */
sealed class PathPaymentStrictReceiveResultXdr {
  abstract val discriminant: PathPaymentStrictReceiveResultCodeXdr

  data class Success(
    val value: PathPaymentStrictReceiveResultSuccessXdr
  ) : PathPaymentStrictReceiveResultXdr() {
    override val discriminant: PathPaymentStrictReceiveResultCodeXdr = PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SUCCESS
  }

  data class NoIssuer(
    val value: AssetXdr
  ) : PathPaymentStrictReceiveResultXdr() {
    override val discriminant: PathPaymentStrictReceiveResultCodeXdr = PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER
  }

  data class Void(
    override val discriminant: PathPaymentStrictReceiveResultCodeXdr
  ) : PathPaymentStrictReceiveResultXdr()

  companion object {

    fun decode(reader: XdrReader): PathPaymentStrictReceiveResultXdr {
      val discriminant = PathPaymentStrictReceiveResultCodeXdr.decode(reader)
      return when (discriminant) {
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SUCCESS -> {
          val value = PathPaymentStrictReceiveResultSuccessXdr.decode(reader)
          Success(value)
        }
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_MALFORMED -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SRC_NOT_AUTHORIZED -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER -> {
          val value = AssetXdr.decode(reader)
          NoIssuer(value)
        }
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF -> Void(discriminant)
        PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX -> Void(discriminant)
        else -> throw IllegalArgumentException("Unknown PathPaymentStrictReceiveResultXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): PathPaymentStrictReceiveResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): PathPaymentStrictReceiveResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): PathPaymentStrictReceiveResultXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "success" -> Success(PathPaymentStrictReceiveResultSuccessXdr.fromXdrJsonTree(value))
          "no_issuer" -> NoIssuer(AssetXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "malformed" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_MALFORMED)
        "underfunded" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_UNDERFUNDED)
        "src_no_trust" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SRC_NO_TRUST)
        "src_not_authorized" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_SRC_NOT_AUTHORIZED)
        "no_destination" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_DESTINATION)
        "no_trust" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NO_TRUST)
        "not_authorized" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_NOT_AUTHORIZED)
        "line_full" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_LINE_FULL)
        "too_few_offers" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS)
        "offer_cross_self" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_OFFER_CROSS_SELF)
        "over_sendmax" -> Void(PathPaymentStrictReceiveResultCodeXdr.PATH_PAYMENT_STRICT_RECEIVE_OVER_SENDMAX)
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Success -> {
        value.encode(writer)
      }
      is Void -> {}
      is NoIssuer -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Success -> buildJsonObject { put("success", value.toXdrJsonElement()) }
    is Void -> XdrJson.name(discriminant.xdrJsonName)
    is NoIssuer -> buildJsonObject { put("no_issuer", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
