// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "PreconditionsV2Xdr"

/**
 * XDR Source:
 * struct PreconditionsV2
 * {
 *     TimeBounds* timeBounds;
 * 
 *     // Transaction only valid for ledger numbers n such that
 *     // minLedger <= n < maxLedger (if maxLedger == 0, then
 *     // only minLedger is checked)
 *     LedgerBounds* ledgerBounds;
 * 
 *     // If NULL, only valid when sourceAccount's sequence number
 *     // is seqNum - 1.  Otherwise, valid when sourceAccount's
 *     // sequence number n satisfies minSeqNum <= n < tx.seqNum.
 *     // Note that after execution the account's sequence number
 *     // is always raised to tx.seqNum, and a transaction is not
 *     // valid if tx.seqNum is too high to ensure replay protection.
 *     SequenceNumber* minSeqNum;
 * 
 *     // For the transaction to be valid, the current ledger time must
 *     // be at least minSeqAge greater than sourceAccount's seqTime.
 *     Duration minSeqAge;
 * 
 *     // For the transaction to be valid, the current ledger number
 *     // must be at least minSeqLedgerGap greater than sourceAccount's
 *     // seqLedger.
 *     uint32 minSeqLedgerGap;
 * 
 *     // For the transaction to be valid, there must be a signature
 *     // corresponding to every Signer in this array, even if the
 *     // signature is not otherwise required by the sourceAccount or
 *     // operations.
 *     SignerKey extraSigners<2>;
 * };
 */
data class PreconditionsV2Xdr(
  val timeBounds: TimeBoundsXdr?,
  /**
   * Transaction only valid for ledger numbers n such that
   * minLedger <= n < maxLedger (if maxLedger == 0, then
   * only minLedger is checked)
   */
  val ledgerBounds: LedgerBoundsXdr?,
  /**
   * If NULL, only valid when sourceAccount's sequence number
   * is seqNum - 1.  Otherwise, valid when sourceAccount's
   * sequence number n satisfies minSeqNum <= n < tx.seqNum.
   * Note that after execution the account's sequence number
   * is always raised to tx.seqNum, and a transaction is not
   * valid if tx.seqNum is too high to ensure replay protection.
   */
  val minSeqNum: SequenceNumberXdr?,
  /**
   * For the transaction to be valid, the current ledger time must
   * be at least minSeqAge greater than sourceAccount's seqTime.
   */
  val minSeqAge: DurationXdr,
  /**
   * For the transaction to be valid, the current ledger number
   * must be at least minSeqLedgerGap greater than sourceAccount's
   * seqLedger.
   */
  val minSeqLedgerGap: Uint32Xdr,
  val extraSigners: List<SignerKeyXdr>
) {
  companion object {

    fun decode(reader: XdrReader): PreconditionsV2Xdr {
      val timeBounds = if (reader.readBoolean()) TimeBoundsXdr.decode(reader) else null
      val ledgerBounds = if (reader.readBoolean()) LedgerBoundsXdr.decode(reader) else null
      val minSeqNum = if (reader.readBoolean()) SequenceNumberXdr.decode(reader) else null
      val minSeqAge = DurationXdr.decode(reader)
      val minSeqLedgerGap = Uint32Xdr.decode(reader)
      val extraSigners = List(reader.readInt()) { SignerKeyXdr.decode(reader) }
      return PreconditionsV2Xdr(timeBounds, ledgerBounds, minSeqNum, minSeqAge, minSeqLedgerGap, extraSigners)
    }

    fun fromXdrJson(json: String): PreconditionsV2Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): PreconditionsV2Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): PreconditionsV2Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return PreconditionsV2Xdr(
        XdrJson.optional(XdrJson.field(json, "time_bounds", XDR_JSON_TYPE))?.let { TimeBoundsXdr.fromXdrJsonTree(it) },
        XdrJson.optional(XdrJson.field(json, "ledger_bounds", XDR_JSON_TYPE))?.let { LedgerBoundsXdr.fromXdrJsonTree(it) },
        XdrJson.optional(XdrJson.field(json, "min_seq_num", XDR_JSON_TYPE))?.let { SequenceNumberXdr.fromXdrJsonTree(it) },
        DurationXdr.fromXdrJsonTree(XdrJson.field(json, "min_seq_age", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "min_seq_ledger_gap", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "extra_signers", XDR_JSON_TYPE), XDR_JSON_TYPE, "extra_signers", maxLength = 2).map { SignerKeyXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    if (timeBounds != null) {
      writer.writeBoolean(true)
      timeBounds.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
    if (ledgerBounds != null) {
      writer.writeBoolean(true)
      ledgerBounds.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
    if (minSeqNum != null) {
      writer.writeBoolean(true)
      minSeqNum.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
    minSeqAge.encode(writer)
    minSeqLedgerGap.encode(writer)
    writer.writeInt(extraSigners.size)
    extraSigners.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("time_bounds", XdrJson.optional(timeBounds) { it.toXdrJsonElement() })
    put("ledger_bounds", XdrJson.optional(ledgerBounds) { it.toXdrJsonElement() })
    put("min_seq_num", XdrJson.optional(minSeqNum) { it.toXdrJsonElement() })
    put("min_seq_age", minSeqAge.toXdrJsonElement())
    put("min_seq_ledger_gap", minSeqLedgerGap.toXdrJsonElement())
    put("extra_signers", XdrJson.array(extraSigners) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
