// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import com.soneso.stellar.sdk.StrKey
import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "PublicKeyXdr"

/**
 * XDR Source:
 * union PublicKey switch (PublicKeyType type)
 * {
 * case PUBLIC_KEY_TYPE_ED25519:
 *     uint256 ed25519;
 * };
 */
sealed class PublicKeyXdr {
  abstract val discriminant: PublicKeyTypeXdr

  data class Ed25519(
    val value: Uint256Xdr
  ) : PublicKeyXdr() {
    override val discriminant: PublicKeyTypeXdr = PublicKeyTypeXdr.PUBLIC_KEY_TYPE_ED25519
  }

  companion object {

    fun decode(reader: XdrReader): PublicKeyXdr {
      val discriminant = PublicKeyTypeXdr.decode(reader)
      return when (discriminant) {
        PublicKeyTypeXdr.PUBLIC_KEY_TYPE_ED25519 -> {
          val value = Uint256Xdr.decode(reader)
          Ed25519(value)
        }
        else -> throw IllegalArgumentException("Unknown PublicKeyXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): PublicKeyXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): PublicKeyXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): PublicKeyXdr =
      Ed25519(Uint256Xdr(XdrJson.strkey(XdrJson.name(element, XDR_JSON_TYPE), XDR_JSON_TYPE, "a G strkey") { StrKey.decodeEd25519PublicKey(it) }))
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Ed25519 -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Ed25519 -> XdrJson.name(StrKey.encodeEd25519PublicKey(value.value))
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
