// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * enum RestoreFootprintResultCode
 * {
 *     // codes considered as "success" for the operation
 *     RESTORE_FOOTPRINT_SUCCESS = 0,
 * 
 *     // codes considered as "failure" for the operation
 *     RESTORE_FOOTPRINT_MALFORMED = -1,
 *     RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED = -2,
 *     RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE = -3
 * };
 */
enum class RestoreFootprintResultCodeXdr(val value: Int) {
  /** codes considered as "success" for the operation */
  RESTORE_FOOTPRINT_SUCCESS(0),
  /** codes considered as "failure" for the operation */
  RESTORE_FOOTPRINT_MALFORMED(-1),
  RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED(-2),
  RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE(-3);

  companion object {

    fun decode(reader: XdrReader): RestoreFootprintResultCodeXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown RestoreFootprintResultCodeXdr value: $value")
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }
}
