// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "RevokeSponsorshipOpXdr"

/**
 * XDR Source:
 * union RevokeSponsorshipOp switch (RevokeSponsorshipType type)
 * {
 * case REVOKE_SPONSORSHIP_LEDGER_ENTRY:
 *     LedgerKey ledgerKey;
 * case REVOKE_SPONSORSHIP_SIGNER:
 *     struct
 *     {
 *         AccountID accountID;
 *         SignerKey signerKey;
 *     } signer;
 * };
 */
sealed class RevokeSponsorshipOpXdr {
  abstract val discriminant: RevokeSponsorshipTypeXdr

  data class LedgerKey(
    val value: LedgerKeyXdr
  ) : RevokeSponsorshipOpXdr() {
    override val discriminant: RevokeSponsorshipTypeXdr = RevokeSponsorshipTypeXdr.REVOKE_SPONSORSHIP_LEDGER_ENTRY
  }

  data class Signer(
    val value: RevokeSponsorshipOpSignerXdr
  ) : RevokeSponsorshipOpXdr() {
    override val discriminant: RevokeSponsorshipTypeXdr = RevokeSponsorshipTypeXdr.REVOKE_SPONSORSHIP_SIGNER
  }

  companion object {

    fun decode(reader: XdrReader): RevokeSponsorshipOpXdr {
      val discriminant = RevokeSponsorshipTypeXdr.decode(reader)
      return when (discriminant) {
        RevokeSponsorshipTypeXdr.REVOKE_SPONSORSHIP_LEDGER_ENTRY -> {
          val value = LedgerKeyXdr.decode(reader)
          LedgerKey(value)
        }
        RevokeSponsorshipTypeXdr.REVOKE_SPONSORSHIP_SIGNER -> {
          val value = RevokeSponsorshipOpSignerXdr.decode(reader)
          Signer(value)
        }
        else -> throw IllegalArgumentException("Unknown RevokeSponsorshipOpXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): RevokeSponsorshipOpXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): RevokeSponsorshipOpXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): RevokeSponsorshipOpXdr {
      val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
      return when (arm) {
        "ledger_entry" -> LedgerKey(LedgerKeyXdr.fromXdrJsonTree(value))
        "signer" -> Signer(RevokeSponsorshipOpSignerXdr.fromXdrJsonTree(value))
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is LedgerKey -> {
        value.encode(writer)
      }
      is Signer -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is LedgerKey -> buildJsonObject { put("ledger_entry", value.toXdrJsonElement()) }
    is Signer -> buildJsonObject { put("signer", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
