// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SCMapEntryXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("key", "val")

/**
 * XDR Source:
 * struct SCMapEntry
 * {
 *     SCVal key;
 *     SCVal val;
 * };
 */
data class SCMapEntryXdr(
  val key: SCValXdr,
  val `val`: SCValXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCMapEntryXdr {
      val key = SCValXdr.decode(reader)
      val `val` = SCValXdr.decode(reader)
      return SCMapEntryXdr(key, `val`)
    }

    fun fromXdrJson(json: String): SCMapEntryXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCMapEntryXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCMapEntryXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SCMapEntryXdr(
        SCValXdr.fromXdrJsonTree(XdrJson.field(json, "key", XDR_JSON_TYPE)),
        SCValXdr.fromXdrJsonTree(XdrJson.field(json, "val", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    key.encode(writer)
    `val`.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("key", key.toXdrJsonElement())
    put("val", `val`.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
