// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SCNonceKeyXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("nonce")

/**
 * XDR Source:
 * struct SCNonceKey {
 *     int64 nonce;
 * };
 */
data class SCNonceKeyXdr(
  val nonce: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCNonceKeyXdr {
      val nonce = Int64Xdr.decode(reader)
      return SCNonceKeyXdr(nonce)
    }

    fun fromXdrJson(json: String): SCNonceKeyXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCNonceKeyXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCNonceKeyXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SCNonceKeyXdr(
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "nonce", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    nonce.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("nonce", nonce.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
