// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCPNomination
 * {
 *     Hash quorumSetHash; // D
 *     Value votes<>;      // X
 *     Value accepted<>;   // Y
 * };
 */
data class SCPNominationXdr(
  /** D */
  val quorumSetHash: HashXdr,
  val votes: List<ValueXdr>,
  val accepted: List<ValueXdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCPNominationXdr {
      val quorumSetHash = HashXdr.decode(reader)
      val votes = List(reader.readInt()) { ValueXdr.decode(reader) }
      val accepted = List(reader.readInt()) { ValueXdr.decode(reader) }
      return SCPNominationXdr(quorumSetHash, votes, accepted)
    }
  }

  fun encode(writer: XdrWriter) {
    quorumSetHash.encode(writer)
    writer.writeInt(votes.size)
    votes.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(accepted.size)
    accepted.forEach { item ->
      item.encode(writer)
    }
  }
}
