// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "SCSpecUDTUnionCaseV0KindXdr"

/**
 * XDR Source:
 * enum SCSpecUDTUnionCaseV0Kind
 * {
 *     SC_SPEC_UDT_UNION_CASE_VOID_V0 = 0,
 *     SC_SPEC_UDT_UNION_CASE_TUPLE_V0 = 1
 * };
 */
enum class SCSpecUDTUnionCaseV0KindXdr(val value: Int, internal val xdrJsonName: String) {
  SC_SPEC_UDT_UNION_CASE_VOID_V0(0, "void_v0"),
  SC_SPEC_UDT_UNION_CASE_TUPLE_V0(1, "tuple_v0");

  companion object {

    fun decode(reader: XdrReader): SCSpecUDTUnionCaseV0KindXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown SCSpecUDTUnionCaseV0KindXdr value: $value")
    }

    fun fromXdrJson(json: String): SCSpecUDTUnionCaseV0KindXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCSpecUDTUnionCaseV0KindXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCSpecUDTUnionCaseV0KindXdr {
      val name = XdrJson.name(element, XDR_JSON_TYPE)
      return findXdrJsonName(name) ?: XdrJson.unknownMember(XDR_JSON_TYPE, name)
    }

    internal fun findXdrJsonName(name: String): SCSpecUDTUnionCaseV0KindXdr? = entries.find { it.xdrJsonName == name }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.name(xdrJsonName)

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
