// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecFunctionInputV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string name<30>;
 *     SCSpecTypeDef type;
 * };
 */
data class SCSpecFunctionInputV0Xdr(
  val doc: String,
  val name: String,
  val type: SCSpecTypeDefXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecFunctionInputV0Xdr {
      val doc = reader.readString()
      val name = reader.readString()
      val type = SCSpecTypeDefXdr.decode(reader)
      return SCSpecFunctionInputV0Xdr(doc, name, type)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(name)
    type.encode(writer)
  }
}
