// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecEventParamV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string name<30>;
 *     SCSpecTypeDef type;
 *     SCSpecEventParamLocationV0 location;
 * };
 */
data class SCSpecEventParamV0Xdr(
  val doc: String,
  val name: String,
  val type: SCSpecTypeDefXdr,
  val location: SCSpecEventParamLocationV0Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecEventParamV0Xdr {
      val doc = reader.readString()
      val name = reader.readString()
      val type = SCSpecTypeDefXdr.decode(reader)
      val location = SCSpecEventParamLocationV0Xdr.decode(reader)
      return SCSpecEventParamV0Xdr(doc, name, type, location)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(name)
    type.encode(writer)
    location.encode(writer)
  }
}
