// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SCSpecTypeVecXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("element_type")

/**
 * XDR Source:
 * struct SCSpecTypeVec
 * {
 *     SCSpecTypeDef elementType;
 * };
 */
data class SCSpecTypeVecXdr(
  val elementType: SCSpecTypeDefXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeVecXdr {
      val elementType = SCSpecTypeDefXdr.decode(reader)
      return SCSpecTypeVecXdr(elementType)
    }

    fun fromXdrJson(json: String): SCSpecTypeVecXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCSpecTypeVecXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCSpecTypeVecXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SCSpecTypeVecXdr(
        SCSpecTypeDefXdr.fromXdrJsonTree(XdrJson.field(json, "element_type", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    elementType.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("element_type", elementType.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
