// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SCSpecUDTErrorEnumV0Xdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("doc", "lib", "name", "cases")

/**
 * XDR Source:
 * struct SCSpecUDTErrorEnumV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string lib<80>;
 *     string name<60>;
 *     SCSpecUDTErrorEnumCaseV0 cases<>;
 * };
 */
data class SCSpecUDTErrorEnumV0Xdr(
  val doc: String,
  val lib: String,
  val name: String,
  val cases: List<SCSpecUDTErrorEnumCaseV0Xdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecUDTErrorEnumV0Xdr {
      val doc = reader.readString()
      val lib = reader.readString()
      val name = reader.readString()
      val cases = List(reader.readInt()) { SCSpecUDTErrorEnumCaseV0Xdr.decode(reader) }
      return SCSpecUDTErrorEnumV0Xdr(doc, lib, name, cases)
    }

    fun fromXdrJson(json: String): SCSpecUDTErrorEnumV0Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCSpecUDTErrorEnumV0Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCSpecUDTErrorEnumV0Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SCSpecUDTErrorEnumV0Xdr(
        XdrJson.unescapeString(XdrJson.field(json, "doc", XDR_JSON_TYPE), XDR_JSON_TYPE, "doc", maxLength = SC_SPEC_DOC_LIMIT),
        XdrJson.unescapeString(XdrJson.field(json, "lib", XDR_JSON_TYPE), XDR_JSON_TYPE, "lib", maxLength = 80),
        XdrJson.unescapeString(XdrJson.field(json, "name", XDR_JSON_TYPE), XDR_JSON_TYPE, "name", maxLength = 60),
        XdrJson.array(XdrJson.field(json, "cases", XDR_JSON_TYPE), XDR_JSON_TYPE, "cases").map { SCSpecUDTErrorEnumCaseV0Xdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(lib)
    writer.writeString(name)
    writer.writeInt(cases.size)
    cases.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("doc", XdrJson.escapedString(doc))
    put("lib", XdrJson.escapedString(lib))
    put("name", XdrJson.escapedString(name))
    put("cases", XdrJson.array(cases) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
