// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecTypeOption
 * {
 *     SCSpecTypeDef valueType;
 * };
 */
data class SCSpecTypeOptionXdr(
  val valueType: SCSpecTypeDefXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeOptionXdr {
      val valueType = SCSpecTypeDefXdr.decode(reader)
      return SCSpecTypeOptionXdr(valueType)
    }
  }

  fun encode(writer: XdrWriter) {
    valueType.encode(writer)
  }
}
