// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecTypeResult
 * {
 *     SCSpecTypeDef okType;
 *     SCSpecTypeDef errorType;
 * };
 */
data class SCSpecTypeResultXdr(
  val okType: SCSpecTypeDefXdr,
  val errorType: SCSpecTypeDefXdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecTypeResultXdr {
      val okType = SCSpecTypeDefXdr.decode(reader)
      val errorType = SCSpecTypeDefXdr.decode(reader)
      return SCSpecTypeResultXdr(okType, errorType)
    }
  }

  fun encode(writer: XdrWriter) {
    okType.encode(writer)
    errorType.encode(writer)
  }
}
