// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SCSpecEventParamV0Xdr"

/**
 * XDR Source:
 * struct SCSpecEventParamV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string name<30>;
 *     SCSpecTypeDef type;
 *     SCSpecEventParamLocationV0 location;
 * };
 */
data class SCSpecEventParamV0Xdr(
  val doc: String,
  val name: String,
  val type: SCSpecTypeDefXdr,
  val location: SCSpecEventParamLocationV0Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecEventParamV0Xdr {
      val doc = reader.readString()
      val name = reader.readString()
      val type = SCSpecTypeDefXdr.decode(reader)
      val location = SCSpecEventParamLocationV0Xdr.decode(reader)
      return SCSpecEventParamV0Xdr(doc, name, type, location)
    }

    fun fromXdrJson(json: String): SCSpecEventParamV0Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SCSpecEventParamV0Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SCSpecEventParamV0Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return SCSpecEventParamV0Xdr(
        XdrJson.unescapeString(XdrJson.field(json, "doc", XDR_JSON_TYPE), XDR_JSON_TYPE, "doc", maxLength = SC_SPEC_DOC_LIMIT),
        XdrJson.unescapeString(XdrJson.field(json, "name", XDR_JSON_TYPE), XDR_JSON_TYPE, "name", maxLength = 30),
        SCSpecTypeDefXdr.fromXdrJsonTree(XdrJson.field(json, "type", "type_", XDR_JSON_TYPE)),
        SCSpecEventParamLocationV0Xdr.fromXdrJsonTree(XdrJson.field(json, "location", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(name)
    type.encode(writer)
    location.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("doc", XdrJson.escapedString(doc))
    put("name", XdrJson.escapedString(name))
    put("type", type.toXdrJsonElement())
    put("location", location.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
