// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SerializedBinaryFuseFilterXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("type", "type_", "input_hash_seed", "filter_seed", "segment_length", "segement_length_mask", "segment_count", "segment_count_length", "fingerprint_length", "fingerprints")

/**
 * XDR Source:
 * struct SerializedBinaryFuseFilter
 * {
 *     BinaryFuseFilterType type;
 * 
 *     // Seed used to hash input to filter
 *     ShortHashSeed inputHashSeed;
 * 
 *     // Seed used for internal filter hash operations
 *     ShortHashSeed filterSeed;
 *     uint32 segmentLength;
 *     uint32 segementLengthMask;
 *     uint32 segmentCount;
 *     uint32 segmentCountLength;
 *     uint32 fingerprintLength; // Length in terms of element count, not bytes
 * 
 *     // Array of uint8_t, uint16_t, or uint32_t depending on filter type
 *     opaque fingerprints<>;
 * };
 */
data class SerializedBinaryFuseFilterXdr(
  val type: BinaryFuseFilterTypeXdr,
  /** Seed used to hash input to filter */
  val inputHashSeed: ShortHashSeedXdr,
  /** Seed used for internal filter hash operations */
  val filterSeed: ShortHashSeedXdr,
  val segmentLength: Uint32Xdr,
  val segementLengthMask: Uint32Xdr,
  val segmentCount: Uint32Xdr,
  val segmentCountLength: Uint32Xdr,
  /** Length in terms of element count, not bytes */
  val fingerprintLength: Uint32Xdr,
  val fingerprints: ByteArray
) {
  companion object {

    fun decode(reader: XdrReader): SerializedBinaryFuseFilterXdr {
      val type = BinaryFuseFilterTypeXdr.decode(reader)
      val inputHashSeed = ShortHashSeedXdr.decode(reader)
      val filterSeed = ShortHashSeedXdr.decode(reader)
      val segmentLength = Uint32Xdr.decode(reader)
      val segementLengthMask = Uint32Xdr.decode(reader)
      val segmentCount = Uint32Xdr.decode(reader)
      val segmentCountLength = Uint32Xdr.decode(reader)
      val fingerprintLength = Uint32Xdr.decode(reader)
      val fingerprints = reader.readVariableOpaque()
      return SerializedBinaryFuseFilterXdr(type, inputHashSeed, filterSeed, segmentLength, segementLengthMask, segmentCount, segmentCountLength, fingerprintLength, fingerprints)
    }

    fun fromXdrJson(json: String): SerializedBinaryFuseFilterXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SerializedBinaryFuseFilterXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SerializedBinaryFuseFilterXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SerializedBinaryFuseFilterXdr(
        BinaryFuseFilterTypeXdr.fromXdrJsonTree(XdrJson.field(json, "type", "type_", XDR_JSON_TYPE)),
        ShortHashSeedXdr.fromXdrJsonTree(XdrJson.field(json, "input_hash_seed", XDR_JSON_TYPE)),
        ShortHashSeedXdr.fromXdrJsonTree(XdrJson.field(json, "filter_seed", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "segment_length", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "segement_length_mask", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "segment_count", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "segment_count_length", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "fingerprint_length", XDR_JSON_TYPE)),
        XdrJson.hex(XdrJson.field(json, "fingerprints", XDR_JSON_TYPE), XDR_JSON_TYPE, "fingerprints")
      )
    }
  }

  fun encode(writer: XdrWriter) {
    type.encode(writer)
    inputHashSeed.encode(writer)
    filterSeed.encode(writer)
    segmentLength.encode(writer)
    segementLengthMask.encode(writer)
    segmentCount.encode(writer)
    segmentCountLength.encode(writer)
    fingerprintLength.encode(writer)
    writer.writeVariableOpaque(fingerprints)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("type", type.toXdrJsonElement())
    put("input_hash_seed", inputHashSeed.toXdrJsonElement())
    put("filter_seed", filterSeed.toXdrJsonElement())
    put("segment_length", segmentLength.toXdrJsonElement())
    put("segement_length_mask", segementLengthMask.toXdrJsonElement())
    put("segment_count", segmentCount.toXdrJsonElement())
    put("segment_count_length", segmentCountLength.toXdrJsonElement())
    put("fingerprint_length", fingerprintLength.toXdrJsonElement())
    put("fingerprints", XdrJson.hex(fingerprints))
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
