// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "SetTrustLineFlagsResultXdr"

/**
 * XDR Source:
 * union SetTrustLineFlagsResult switch (SetTrustLineFlagsResultCode code)
 * {
 * case SET_TRUST_LINE_FLAGS_SUCCESS:
 *     void;
 * case SET_TRUST_LINE_FLAGS_MALFORMED:
 * case SET_TRUST_LINE_FLAGS_NO_TRUST_LINE:
 * case SET_TRUST_LINE_FLAGS_CANT_REVOKE:
 * case SET_TRUST_LINE_FLAGS_INVALID_STATE:
 * case SET_TRUST_LINE_FLAGS_LOW_RESERVE:
 *     void;
 * };
 */
sealed class SetTrustLineFlagsResultXdr {
  abstract val discriminant: SetTrustLineFlagsResultCodeXdr

  data class Void(
    override val discriminant: SetTrustLineFlagsResultCodeXdr
  ) : SetTrustLineFlagsResultXdr()

  companion object {

    fun decode(reader: XdrReader): SetTrustLineFlagsResultXdr {
      val discriminant = SetTrustLineFlagsResultCodeXdr.decode(reader)
      return when (discriminant) {
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_SUCCESS -> Void(discriminant)
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_MALFORMED -> Void(discriminant)
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_NO_TRUST_LINE -> Void(discriminant)
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_CANT_REVOKE -> Void(discriminant)
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_INVALID_STATE -> Void(discriminant)
        SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_LOW_RESERVE -> Void(discriminant)
        else -> throw IllegalArgumentException("Unknown SetTrustLineFlagsResultXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): SetTrustLineFlagsResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SetTrustLineFlagsResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SetTrustLineFlagsResultXdr {
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "success" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_SUCCESS)
        "malformed" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_MALFORMED)
        "no_trust_line" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_NO_TRUST_LINE)
        "cant_revoke" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_CANT_REVOKE)
        "invalid_state" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_INVALID_STATE)
        "low_reserve" -> Void(SetTrustLineFlagsResultCodeXdr.SET_TRUST_LINE_FLAGS_LOW_RESERVE)
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Void -> {}
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Void -> XdrJson.name(discriminant.xdrJsonName)
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
