// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SignedTimeSlicedSurveyStopCollectingMessage
 * {
 *     Signature signature;
 *     TimeSlicedSurveyStopCollectingMessage stopCollecting;
 * };
 */
data class SignedTimeSlicedSurveyStopCollectingMessageXdr(
  val signature: SignatureXdr,
  val stopCollecting: TimeSlicedSurveyStopCollectingMessageXdr
) {
  companion object {

    fun decode(reader: XdrReader): SignedTimeSlicedSurveyStopCollectingMessageXdr {
      val signature = SignatureXdr.decode(reader)
      val stopCollecting = TimeSlicedSurveyStopCollectingMessageXdr.decode(reader)
      return SignedTimeSlicedSurveyStopCollectingMessageXdr(signature, stopCollecting)
    }
  }

  fun encode(writer: XdrWriter) {
    signature.encode(writer)
    stopCollecting.encode(writer)
  }
}
