// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SimplePaymentResultXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("destination", "asset", "amount")

/**
 * XDR Source:
 * struct SimplePaymentResult
 * {
 *     AccountID destination;
 *     Asset asset;
 *     int64 amount;
 * };
 */
data class SimplePaymentResultXdr(
  val destination: AccountIDXdr,
  val asset: AssetXdr,
  val amount: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SimplePaymentResultXdr {
      val destination = AccountIDXdr.decode(reader)
      val asset = AssetXdr.decode(reader)
      val amount = Int64Xdr.decode(reader)
      return SimplePaymentResultXdr(destination, asset, amount)
    }

    fun fromXdrJson(json: String): SimplePaymentResultXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SimplePaymentResultXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SimplePaymentResultXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SimplePaymentResultXdr(
        AccountIDXdr.fromXdrJsonTree(XdrJson.field(json, "destination", XDR_JSON_TYPE)),
        AssetXdr.fromXdrJsonTree(XdrJson.field(json, "asset", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "amount", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    destination.encode(writer)
    asset.encode(writer)
    amount.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("destination", destination.toXdrJsonElement())
    put("asset", asset.toXdrJsonElement())
    put("amount", amount.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
