// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SorobanTransactionMetaExtV1Xdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("ext", "total_non_refundable_resource_fee_charged", "total_refundable_resource_fee_charged", "rent_fee_charged")

/**
 * XDR Source:
 * struct SorobanTransactionMetaExtV1
 * {
 *     ExtensionPoint ext;
 * 
 *     // The following are the components of the overall Soroban resource fee
 *     // charged for the transaction.
 *     // The following relation holds:
 *     // `resourceFeeCharged = totalNonRefundableResourceFeeCharged + totalRefundableResourceFeeCharged`
 *     // where `resourceFeeCharged` is the overall fee charged for the
 *     // transaction. Also, `resourceFeeCharged` <= `sorobanData.resourceFee`
 *     // i.e.we never charge more than the declared resource fee.
 *     // The inclusion fee for charged the Soroban transaction can be found using
 *     // the following equation:
 *     // `result.feeCharged = resourceFeeCharged + inclusionFeeCharged`.
 * 
 *     // Total amount (in stroops) that has been charged for non-refundable
 *     // Soroban resources.
 *     // Non-refundable resources are charged based on the usage declared in
 *     // the transaction envelope (such as `instructions`, `readBytes` etc.) and
 *     // is charged regardless of the success of the transaction.
 *     int64 totalNonRefundableResourceFeeCharged;
 *     // Total amount (in stroops) that has been charged for refundable
 *     // Soroban resource fees.
 *     // Currently this comprises the rent fee (`rentFeeCharged`) and the
 *     // fee for the events and return value.
 *     // Refundable resources are charged based on the actual resources usage.
 *     // Since currently refundable resources are only used for the successful
 *     // transactions, this will be `0` for failed transactions.
 *     int64 totalRefundableResourceFeeCharged;
 *     // Amount (in stroops) that has been charged for rent.
 *     // This is a part of `totalRefundableResourceFeeCharged`.
 *     int64 rentFeeCharged;
 * };
 */
data class SorobanTransactionMetaExtV1Xdr(
  val ext: ExtensionPointXdr,
  /**
   * The following are the components of the overall Soroban resource fee
   * charged for the transaction.
   * The following relation holds:
   * `resourceFeeCharged = totalNonRefundableResourceFeeCharged + totalRefundableResourceFeeCharged`
   * where `resourceFeeCharged` is the overall fee charged for the
   * transaction. Also, `resourceFeeCharged` <= `sorobanData.resourceFee`
   * i.e.we never charge more than the declared resource fee.
   * The inclusion fee for charged the Soroban transaction can be found using
   * the following equation:
   * `result.feeCharged = resourceFeeCharged + inclusionFeeCharged`.
   * Total amount (in stroops) that has been charged for non-refundable
   * Soroban resources.
   * Non-refundable resources are charged based on the usage declared in
   * the transaction envelope (such as `instructions`, `readBytes` etc.) and
   * is charged regardless of the success of the transaction.
   */
  val totalNonRefundableResourceFeeCharged: Int64Xdr,
  /**
   * Total amount (in stroops) that has been charged for refundable
   * Soroban resource fees.
   * Currently this comprises the rent fee (`rentFeeCharged`) and the
   * fee for the events and return value.
   * Refundable resources are charged based on the actual resources usage.
   * Since currently refundable resources are only used for the successful
   * transactions, this will be `0` for failed transactions.
   */
  val totalRefundableResourceFeeCharged: Int64Xdr,
  /**
   * Amount (in stroops) that has been charged for rent.
   * This is a part of `totalRefundableResourceFeeCharged`.
   */
  val rentFeeCharged: Int64Xdr
) {
  companion object {

    fun decode(reader: XdrReader): SorobanTransactionMetaExtV1Xdr {
      val ext = ExtensionPointXdr.decode(reader)
      val totalNonRefundableResourceFeeCharged = Int64Xdr.decode(reader)
      val totalRefundableResourceFeeCharged = Int64Xdr.decode(reader)
      val rentFeeCharged = Int64Xdr.decode(reader)
      return SorobanTransactionMetaExtV1Xdr(ext, totalNonRefundableResourceFeeCharged, totalRefundableResourceFeeCharged, rentFeeCharged)
    }

    fun fromXdrJson(json: String): SorobanTransactionMetaExtV1Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SorobanTransactionMetaExtV1Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SorobanTransactionMetaExtV1Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return SorobanTransactionMetaExtV1Xdr(
        ExtensionPointXdr.fromXdrJsonTree(XdrJson.field(json, "ext", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "total_non_refundable_resource_fee_charged", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "total_refundable_resource_fee_charged", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "rent_fee_charged", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    totalNonRefundableResourceFeeCharged.encode(writer)
    totalRefundableResourceFeeCharged.encode(writer)
    rentFeeCharged.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("ext", ext.toXdrJsonElement())
    put("total_non_refundable_resource_fee_charged", totalNonRefundableResourceFeeCharged.toXdrJsonElement())
    put("total_refundable_resource_fee_charged", totalRefundableResourceFeeCharged.toXdrJsonElement())
    put("rent_fee_charged", rentFeeCharged.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
