// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * union switch (int v)
 *     {
 *     case 0:
 *         void;
 *     case 1:
 *         SorobanResourcesExtV0 resourceExt;
 *     }
 */
sealed class SorobanTransactionDataExtXdr {
  abstract val discriminant: Int

  data class ResourceExt(
    val value: SorobanResourcesExtV0Xdr
  ) : SorobanTransactionDataExtXdr() {
    override val discriminant: Int = 1
  }

  data object Void : SorobanTransactionDataExtXdr() {
    override val discriminant: Int = 0
  }

  companion object {

    fun decode(reader: XdrReader): SorobanTransactionDataExtXdr {
      val discriminant = reader.readInt()
      return when (discriminant) {
        0 -> Void
        1 -> {
          val value = SorobanResourcesExtV0Xdr.decode(reader)
          ResourceExt(value)
        }
        else -> throw IllegalArgumentException("Unknown SorobanTransactionDataExtXdr discriminant: $discriminant")
      }
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(discriminant)
    when (this) {
      is Void -> {}
      is ResourceExt -> {
        value.encode(writer)
      }
    }
  }
}
