// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SorobanAddressCredentialsXdr"

/**
 * XDR Source:
 * struct SorobanAddressCredentials
 * {
 *     SCAddress address;
 *     int64 nonce;
 *     uint32 signatureExpirationLedger;
 *     SCVal signature;
 * };
 */
data class SorobanAddressCredentialsXdr(
  val address: SCAddressXdr,
  val nonce: Int64Xdr,
  val signatureExpirationLedger: Uint32Xdr,
  val signature: SCValXdr
) {
  companion object {

    fun decode(reader: XdrReader): SorobanAddressCredentialsXdr {
      val address = SCAddressXdr.decode(reader)
      val nonce = Int64Xdr.decode(reader)
      val signatureExpirationLedger = Uint32Xdr.decode(reader)
      val signature = SCValXdr.decode(reader)
      return SorobanAddressCredentialsXdr(address, nonce, signatureExpirationLedger, signature)
    }

    fun fromXdrJson(json: String): SorobanAddressCredentialsXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SorobanAddressCredentialsXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SorobanAddressCredentialsXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return SorobanAddressCredentialsXdr(
        SCAddressXdr.fromXdrJsonTree(XdrJson.field(json, "address", XDR_JSON_TYPE)),
        Int64Xdr.fromXdrJsonTree(XdrJson.field(json, "nonce", XDR_JSON_TYPE)),
        Uint32Xdr.fromXdrJsonTree(XdrJson.field(json, "signature_expiration_ledger", XDR_JSON_TYPE)),
        SCValXdr.fromXdrJsonTree(XdrJson.field(json, "signature", XDR_JSON_TYPE))
      )
    }
  }

  fun encode(writer: XdrWriter) {
    address.encode(writer)
    nonce.encode(writer)
    signatureExpirationLedger.encode(writer)
    signature.encode(writer)
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("address", address.toXdrJsonElement())
    put("nonce", nonce.toXdrJsonElement())
    put("signature_expiration_ledger", signatureExpirationLedger.toXdrJsonElement())
    put("signature", signature.toXdrJsonElement())
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
