// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SorobanAuthorizedInvocation
 * {
 *     SorobanAuthorizedFunction function;
 *     SorobanAuthorizedInvocation subInvocations<>;
 * };
 */
data class SorobanAuthorizedInvocationXdr(
  val function: SorobanAuthorizedFunctionXdr,
  val subInvocations: List<SorobanAuthorizedInvocationXdr>
) {
  companion object {

    fun decode(reader: XdrReader): SorobanAuthorizedInvocationXdr {
      val function = SorobanAuthorizedFunctionXdr.decode(reader)
      val subInvocations = List(reader.readInt()) { SorobanAuthorizedInvocationXdr.decode(reader) }
      return SorobanAuthorizedInvocationXdr(function, subInvocations)
    }
  }

  fun encode(writer: XdrWriter) {
    function.encode(writer)
    writer.writeInt(subInvocations.size)
    subInvocations.forEach { item ->
      item.encode(writer)
    }
  }
}
