// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SorobanTransactionMetaV2
 * {
 *     SorobanTransactionMetaExt ext;
 * 
 *     SCVal* returnValue;
 * };
 */
data class SorobanTransactionMetaV2Xdr(
  val ext: SorobanTransactionMetaExtXdr,
  val returnValue: SCValXdr?
) {
  companion object {

    fun decode(reader: XdrReader): SorobanTransactionMetaV2Xdr {
      val ext = SorobanTransactionMetaExtXdr.decode(reader)
      val returnValue = if (reader.readBoolean()) SCValXdr.decode(reader) else null
      return SorobanTransactionMetaV2Xdr(ext, returnValue)
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    if (returnValue != null) {
      writer.writeBoolean(true)
      returnValue.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
  }
}
