// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "SorobanCredentialsXdr"

/**
 * XDR Source:
 * union SorobanCredentials switch (SorobanCredentialsType type)
 * {
 * case SOROBAN_CREDENTIALS_SOURCE_ACCOUNT:
 *     void;
 * case SOROBAN_CREDENTIALS_ADDRESS:
 *     SorobanAddressCredentials address;
 * case SOROBAN_CREDENTIALS_ADDRESS_V2:
 *     SorobanAddressCredentials addressV2;
 * case SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES:
 *     SorobanAddressCredentialsWithDelegates addressWithDelegates;
 * };
 */
sealed class SorobanCredentialsXdr {
  abstract val discriminant: SorobanCredentialsTypeXdr

  data class Address(
    val value: SorobanAddressCredentialsXdr
  ) : SorobanCredentialsXdr() {
    override val discriminant: SorobanCredentialsTypeXdr = SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS
  }

  data class AddressV2(
    val value: SorobanAddressCredentialsXdr
  ) : SorobanCredentialsXdr() {
    override val discriminant: SorobanCredentialsTypeXdr = SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS_V2
  }

  data class AddressWithDelegates(
    val value: SorobanAddressCredentialsWithDelegatesXdr
  ) : SorobanCredentialsXdr() {
    override val discriminant: SorobanCredentialsTypeXdr = SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES
  }

  data object Void : SorobanCredentialsXdr() {
    override val discriminant: SorobanCredentialsTypeXdr = SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_SOURCE_ACCOUNT
  }

  companion object {

    fun decode(reader: XdrReader): SorobanCredentialsXdr {
      val discriminant = SorobanCredentialsTypeXdr.decode(reader)
      return when (discriminant) {
        SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_SOURCE_ACCOUNT -> Void
        SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS -> {
          val value = SorobanAddressCredentialsXdr.decode(reader)
          Address(value)
        }
        SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS_V2 -> {
          val value = SorobanAddressCredentialsXdr.decode(reader)
          AddressV2(value)
        }
        SorobanCredentialsTypeXdr.SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES -> {
          val value = SorobanAddressCredentialsWithDelegatesXdr.decode(reader)
          AddressWithDelegates(value)
        }
        else -> throw IllegalArgumentException("Unknown SorobanCredentialsXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): SorobanCredentialsXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): SorobanCredentialsXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): SorobanCredentialsXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "address" -> Address(SorobanAddressCredentialsXdr.fromXdrJsonTree(value))
          "address_v2" -> AddressV2(SorobanAddressCredentialsXdr.fromXdrJsonTree(value))
          "address_with_delegates" -> AddressWithDelegates(SorobanAddressCredentialsWithDelegatesXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "source_account" -> Void
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Void -> {}
      is Address -> {
        value.encode(writer)
      }
      is AddressV2 -> {
        value.encode(writer)
      }
      is AddressWithDelegates -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Void -> XdrJson.name("source_account")
    is Address -> buildJsonObject { put("address", value.toXdrJsonElement()) }
    is AddressV2 -> buildJsonObject { put("address_v2", value.toXdrJsonElement()) }
    is AddressWithDelegates -> buildJsonObject { put("address_with_delegates", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
