// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SorobanAuthorizationEntry
 * {
 *     SorobanCredentials credentials;
 *     SorobanAuthorizedInvocation rootInvocation;
 * };
 */
data class SorobanAuthorizationEntryXdr(
  val credentials: SorobanCredentialsXdr,
  val rootInvocation: SorobanAuthorizedInvocationXdr
) {
  companion object {

    fun decode(reader: XdrReader): SorobanAuthorizationEntryXdr {
      val credentials = SorobanCredentialsXdr.decode(reader)
      val rootInvocation = SorobanAuthorizedInvocationXdr.decode(reader)
      return SorobanAuthorizationEntryXdr(credentials, rootInvocation)
    }
  }

  fun encode(writer: XdrWriter) {
    credentials.encode(writer)
    rootInvocation.encode(writer)
  }
}
