// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "StellarValueExtXdr"

/**
 * XDR Source:
 * union switch (StellarValueType v)
 *     {
 *     case STELLAR_VALUE_BASIC:
 *         void;
 *     case STELLAR_VALUE_SIGNED:
 *         LedgerCloseValueSignature lcValueSignature;
 *     case STELLAR_VALUE_EMPTY_TX_SET:
 *         struct
 *         {
 *             Hash txSetHash;
 *             Hash previousLedgerHash;
 *             uint32 previousLedgerVersion;
 *             LedgerCloseValueSignature lcValueSignature;
 *         } proposedValue;
 *     case STELLAR_VALUE_SIGNED_MS:
 *         struct
 *         {
 *             TimePointMs closeTimeMs; // closeTime == closeTimeMs / 1000
 *             LedgerCloseValueSignature lcValueSignature;
 *         } signedMsValue;
 *     case STELLAR_VALUE_EMPTY_TX_SET_MS:
 *         struct
 *         {
 *             TimePointMs closeTimeMs; // closeTime == closeTimeMs / 1000
 *             Hash txSetHash;
 *             Hash previousLedgerHash;
 *             uint32 previousLedgerVersion;
 *             LedgerCloseValueSignature lcValueSignature;
 *         } proposedMsValue;
 *     }
 */
sealed class StellarValueExtXdr {
  abstract val discriminant: StellarValueTypeXdr

  data class LcValueSignature(
    val value: LedgerCloseValueSignatureXdr
  ) : StellarValueExtXdr() {
    override val discriminant: StellarValueTypeXdr = StellarValueTypeXdr.STELLAR_VALUE_SIGNED
  }

  data class ProposedValue(
    val value: StellarValueProposedValueXdr
  ) : StellarValueExtXdr() {
    override val discriminant: StellarValueTypeXdr = StellarValueTypeXdr.STELLAR_VALUE_EMPTY_TX_SET
  }

  data class SignedMsValue(
    val value: StellarValueSignedMsValueXdr
  ) : StellarValueExtXdr() {
    override val discriminant: StellarValueTypeXdr = StellarValueTypeXdr.STELLAR_VALUE_SIGNED_MS
  }

  data class ProposedMsValue(
    val value: StellarValueProposedMsValueXdr
  ) : StellarValueExtXdr() {
    override val discriminant: StellarValueTypeXdr = StellarValueTypeXdr.STELLAR_VALUE_EMPTY_TX_SET_MS
  }

  data object Void : StellarValueExtXdr() {
    override val discriminant: StellarValueTypeXdr = StellarValueTypeXdr.STELLAR_VALUE_BASIC
  }

  companion object {

    fun decode(reader: XdrReader): StellarValueExtXdr {
      val discriminant = StellarValueTypeXdr.decode(reader)
      return when (discriminant) {
        StellarValueTypeXdr.STELLAR_VALUE_BASIC -> Void
        StellarValueTypeXdr.STELLAR_VALUE_SIGNED -> {
          val value = LedgerCloseValueSignatureXdr.decode(reader)
          LcValueSignature(value)
        }
        StellarValueTypeXdr.STELLAR_VALUE_EMPTY_TX_SET -> {
          val value = StellarValueProposedValueXdr.decode(reader)
          ProposedValue(value)
        }
        StellarValueTypeXdr.STELLAR_VALUE_SIGNED_MS -> {
          val value = StellarValueSignedMsValueXdr.decode(reader)
          SignedMsValue(value)
        }
        StellarValueTypeXdr.STELLAR_VALUE_EMPTY_TX_SET_MS -> {
          val value = StellarValueProposedMsValueXdr.decode(reader)
          ProposedMsValue(value)
        }
        else -> throw IllegalArgumentException("Unknown StellarValueExtXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): StellarValueExtXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): StellarValueExtXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): StellarValueExtXdr {
      if (element is JsonObject) {
        val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
        return when (arm) {
          "signed" -> LcValueSignature(LedgerCloseValueSignatureXdr.fromXdrJsonTree(value))
          "empty_tx_set" -> ProposedValue(StellarValueProposedValueXdr.fromXdrJsonTree(value))
          "signed_ms" -> SignedMsValue(StellarValueSignedMsValueXdr.fromXdrJsonTree(value))
          "empty_tx_set_ms" -> ProposedMsValue(StellarValueProposedMsValueXdr.fromXdrJsonTree(value))
          else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
        }
      }
      return when (val arm = XdrJson.name(element, XDR_JSON_TYPE)) {
        "basic" -> Void
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is Void -> {}
      is LcValueSignature -> {
        value.encode(writer)
      }
      is ProposedValue -> {
        value.encode(writer)
      }
      is SignedMsValue -> {
        value.encode(writer)
      }
      is ProposedMsValue -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is Void -> XdrJson.name("basic")
    is LcValueSignature -> buildJsonObject { put("signed", value.toXdrJsonElement()) }
    is ProposedValue -> buildJsonObject { put("empty_tx_set", value.toXdrJsonElement()) }
    is SignedMsValue -> buildJsonObject { put("signed_ms", value.toXdrJsonElement()) }
    is ProposedMsValue -> buildJsonObject { put("empty_tx_set_ms", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
