// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SurveyRequestMessage
 * {
 *     NodeID surveyorPeerID;
 *     NodeID surveyedPeerID;
 *     uint32 ledgerNum;
 *     Curve25519Public encryptionKey;
 *     SurveyMessageCommandType commandType;
 * };
 */
data class SurveyRequestMessageXdr(
  val surveyorPeerId: NodeIDXdr,
  val surveyedPeerId: NodeIDXdr,
  val ledgerNum: Uint32Xdr,
  val encryptionKey: Curve25519PublicXdr,
  val commandType: SurveyMessageCommandTypeXdr
) {
  companion object {

    fun decode(reader: XdrReader): SurveyRequestMessageXdr {
      val surveyorPeerId = NodeIDXdr.decode(reader)
      val surveyedPeerId = NodeIDXdr.decode(reader)
      val ledgerNum = Uint32Xdr.decode(reader)
      val encryptionKey = Curve25519PublicXdr.decode(reader)
      val commandType = SurveyMessageCommandTypeXdr.decode(reader)
      return SurveyRequestMessageXdr(surveyorPeerId, surveyedPeerId, ledgerNum, encryptionKey, commandType)
    }
  }

  fun encode(writer: XdrWriter) {
    surveyorPeerId.encode(writer)
    surveyedPeerId.encode(writer)
    ledgerNum.encode(writer)
    encryptionKey.encode(writer)
    commandType.encode(writer)
  }
}
