// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SurveyResponseMessage
 * {
 *     NodeID surveyorPeerID;
 *     NodeID surveyedPeerID;
 *     uint32 ledgerNum;
 *     SurveyMessageCommandType commandType;
 *     EncryptedBody encryptedBody;
 * };
 */
data class SurveyResponseMessageXdr(
  val surveyorPeerId: NodeIDXdr,
  val surveyedPeerId: NodeIDXdr,
  val ledgerNum: Uint32Xdr,
  val commandType: SurveyMessageCommandTypeXdr,
  val encryptedBody: EncryptedBodyXdr
) {
  companion object {

    fun decode(reader: XdrReader): SurveyResponseMessageXdr {
      val surveyorPeerId = NodeIDXdr.decode(reader)
      val surveyedPeerId = NodeIDXdr.decode(reader)
      val ledgerNum = Uint32Xdr.decode(reader)
      val commandType = SurveyMessageCommandTypeXdr.decode(reader)
      val encryptedBody = EncryptedBodyXdr.decode(reader)
      return SurveyResponseMessageXdr(surveyorPeerId, surveyedPeerId, ledgerNum, commandType, encryptedBody)
    }
  }

  fun encode(writer: XdrWriter) {
    surveyorPeerId.encode(writer)
    surveyedPeerId.encode(writer)
    ledgerNum.encode(writer)
    commandType.encode(writer)
    encryptedBody.encode(writer)
  }
}
