// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct TimeSlicedPeerData
 * {
 *     PeerStats peerStats;
 *     uint32 averageLatencyMs;
 * };
 */
data class TimeSlicedPeerDataXdr(
  val peerStats: PeerStatsXdr,
  val averageLatencyMs: Uint32Xdr
) {
  companion object {

    fun decode(reader: XdrReader): TimeSlicedPeerDataXdr {
      val peerStats = PeerStatsXdr.decode(reader)
      val averageLatencyMs = Uint32Xdr.decode(reader)
      return TimeSlicedPeerDataXdr(peerStats, averageLatencyMs)
    }
  }

  fun encode(writer: XdrWriter) {
    peerStats.encode(writer)
    averageLatencyMs.encode(writer)
  }
}
