// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "TransactionSetV1Xdr"

/**
 * XDR Source:
 * struct TransactionSetV1
 * {
 *     Hash previousLedgerHash;
 *     TransactionPhase phases<>;
 * };
 */
data class TransactionSetV1Xdr(
  val previousLedgerHash: HashXdr,
  val phases: List<TransactionPhaseXdr>
) {
  companion object {

    fun decode(reader: XdrReader): TransactionSetV1Xdr {
      val previousLedgerHash = HashXdr.decode(reader)
      val phases = List(reader.readInt()) { TransactionPhaseXdr.decode(reader) }
      return TransactionSetV1Xdr(previousLedgerHash, phases)
    }

    fun fromXdrJson(json: String): TransactionSetV1Xdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): TransactionSetV1Xdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): TransactionSetV1Xdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE)
      return TransactionSetV1Xdr(
        HashXdr.fromXdrJsonTree(XdrJson.field(json, "previous_ledger_hash", XDR_JSON_TYPE)),
        XdrJson.array(XdrJson.field(json, "phases", XDR_JSON_TYPE), XDR_JSON_TYPE, "phases").map { TransactionPhaseXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    previousLedgerHash.encode(writer)
    writer.writeInt(phases.size)
    phases.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("previous_ledger_hash", previousLedgerHash.toXdrJsonElement())
    put("phases", XdrJson.array(phases) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
