// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct TransactionV1Envelope
 * {
 *     Transaction tx;
 *     /* Each decorated signature is a signature over the SHA256 hash of
 *      * a TransactionSignaturePayload */
 *     DecoratedSignature signatures<20>;
 * };
 */
data class TransactionV1EnvelopeXdr(
  val tx: TransactionXdr,
  val signatures: List<DecoratedSignatureXdr>
) {
  companion object {

    fun decode(reader: XdrReader): TransactionV1EnvelopeXdr {
      val tx = TransactionXdr.decode(reader)
      val signatures = List(reader.readInt()) { DecoratedSignatureXdr.decode(reader) }
      return TransactionV1EnvelopeXdr(tx, signatures)
    }
  }

  fun encode(writer: XdrWriter) {
    tx.encode(writer)
    writer.writeInt(signatures.size)
    signatures.forEach { item ->
      item.encode(writer)
    }
  }
}
