// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct TransactionResultMetaV1
 * {
 *     ExtensionPoint ext;
 * 
 *     TransactionResultPair result;
 *     LedgerEntryChanges feeProcessing;
 *     TransactionMeta txApplyProcessing;
 * 
 *     LedgerEntryChanges postTxApplyFeeProcessing;
 * };
 */
data class TransactionResultMetaV1Xdr(
  val ext: ExtensionPointXdr,
  val result: TransactionResultPairXdr,
  val feeProcessing: LedgerEntryChangesXdr,
  val txApplyProcessing: TransactionMetaXdr,
  val postTxApplyFeeProcessing: LedgerEntryChangesXdr
) {
  companion object {

    fun decode(reader: XdrReader): TransactionResultMetaV1Xdr {
      val ext = ExtensionPointXdr.decode(reader)
      val result = TransactionResultPairXdr.decode(reader)
      val feeProcessing = LedgerEntryChangesXdr.decode(reader)
      val txApplyProcessing = TransactionMetaXdr.decode(reader)
      val postTxApplyFeeProcessing = LedgerEntryChangesXdr.decode(reader)
      return TransactionResultMetaV1Xdr(ext, result, feeProcessing, txApplyProcessing, postTxApplyFeeProcessing)
    }
  }

  fun encode(writer: XdrWriter) {
    ext.encode(writer)
    result.encode(writer)
    feeProcessing.encode(writer)
    txApplyProcessing.encode(writer)
    postTxApplyFeeProcessing.encode(writer)
  }
}
