// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement

private const val XDR_JSON_TYPE = "TransactionEventStageXdr"

/**
 * XDR Source:
 * enum TransactionEventStage {
 *     // The event has happened before any one of the transactions has its
 *     // operations applied.
 *     TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS = 0,
 *     // The event has happened immediately after operations of the transaction
 *     // have been applied.
 *     TRANSACTION_EVENT_STAGE_AFTER_TX = 1,
 *     // The event has happened after every transaction had its operations
 *     // applied.
 *     TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS = 2
 * };
 */
enum class TransactionEventStageXdr(val value: Int, internal val xdrJsonName: String) {
  /**
   * The event has happened before any one of the transactions has its
   * operations applied.
   */
  TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS(0, "before_all_txs"),
  /**
   * The event has happened immediately after operations of the transaction
   * have been applied.
   */
  TRANSACTION_EVENT_STAGE_AFTER_TX(1, "after_tx"),
  /**
   * The event has happened after every transaction had its operations
   * applied.
   */
  TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS(2, "after_all_txs");

  companion object {

    fun decode(reader: XdrReader): TransactionEventStageXdr {
      val value = reader.readInt()
      return entries.find { it.value == value }
        ?: throw IllegalArgumentException("Unknown TransactionEventStageXdr value: $value")
    }

    fun fromXdrJson(json: String): TransactionEventStageXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): TransactionEventStageXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): TransactionEventStageXdr {
      val name = XdrJson.name(element, XDR_JSON_TYPE)
      return findXdrJsonName(name) ?: XdrJson.unknownMember(XDR_JSON_TYPE, name)
    }

    internal fun findXdrJsonName(name: String): TransactionEventStageXdr? = entries.find { it.xdrJsonName == name }
  }

  fun encode(writer: XdrWriter) {
    writer.writeInt(value)
  }

  fun toXdrJsonElement(): JsonElement = XdrJson.name(xdrJsonName)

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
