// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "TxSetComponentTxsMaybeDiscountedFeeXdr"

private val XDR_JSON_KEYS: Array<String> = arrayOf("base_fee", "txs")

/**
 * XDR Source:
 * struct
 *   {
 *     int64* baseFee;
 *     TransactionEnvelope txs<>;
 *   }
 */
data class TxSetComponentTxsMaybeDiscountedFeeXdr(
  val baseFee: Int64Xdr?,
  val txs: List<TransactionEnvelopeXdr>
) {
  companion object {

    fun decode(reader: XdrReader): TxSetComponentTxsMaybeDiscountedFeeXdr {
      val baseFee = if (reader.readBoolean()) Int64Xdr.decode(reader) else null
      val txs = List(reader.readInt()) { TransactionEnvelopeXdr.decode(reader) }
      return TxSetComponentTxsMaybeDiscountedFeeXdr(baseFee, txs)
    }

    fun fromXdrJson(json: String): TxSetComponentTxsMaybeDiscountedFeeXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): TxSetComponentTxsMaybeDiscountedFeeXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): TxSetComponentTxsMaybeDiscountedFeeXdr {
      val json = XdrJson.obj(element, XDR_JSON_TYPE, XDR_JSON_KEYS)
      return TxSetComponentTxsMaybeDiscountedFeeXdr(
        XdrJson.optional(XdrJson.field(json, "base_fee", XDR_JSON_TYPE))?.let { Int64Xdr.fromXdrJsonTree(it) },
        XdrJson.array(XdrJson.field(json, "txs", XDR_JSON_TYPE), XDR_JSON_TYPE, "txs").map { TransactionEnvelopeXdr.fromXdrJsonTree(it) }
      )
    }
  }

  fun encode(writer: XdrWriter) {
    if (baseFee != null) {
      writer.writeBoolean(true)
      baseFee.encode(writer)
    } else {
      writer.writeBoolean(false)
    }
    writer.writeInt(txs.size)
    txs.forEach { item ->
      item.encode(writer)
    }
  }

  fun toXdrJsonElement(): JsonElement = buildJsonObject {
    put("base_fee", XdrJson.optional(baseFee) { it.toXdrJsonElement() })
    put("txs", XdrJson.array(txs) { it.toXdrJsonElement() })
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
