// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject

private const val XDR_JSON_TYPE = "TxSetComponentXdr"

/**
 * XDR Source:
 * union TxSetComponent switch (TxSetComponentType type)
 * {
 * case TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE:
 *   struct
 *   {
 *     int64* baseFee;
 *     TransactionEnvelope txs<>;
 *   } txsMaybeDiscountedFee;
 * };
 */
sealed class TxSetComponentXdr {
  abstract val discriminant: TxSetComponentTypeXdr

  data class TxsMaybeDiscountedFee(
    val value: TxSetComponentTxsMaybeDiscountedFeeXdr
  ) : TxSetComponentXdr() {
    override val discriminant: TxSetComponentTypeXdr = TxSetComponentTypeXdr.TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE
  }

  companion object {

    fun decode(reader: XdrReader): TxSetComponentXdr {
      val discriminant = TxSetComponentTypeXdr.decode(reader)
      return when (discriminant) {
        TxSetComponentTypeXdr.TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE -> {
          val value = TxSetComponentTxsMaybeDiscountedFeeXdr.decode(reader)
          TxsMaybeDiscountedFee(value)
        }
        else -> throw IllegalArgumentException("Unknown TxSetComponentXdr discriminant: $discriminant")
      }
    }

    fun fromXdrJson(json: String): TxSetComponentXdr = fromXdrJsonTree(XdrJson.parse(json, XDR_JSON_TYPE))

    fun fromXdrJsonElement(element: JsonElement): TxSetComponentXdr = fromXdrJsonTree(XdrJson.checkDepth(element, XDR_JSON_TYPE))

    internal fun fromXdrJsonTree(element: JsonElement): TxSetComponentXdr {
      val (arm, value) = XdrJson.singleKeyObject(element, XDR_JSON_TYPE)
      return when (arm) {
        "txset_comp_txs_maybe_discounted_fee" -> TxsMaybeDiscountedFee(TxSetComponentTxsMaybeDiscountedFeeXdr.fromXdrJsonTree(value))
        else -> XdrJson.unknownArm(XDR_JSON_TYPE, arm)
      }
    }
  }

  fun encode(writer: XdrWriter) {
    discriminant.encode(writer)
    when (this) {
      is TxsMaybeDiscountedFee -> {
        value.encode(writer)
      }
    }
  }

  fun toXdrJsonElement(): JsonElement = when (this) {
    is TxsMaybeDiscountedFee -> buildJsonObject { put("txset_comp_txs_maybe_discounted_fee", value.toXdrJsonElement()) }
  }

  fun toXdrJson(): String = XdrJson.encodeToString(toXdrJsonElement())
}
