# frozen_string_literal: true

source 'https://rubygems.org'

gem 'xdrgen', git: 'https://github.com/stellar/xdrgen.git', branch: 'master'
gem 'base64'
gem 'benchmark'
gem 'bigdecimal'
gem 'logger'
gem 'mutex_m'
gem 'minitest', '~> 5.0'