name: StellarSample
options:
  bundleIdPrefix: com.stellar
targets:
  StellarSample:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - .
    dependencies:
      - framework: stellarSample/shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
        embed: true
    settings:
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/../shared/build/bin/iosSimulatorArm64/debugFramework
      PRODUCT_BUNDLE_IDENTIFIER: com.stellar.StellarSample
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.0"
