name: StellarDemo
options:
  bundleIdPrefix: com.soneso.demo
  deploymentTarget:
    macOS: 11.0
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  StellarDemo:
    type: application
    platform: macOS
    sources:
      - StellarDemo
    info:
      path: StellarDemo/Info.plist
      properties:
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
        LSMinimumSystemVersion: 11.0
        NSHumanReadableCopyright: Copyright © 2025 Stellar Development Foundation
    settings:
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(SRCROOT)/../../shared/build/bin/macosArm64/debugFramework
        - $(SRCROOT)/../../shared/build/bin/macosX64/debugFramework
      OTHER_LDFLAGS:
        - $(inherited)
        - -framework shared
      MACOSX_DEPLOYMENT_TARGET: 11.0
    dependencies:
      - framework: ../shared/build/bin/macosArm64/debugFramework/shared.framework
        embed: true
    preBuildScripts:
      - script: |
          cd "$SRCROOT/../../.."
          if [ "$(uname -m)" = "arm64" ]; then
            ./gradlew :demo:shared:linkDebugFrameworkMacosArm64
          else
            ./gradlew :demo:shared:linkDebugFrameworkMacosX64
          fi
        name: Build Kotlin Framework
        basedOnDependencyAnalysis: false
